(function(root){'use strict';const E=root.GCEngine||(typeof require!=='undefined'?require('./engine.js'):null),{D,check,integer,clone,sum,clamp,rand,pick,uid,log,item,level,unlocked,power,special,useStaff,capacity,productionLimit,craftLimit,batch,produceBatch,supplyUnit,shelf,qty,total,addLot,planTake,consume,craftPlan,manufacture,standardCost,makeStaff,order,generateCandidates,productionRank,growMaterial,nextContest,contestScore,rivalPreview,evaluation,dayLedger}=E,A=E.actions;
function pay(s,n,category='investment'){integer(n,0,1e12);check(s.money>=n,'資金が足りません');s.money-=n;s.ledger.cashOut+=n;s.ledger[category]=(s.ledger[category]||0)+n}
function rp(s,n){check(s.rp>=n,'研究Pが足りません');s.rp-=n}
function gainXP(s,n){s.companyXP+=n;while(s.levelClaimed<level(s)){s.levelClaimed++;const bonus=200;s.money+=bonus;s.ledger.otherIncome+=bonus;log(s,'会社Lv '+s.levelClaimed,'実績が積み重なりました。お祝い金200円。','growth')}}
function produce(s,p,auto=false){const i=item(s,p.id);check(i?.farm,'この素材は畑で作れません');const n=p.n===undefined?produceBatch(s):p.n;integer(n,1);check(auto||n<=produceBatch(s),'生産バッチの上限を超えています');check(auto||s.used.produce<productionLimit(s),'今日の生産枠を使い切りました');let kept=Math.min(n,Math.max(0,capacity(s)-total(s)));check(kept>0,'倉庫に空きがありません');check(kept===n||p.overflow===true,'倉庫超過分の廃棄を確認してください');pay(s,i.cost*n,'materialSpend');const q=productionRank(s,p.id);addLot(s,p.id,kept,q,q,i.cost);if(kept<n){s.ledger.waste+=n-kept;s.ledger.wasteCost+=(n-kept)*i.cost;s.stats.waste+=n-kept}if(!auto)s.used.produce++;if(s.harvestProgress?.day!==s.day)s.harvestProgress={day:s.day,items:{}};const progress=s.harvestProgress.items[p.id]||(s.harvestProgress.items[p.id]={volume:0,awarded:0});progress.volume+=kept;const earned=Math.max(0,Math.min(4+2*(s.facilities.farm-1)+s.research.production+Math.floor(power(s,'farm')/12),Math.floor(progress.volume/2))-progress.awarded);progress.awarded+=earned;useStaff(s,'farm',earned,p.id);growMaterial(s,p.id,earned);s.lastResult={title:i.name+' ×'+kept+'を収穫',text:'素材品質 '+D.ranks[q]+' ・費用 '+i.cost*n+'円'+(kept<n?' ・超過廃棄 '+(n-kept)+'個':''),kind:'harvest'}}
A.produce=(s,p)=>produce(s,p);
A.buy=(s,p)=>{const i=item(s,p.id);check(i?.buy&&unlocked(s,p.id),'まだ仕入れられません');integer(p.n,1,100000);check(p.n%supplyUnit(s)===0,'仕入れ単位は'+supplyUnit(s)+'個です');const kept=Math.min(p.n,Math.max(0,capacity(s)-total(s)));check(kept===p.n||p.overflow===true,'超過分廃棄の確認が必要です');const modifier=s.buff?.kind==='sale'?.8:s.buff?.kind==='price'?1.2:1;const unitCost=Math.round(i.cost*modifier*(1-Math.min(.15,power(s,'sales')*.003)));pay(s,unitCost*p.n,'materialSpend');if(kept){const q=E.supplyRank(s,p.id);addLot(s,p.id,kept,q,q,unitCost)}if(kept<p.n){s.stats.waste+=p.n-kept;s.ledger.waste+=p.n-kept;s.ledger.wasteCost+=(p.n-kept)*unitCost}useStaff(s,'sales');s.lastResult={title:i.name+'を仕入れました',text:'保管 '+kept+'個 / 廃棄 '+(p.n-kept)+'個 / 費用 '+unitCost*p.n+'円',kind:'buy'}};
A.craft=(s,p)=>{check(p.policy!=='trial'||s.day>=6||level(s)>=3,'試作は6日目または会社Lv3からです');if(p.policy&&p.policy!=='standard')check(s.day>=4||s.research.processing>0,'製造方針は4日目または加工研究で解放');let plan=craftPlan(s,p.id,p.n,{...p,auto:false});check(plan.ok,plan.reason);manufacture(s,plan)};
A.policy=(s,p)=>{check(D.policies[p.policy],'方針が不明です');check(p.policy==='standard'||s.day>=4||s.research.processing>0,'4日目または加工研究で解放');s.policy=p.policy};
A.accept=(s,p)=>{check(s.orders.length<2+Math.floor(s.research.sales/2),'受注枠がいっぱいです');check(s.used.accept<E.acceptLimit(s),'新規受注は1日'+E.acceptLimit(s)+'件までです');const o=s.candidates.find(x=>x.id===p.id);check(o,'この候補は更新されました');s.orders.push({...o,reward:E.quoteReward(s,o),dueDay:s.day+o.duration-1,acceptedDay:s.day,auto:false,extended:false});s.candidates=s.candidates.filter(x=>x.id!==p.id);s.used.accept++;useStaff(s,'sales');const saved=s.candidates;generateCandidates(s);s.candidates=[...saved,s.candidates[0]].slice(0,3);s.lastResult={title:'注文を引き受けました',text:item(s,o.itemId).name+' '+o.quantity+'個 / '+(s.day+o.duration-1)+'日目の営業終了まで',kind:'order'}};
A.skip=(s,p)=>{check(s.candidates.some(o=>o.id===p.id),'候補がありません');s.candidates=s.candidates.filter(o=>o.id!==p.id);s.lastResult={title:'見送りました',text:'評判は変わりません。候補は翌日に更新されます。',kind:'note'}};
function release(s,id){s.lots.forEach(l=>{if(l.reservation===id)l.reservation=null})}
function deliver(s,id){const o=s.orders.find(o=>o.id===id);check(o,'注文が見つかりません');check(o.dueDay>=s.day,'納品期限を過ぎています');const requirements=o.requirements||[{itemId:o.itemId,quantity:o.quantity}],plans=[];for(const r of requirements){const p=planTake(s,r.itemId,r.quantity,o.minQuality,o.id);check(p.ok,item(s,r.itemId).name+' '+D.ranks[o.minQuality]+'以上があと'+p.missing+'個必要です');plans.push(...p.lots)}const cost=consume(s,plans);s.money+=o.reward;s.ledger.sales+=o.reward;s.ledger.cogs+=cost;s.ledger.deliveries++;s.stats.sales+=o.reward;s.stats.delivered++;E.deliveryProgress(s,o);if(o.minQuality>=4)s.stats.highDeliveries=(s.stats.highDeliveries||0)+1;if(item(s,o.itemId).original)s.stats.originalDeliveries=(s.stats.originalDeliveries||0)+1;s.reputation+=o.rep;s.cancels[o.customer]=0;const c=s.customers[o.customer]||(s.customers[o.customer]={delivered:0,stage:0});c.delivered++;const previousStage=c.stage,stage=Math.min(3,Math.floor(c.delivered/3));const who=D.customers.find(c=>c.id===o.customer)||D.customers[0];if(stage>c.stage){c.stage=stage;log(s,who.name+'との絆が深まった',who.lines[stage],'milestone');s.rp+=10;if(stage>=1)s.guarantees[o.itemId]=Math.max(s.guarantees[o.itemId]||0,stage+1)}if(o.guarantee)s.guarantees[o.itemId]=Math.max(s.guarantees[o.itemId]||0,o.guarantee);s.mastery[o.itemId]=(s.mastery[o.itemId]||0)+2;gainXP(s,7+o.minQuality*2);s.regionStats[o.region]=(s.regionStats[o.region]||0)+1;if(s.regionStats[o.region]===8){log(s,D.regions[o.region].name+'の定番に','地域の記念看板が会社に届きました。','milestone');gainXP(s,10)}if(item(s,o.itemId).original){const r=s.recipes.find(r=>r.id===o.itemId);r.sales+=o.quantity;r.reactions.push({day:s.day,customer:who.name,text:who.lines[c.stage]})}release(s,id);s.orders=s.orders.filter(o=>o.id!==id);s.lastResult={title:'お届け、ありがとう！',text:who.name+'「'+who.lines[c.stage]+'」',sub:'報酬 '+o.reward+'円 / 販売利益 '+Math.round(o.reward-cost)+'円',kind:s.stats.delivered===1||stage>previousStage?'delivery':'routine'};log(s,who.name+'へ納品',item(s,o.itemId).name+' ×'+o.quantity+' / '+o.reward+'円','delivery')}
A.deliver=(s,p)=>deliver(s,p.id);
A.cancel=(s,p)=>{const o=s.orders.find(o=>o.id===p.id);check(o,'注文がありません');const n=(s.cancels[o.customer]||0)+1,loss=Math.min(o.loss,Math.ceil(o.loss*.25*n));s.reputation=Math.max(0,s.reputation-loss);s.cancels[o.customer]=n;release(s,o.id);s.orders=s.orders.filter(x=>x.id!==o.id);log(s,'契約をキャンセル','評判 −'+loss+'。端数は切り上げ。','warning')};
A.extend=(s,p)=>{const o=s.orders.find(o=>o.id===p.id);check(o&&!o.extended,'この契約では延長済みです');check(((s.customers[o.customer]?.delivered||0)>=1||(s.customers[o.customer]?.legacyLevel||1)>1),'1回以上納品した顧客に相談できます');o.dueDay+=2;o.reward=Math.floor(o.reward*.85);o.extended=true;log(s,'期限を2日延長','契約報酬を15%減らして調整しました。')};
A.autoDeliver=(s,p)=>{const o=s.orders.find(o=>o.id===p.id);check(o,'注文がありません');o.auto=!o.auto};
A.reserve=(s,p)=>{const o=s.orders.find(o=>o.id===p.id);check(o,'注文がありません');release(s,o.id);const takes=(o.requirements||[{itemId:o.itemId,quantity:o.quantity}]).map(r=>planTake(s,r.itemId,r.quantity,o.minQuality)),take={lots:takes.flatMap(x=>x.lots),missing:sum(takes.map(x=>x.missing))};for(const pl of take.lots){const l=s.lots.find(x=>x.lotId===pl.lotId);if(pl.amount<l.quantity){l.quantity-=pl.amount;s.lots.push({...l,lotId:uid(s,'lot'),quantity:pl.amount,reservation:o.id})}else l.reservation=o.id}s.lastResult={title:'在庫を注文用に確保',text:(o.quantity-take.missing)+'個を予約。自動加工・卸売から保護します。',kind:'note'}};
A.unlockReservation=(s,p)=>{const l=s.lots.find(l=>l.lotId===p.id);check(l,'ロットがありません');l.reservation=null};
A.mergeLots=s=>{const groups=new Map();for(const l of s.lots){const fields=Object.fromEntries(Object.keys(l).filter(k=>!['lotId','quantity'].includes(k)).sort().map(k=>[k,l[k]])),key=JSON.stringify(fields);if(groups.has(key))groups.get(key).quantity+=l.quantity;else groups.set(key,clone(l))}const before=s.lots.length;s.lots=[...groups.values()];s.lastResult={title:'同条件のロットを整理',text:before+'ロット → '+s.lots.length+'ロット。期限・品質・予約・改善回数は維持。',kind:'note'}};
A.lock=(s,p)=>{const l=s.lots.find(l=>l.lotId===p.id);check(l,'ロットがありません');l.locked=!l.locked};
A.discard=(s,p)=>{const l=s.lots.find(l=>l.lotId===p.id);check(l,'ロットがありません');integer(p.n,1,l.quantity);check(!l.reservation&&!l.locked,'予約・保護を解除してください');s.ledger.waste+=p.n;s.ledger.wasteCost+=p.n*l.unitCost;s.stats.waste+=p.n;consume(s,[{...l,amount:p.n}]);s.lastResult={title:'在庫を整理しました',text:item(s,l.itemId).name+' '+p.n+'個を廃棄',kind:'note'}};
A.improve=(s,p)=>{const l=s.lots.find(l=>l.lotId===p.id);check(l,'ロットがありません');check(!l.locked&&!l.reservation,'保護・予約中のロットは改善できません');integer(p.n,1,l.quantity);check(item(s,l.itemId).recipe,'品質改善は加工品が対象です');check(l.reworkCount<1,'このロットは改善済みです');check(l.qualityRank<Math.min(6,Math.floor(l.materialPotential+1e-8)+2),'素材の品質上限です');check(s.used.craft<craftLimit(s),'加工枠が残っていません');check(p.n<=batch(s),'1回に改善できるのは'+batch(s)+'個までです');const cost=[50,50,50,70,100,150][l.qualityRank]*p.n;rp(s,cost);const source=clone(l);consume(s,[{...l,amount:p.n}]);s.lots.push({...source,lotId:uid(s,'lot'),quantity:p.n,qualityRank:source.qualityRank+1,reworkCount:source.reworkCount+1});s.used.craft++;useStaff(s,'lab');s.lastResult={title:'ひと手間で、ひとつ上へ',text:D.ranks[source.qualityRank]+' → '+D.ranks[source.qualityRank+1]+' / 研究P '+cost+' / 期限は変わりません',kind:'quality'}};
A.research=(s,p)=>{const d=D.research[p.id];check(d,'研究がありません');check(s.research[p.id]<6,'基本研究はLv6が最大です');const cost=d.base*(s.research[p.id]+1);rp(s,cost);s.research[p.id]++;gainXP(s,3);log(s,d.name+' Lv'+s.research[p.id],d.desc,'growth');s.lastResult={title:d.name+'が進みました',text:d.desc,kind:'growth'}};
A.facility=(s,p)=>{const d=D.facilities[p.id];check(d,'施設がありません');check(s.facilities[p.id]<6,'施設はLv6が最大です');pay(s,Math.round(d.base*Math.pow(1.65,s.facilities[p.id]-1)));s.facilities[p.id]++;gainXP(s,3);log(s,d.name+'を増築',d.desc+'。今日の使用枠は維持。','milestone');s.lastResult={title:d.name+'が大きくなりました',text:d.desc,kind:'growth'}};
A.assign=(s,p)=>{const t=s.staff.find(t=>t.id===p.id);check(t&&D.roles[p.role],'配置先が不明です');if(t.usedDay===s.day){t.nextAssignment=p.role;s.lastResult={title:'明日の配置を予約',text:'今日は'+D.roles[t.assigned].name+'で効果使用済み。明日から'+D.roles[p.role].name,kind:'note'}}else{t.assigned=p.role;t.nextAssignment=null;s.lastResult={title:'今日の担当を変更',text:D.roles[p.role].name+'に配置しました。既存在庫の期限は変わりません。',kind:'note'}}};
A.train=(s,p)=>{const t=s.staff.find(t=>t.id===p.id);check(t,'スタッフがいません');pay(s,300+t.level*120);t.exp+=8;useStaffTraining(t);s.lastResult={title:t.name+'の研修',text:'経験 ＋8 / 現在Lv'+t.level,kind:'growth'}};
function useStaffTraining(t){while(t.exp>=t.level*10){t.exp-=t.level*10;t.level++}}
A.specialize=(s,p)=>{const t=s.staff.find(t=>t.id===p.id);check(t&&t.level>=3,'スタッフLv3で専門研修を解放');check(['batch','finish','fresh','harvest','study','local','small','bread'].includes(p.spec),'得意技が不明です');if(t.spec)pay(s,600);else rp(s,20);t.spec=p.spec;t.history.push({day:s.day,text:'専門研修：'+p.spec});s.lastResult={title:'得意技を選びました',text:'再訓練は600円で可能です。',kind:'growth'}};
A.supplier=(s)=>{check(s.supplierLevel<6,'仕入れ契約は最高ランクです');pay(s,1000+700*s.supplierLevel);rp(s,15+10*s.supplierLevel);s.supplierLevel++;useStaff(s,'sales');log(s,'仕入れ契約 '+D.ranks[s.supplierLevel],'今後の入荷品質が上がります。既存在庫は変わりません。','growth')};
A.standardize=(s,p)=>{check(item(s,p.id)?.recipe,'商品を選んでください');check((s.standardized[p.id]||0)<3,'標準化は3段階までです');rp(s,45+25*(s.standardized[p.id]||0));s.standardized[p.id]=(s.standardized[p.id]||0)+1;s.guarantees[p.id]=Math.max(s.guarantees[p.id]||0,Math.min(4,s.standardized[p.id]+1));log(s,item(s,p.id).name+'の製法標準化','素材条件内で'+D.ranks[s.guarantees[p.id]]+'以上を保証。','growth');s.lastResult={title:item(s,p.id).name+'の製法を標準化',text:'素材条件内で'+D.ranks[s.guarantees[p.id]]+'以上を保証します。',kind:'growth'}};
A.market=(s)=>{check(s.used.analysis<1,'市場分析は1日1回です');rp(s,60);s.used.analysis++;generateCandidates(s)};
A.develop=(s,p)=>{const i=item(s,p.id);check(i?.dev&&!s.developed[p.id],'開発対象ではありません');check(s.research.recipe>=i.unlock,'レシピ研究Lv'+i.unlock+'が必要です');check(s.regions.includes(i.region)||level(s)>=i.unlock+2,'対象地域または会社Lv'+(i.unlock+2)+'が必要です');pay(s,i.devCost);rp(s,20+i.unlock*10);s.developed[p.id]=true;gainXP(s,10);log(s,'新商品「'+i.name+'」',i.tags.join('・'),'milestone')};
A.region=(s,p)=>{check(D.regions[p.id],'地域が不明です');const r=D.regions[p.id];if(!s.regions.includes(p.id)){check(s.scenario!=='local','このシナリオでは町内市場に専念します');check(level(s)>=r.lv&&s.reputation>=r.rep,'会社Lv'+r.lv+'・評判'+r.rep+'が必要です');pay(s,r.cost);s.regions.push(p.id);gainXP(s,10);log(s,r.name+'へ進出',r.desc,'milestone')}s.region=p.id};
A.invest=(s,p)=>{check(['brand','ads','quality','vip','patent'].includes(p.id),'投資が不明です');check(s.investments[p.id]<3,'この投資は3段階までです');check(level(s)>=4,'会社Lv4で解放');const prices={brand:1800,ads:1400,quality:2000,vip:2600,patent:2200};pay(s,prices[p.id]*(s.investments[p.id]+1));check(p.id!=='patent'||s.investments.patent===0,'特許ブランド化は取得済みです');s.investments[p.id]++;if(p.id==='ads'){s.reputation+=3;s.adsUntil=s.day+4;generateCandidates(s)}if(p.id==='quality'){const products=Object.keys(s.mastery).filter(k=>s.mastery[k]>=6);for(const k of products)s.guarantees[k]=Math.max(s.guarantees[k]||0,Math.min(4,s.investments.quality+1))}if(p.id==='vip'){const id=s.signature||Object.keys(s.mastery).sort((a,b)=>item(s,b).price-item(s,a).price)[0]||'bread';s.candidates[2]=order(s,id,3,Math.min(4,s.investments.vip+1),'kaede',{duration:6,challenge:true,title:'VIPからの指名注文'})}log(s,'経営への投資',p.id+'：購入した評判は会社経験に変換しません。','growth')};
A.wholesale=(s,p)=>{check(item(s,p.id),'商品が不明です');integer(p.target,0,99);s.wholesale[p.id]=p.target};
A.dailyFarm=(s,p)=>{check(['wheat','vegetable','off'].includes(p.id),'作物が不明です');integer(p.target,0,999);s.dailyCrop=p.id;s.dailyTarget=p.target};
A.autoBuild=(s,p)=>{const d=D.auto[p.id];check(d&&level(s)>=d.lv&&unlocked(s,d.item),'会社Lv・対象レシピの条件が不足しています');if(s.auto[p.id]){check(s.auto[p.id].level<4,'自動設備はLv4までです');pay(s,d.cost*s.auto[p.id].level);s.auto[p.id].level++}else{pay(s,d.cost);s.auto[p.id]={level:1,enabled:true,target:4,budget:500,minQuality:0,status:'営業終了時に稼働'}}};
A.autoConfig=(s,p)=>{const a=s.auto[p.id];check(a,'設備がありません');integer(p.target,0,999);integer(p.budget,0,100000);integer(p.minQuality,0,6);Object.assign(a,{target:p.target,budget:p.budget,minQuality:p.minQuality,enabled:!!p.enabled})};
function recipeDraft(s,p){check(s.day>=6||level(s)>=3,'試作は6日目または会社Lv3で解放');check(typeof p.name==='string'&&p.name.trim().length>0&&p.name.length<=24,'商品名は1〜24文字です');const ingredients=p.ingredients;check(ingredients&&typeof ingredients==='object','材料を選んでください');const entries=Object.entries(ingredients).filter(([,n])=>n>0);check(entries.length>0,'材料を選んでください');for(const [k,n]of entries){check(D.items[k]&&unlocked(s,k),'未解放の材料です');integer(n,1,8)}const count=sum(entries.map(([,n])=>n));check(count>=2&&count<=8,'材料は合計2〜8個です');check(entries.some(([k])=>['wheat','flour','bread','vegetable','deli','sweets','premiumBread','bento'].includes(k)),'小麦・野菜・パン・惣菜・菓子などの主素材を入れてください');check(entries.some(([k])=>k===p.main),'主素材を選んでください');const others=entries.filter(([k])=>k!==p.main),weights={[p.main]:others.length?.65:1};const otherCount=sum(others.map(([,n])=>n));for(const [k,n]of others)weights[k]=.35*n/otherCount;const affinity=E.F.analyze(ingredients),synergy=affinity.details.filter(x=>x.tier>0).length;const tagScores={};for(const [k,n]of entries)for(const t of item(s,k).tags)tagScores[t]=(tagScores[t]||0)+n*(k===p.main?2:1);const tags=Object.entries(tagScores).sort((a,b)=>b[1]-a[1]).slice(0,3).map(([k])=>k);return {name:p.name.trim(),recipe:Object.fromEntries(entries),weights,tags,fee:60,synergy,affinity}}
E.recipeDraft=recipeDraft;
A.prototype=(s,p)=>{const draft=recipeDraft(s,p);const signature=JSON.stringify(Object.fromEntries(Object.entries(draft.recipe).sort(([a],[b])=>a.localeCompare(b))))+'/'+p.main;const parent=s.recipes.find(r=>r.id===p.parent);const attempts=1+Math.max(0,...s.recipes.filter(r=>r.formula===signature).map(r=>r.attempts||0));const id=uid(s,'recipe');draft.id='original:'+id;draft.recipeVersion=(parent?.recipeVersion||0)+1;draft.formula=signature;draft.attempts=attempts;draft.completion=Math.min(100,35+clamp(draft.affinity.total*5,-15,20)+attempts*15+s.research.recipe*5);draft.formal=false;draft.sales=0;draft.reactions=[];draft.awards=[];draft.history=[...(parent?.history||[]),{day:s.day,text:parent?'配合を改訂':'初めての試作'}];draft.representative=E.staff(s,'workshop')[0]?.name||'社長';draft.parent=parent?.id||null;const plan=craftPlan(s,draft.id,1,{recipe:draft,policy:'trial'});check(plan.ok,plan.reason);s.recipes.push(draft);manufacture(s,plan);draft.lastTasting=clone(s.lastResult);for(const pair of draft.affinity.details)s.discoveries['pair:'+pair.a+'|'+pair.b]=true;s.discoveries[signature]=true;s.rp+=8;gainXP(s,3);s.lastResult={title:'「'+draft.name+'」が生まれました',text:'完成度 '+draft.completion+'% / '+draft.tags.join('・'),sub:(draft.lastTasting.sub||'')+' / '+(draft.affinity.total<0?'味がぶつかる食材を1つ替えてみよう。':draft.affinity.weak?'相性は中立寄り。良い組み合わせを加えると安定します。':'良い相性が品質抽選を後押し。素材育成でも品質帯が広がります。'),kind:'quality'};log(s,'試作「'+draft.name+'」',draft.tags.join('・'),'milestone')};
A.refine=(s,p)=>{const r=s.recipes.find(r=>r.id===p.id);check(r&&!r.formal,'試作中のレシピを選んでください');rp(s,25);r.completion=Math.min(100,r.completion+20);r.history.push({day:s.day,text:'製法を研究し完成度＋20'});s.lastResult={title:'製法の理解が進みました',text:'完成度 '+r.completion+'% / 素材上限は変わりません',kind:'growth'}};
A.formalize=(s,p)=>{const r=s.recipes.find(r=>r.id===p.id);check(r&&r.completion>=100&&!r.formal,'完成度100%の試作レシピが必要です');rp(s,35);r.formal=true;s.guarantees[r.id]=3;s.signature=r.id;r.history.push({day:s.day,text:'正式レシピ・看板商品に採用'});gainXP(s,12);log(s,'看板商品「'+r.name+'」完成','B保証は素材上限の範囲内で適用。全国品評会に出品できます。','milestone');s.lastResult={title:'わが社の看板商品、完成！',text:r.name+' / '+r.tags.join('・'),kind:'award'}};
A.signature=(s,p)=>{check(s.recipes.some(r=>r.id===p.id&&r.formal),'正式レシピが必要です');s.signature=p.id};
A.contest=(s,p)=>{const c=D.contests[p.key];check(c,'大会がありません');const day=nextContest(s,p.key);check(s.day>=Math.max(5,day-10)&&s.day<day,'受付は開催10日前〜前日です');const lot=s.lots.find(l=>l.lotId===p.lot);check(lot&&!lot.locked&&!lot.reservation&&lot.expiresAfterDay>=s.day,'出品できる在庫がありません');const i=item(s,lot.itemId);check(c.original?i.original&&i.formal:c.product?lot.itemId===c.product:!!i.recipe&&i.kind==='food','大会の対象商品ではありません');const old=s.contestEntries.find(e=>e.key===p.key&&e.day===day);if(!old)pay(s,c.fee,'fees');const score=contestScore(s,p.key,lot);const entry={key:p.key,day,lot:clone({...lot,quantity:1}),name:i.name,tags:clone(i.tags),score,representative:E.staff(s,'workshop')[0]?.id||null};consume(s,[{...lot,amount:1}]);s.contestEntries=s.contestEntries.filter(e=>!(e.key===p.key&&e.day===day));s.contestEntries.push(entry);log(s,c.name+'に出品',i.name+' / '+D.ranks[lot.qualityRank]+'。提出済みサンプルは返却されません。');s.lastResult={title:'大切な一皿を、品評会へ',text:day+'日目に審査。出品情報と品質を固定しました。',kind:'delivery'}};
A.contestCancel=(s,p)=>{const e=s.contestEntries.find(e=>e.key===p.key);check(e&&s.day<e.day,'受付期間外です');s.contestEntries=s.contestEntries.filter(x=>x!==e)};
A.rival=(s,p)=>{const r=D.rivals[p.key],lot=s.lots.find(l=>l.lotId===p.lot);check(r&&lot&&!lot.locked&&!lot.reservation&&item(s,lot.itemId)?.kind==='food','挑戦用の食品を選んでください');check(s.day>=(s.rivalCooldowns[p.key]||0),'再戦までお待ちください');const pre=rivalPreview(s,p.key,lot);pay(s,r.fee,'fees');consume(s,[{...lot,amount:1}]);const won=rand(s)<pre.chance;s.rivalCooldowns[p.key]=s.day+(won?14:3);if(won){s.money+=r.reward;s.ledger.otherIncome+=r.reward;s.rivalWins[p.key]=true;s.reputation+=3;gainXP(s,8)}log(s,r.name+'との料理対決',won?'勝利！提携：'+r.bonus:'今回は届かず。相手の得意条件は「'+r.tag+'」。','milestone');s.lastResult={title:won?'新しい仲間、新しい好敵手':'次の一皿で、再挑戦',text:r.name+' / '+(won?'勝利・報酬 '+r.reward+'円':'敗北・報酬なし')+' / 品質 '+D.ranks[lot.qualityRank],sub:'お題「'+r.tag+'」適合加点 '+pre.fit+' / 次回 '+s.rivalCooldowns[p.key]+'日目',kind:won?'award':'note'}};
A.event=(s,p)=>{check(s.event&&!s.event.story,'通常イベントはありません');const ev=D.events[s.event.index];check(ev.options.some(o=>o[0]===p.choice),'選択肢が不明です');const choice=p.choice;switch(ev.kind){case'sale':if(choice==='invite')s.nextBuff={kind:'sale'};else s.rp+=12;break;case'idea':if(choice==='quality')s.rp+=18;else s.staff.forEach(t=>{t.exp+=3;useStaffTraining(t)});break;case'tv':if(choice==='local')s.reputation+=3;else s.rp+=15;break;case'price':if(choice==='deal')pay(s,200,'fees');else s.nextBuff={kind:'price'};break;case'group':if(choice==='order')s.candidates[2]=order(s,'salad',4,0,'sakura',{reward:1500,title:'町の集まり・団体注文'});break;case'word':if(choice==='rep')s.reputation+=3;else s.rp+=12;break;case'repair':if(choice==='fix')pay(s,200,'fees');else s.nextBuff={kind:'repair'};break;case'delivery':if(choice==='pay')pay(s,150,'fees');else if(choice==='negotiate')rp(s,10);else s.nextBuff={kind:'delivery'};break}s.event=null;log(s,ev.name,ev.options.find(o=>o[0]===choice)[1])};
function runAutomation(s){const outputs=[];if(s.dailyCrop!=='off'){const n=Math.min(2+s.facilities.farm-1,Math.max(0,s.dailyTarget-qty(s,s.dailyCrop)),Math.max(0,capacity(s)-total(s)));if(n>0&&s.money>=item(s,s.dailyCrop).cost*n){produce(s,{id:s.dailyCrop,n},true);outputs.push(item(s,s.dailyCrop).name+' '+n+'個')}}for(const [key,d]of Object.entries(D.auto)){const a=s.auto[key];if(!a||!a.enabled)continue;const reservedNeed=sum(s.orders.flatMap(o=>o.requirements||[{itemId:o.itemId,quantity:o.quantity}]).filter(r=>r.itemId===d.item).map(r=>r.quantity))-sum(s.lots.filter(l=>l.itemId===d.item&&l.reservation).map(l=>l.quantity));let n=Math.min(a.level+1,Math.max(0,Math.max(a.target,reservedNeed)-qty(s,d.item)));if(n<=0){a.status='目標在庫に到達';continue}if(D.items[d.item].farm){n=Math.min(n,capacity(s)-total(s));const q=productionRank(s,d.item);if(n<=0){a.status='倉庫不足';continue}if(q<a.minQuality){a.status='最低品質に未到達';continue}if(n*item(s,d.item).cost>a.budget||n*item(s,d.item).cost>s.money){a.status='予算・資金不足';continue}produce(s,{id:d.item,n},true)}else{const plan=craftPlan(s,d.item,n,{auto:true,autoBatch:a.level+1,policy:'standard'});if(!plan.ok){a.status=plan.reason;continue}if(plan.fee>a.budget){a.status='予算上限';continue}if(plan.q.floor<a.minQuality){a.status='最低品質を保証できません';continue}manufacture(s,plan,{auto:true})}a.status='本日 '+n+'個を製造';outputs.push(d.name+' '+n+'個')}return outputs}
function wholesale(s){let left=8+s.research.sales*2;for(const [id,target]of Object.entries(s.wholesale)){if(left<=0)break;const n=Math.min(target,left,qty(s,id));if(n<=0)continue;const p=planTake(s,id,n);const cost=consume(s,p.lots),value=Math.round(item(s,id).price*.42*n);s.money+=value;s.stats.sales+=value;s.stats.wholesale+=n;s.ledger.sales+=value;s.ledger.cogs+=cost;left-=n}}
function resolveContests(s){const results=[];for(const en of s.contestEntries.filter(e=>e.day===s.day)){const c=en.legacyName?{name:en.legacyName,prize:en.legacyPrize||2800}:D.contests[en.key]||{name:'旧大会',prize:2800};const score=Math.round(en.score.base+rand(s)*4-2),grade=score>=90?'優勝':score>=72?'準優勝':score>=55?'入賞':'参加賞';const money=Math.round(c.prize*(score>=90?1:score>=72?.65:score>=55?.38:.12));s.money+=money;s.ledger.otherIncome+=money;s.rp+=score>=55?25:10;s.reputation+=score>=55?6:1;gainXP(s,score>=55?12:4);const result={key:en.key,day:s.day,score,grade,money,entry:en};s.contestHistory.push(result);results.push(result);log(s,c.name+'・'+grade,en.name+' '+D.ranks[en.lot.qualityRank]+' / '+score+'点','award');const r=s.recipes.find(r=>r.id===en.lot.itemId);if(r)r.awards.push({day:s.day,contest:c.name,grade});const t=s.staff.find(t=>t.id===en.representative);if(t)t.history.push({day:s.day,text:c.name+' '+grade})}s.contestEntries=s.contestEntries.filter(e=>e.day!==s.day);return results}
function advance(s){s.day++;s.used={produce:0,craft:0,accept:0,analysis:0};for(const t of s.staff){if(t.nextAssignment){t.assigned=t.nextAssignment;t.nextAssignment=null}}s.buff=s.nextBuff;s.nextBuff=null;s.ledger=dayLedger(s);if((s.day-1)%5===0)s.trendIndex=(s.trendIndex+1)%D.trends.length;generateCandidates(s);s.event=E.morningEvent(s);s.lastResult={title:s.day+'日目、おはようございます',text:E.season(s).name+' / 流行：'+E.trend(s).name+'。今日もひとつ、工夫しよう。',kind:'morning'}}
A.nextDay=(s,p)=>{check(p.day===s.day,'この日の締めは処理済みです');check(!s.ended,'評価済みです');if(s.event&&!s.event.story){const k=D.events[s.event.index].kind,defaults={price:'accept',repair:'slow',delivery:'wait'};if(defaults[k])A.event(s,{choice:defaults[k]})}const day=s.day,auto=runAutomation(s),delegation=E.runWorkPlan(s),delivered=[];for(const o of [...s.orders])if(o.auto&&(o.requirements||[{itemId:o.itemId,quantity:o.quantity}]).every(r=>planTake(s,r.itemId,r.quantity,o.minQuality,o.id).ok)){deliver(s,o.id);delivered.push(o.id)}wholesale(s);const financeWork=E.runFinanceWork(s);const pendingOrders=s.orders.map(o=>({id:o.id,itemId:o.itemId,dueDay:o.dueDay}));const contests=resolveContests(s),failed=[];for(const o of s.orders.filter(o=>o.dueDay<=day)){s.reputation=Math.max(0,s.reputation-o.loss);s.stats.failed++;failed.push(item(s,o.itemId).name);release(s,o.id);log(s,'注文期限を超過',item(s,o.itemId).name+' / 評判 −'+o.loss,'warning')}s.orders=s.orders.filter(o=>o.dueDay>day);const expired=s.lots.filter(l=>l.expiresAfterDay<=day);s.ledger.waste+=sum(expired.map(l=>l.quantity));s.stats.waste+=sum(expired.map(l=>l.quantity));s.ledger.wasteCost+=sum(expired.map(l=>l.quantity*l.unitCost));s.lots=s.lots.filter(l=>l.expiresAfterDay>day);const research=4+s.facilities.lab*4+Math.floor(power(s,'lab')/2)+(special(s,'lab','study')?4:0)+(s.rivalWins.lab?3:0);s.rp+=research;useStaff(s,'lab');const operating=Math.min(s.money,E.operatingCost(s));pay(s,operating,'operating');const salesProfit=s.ledger.sales-s.ledger.cogs,profit=salesProfit+(s.ledger.contractIncome||0)-s.ledger.wasteCost-operating-s.ledger.fees-(s.ledger.diningCost||0);s.stats.profit+=profit;const report={day,...clone(s.ledger),endCash:s.money,cashChange:s.money-s.ledger.startCash,salesProfit,profit,research,auto,delegation,financeWork,pendingOrders,delivered:delivered.length+delegation.delivered,failed,contests,expired:expired.map(l=>({name:item(s,l.itemId).name,n:l.quantity}))};s.reports.unshift(report);s.reports=s.reports.slice(0,90);s.lastDayTransaction={day,transactionSeq:s.transactionSeq+1,report:clone(report)};
const endDay=D.scenarios[s.scenario].days;if(day===endDay&&!s.initialEvaluation){s.initialEvaluation=evaluation(s);s.ended=true;log(s,'会社の最初の物語が完成',s.initialEvaluation.ending,'milestone');s.lastResult={title:endDay+'日間、おつかれさまでした',text:s.initialEvaluation.ending,kind:'ending'}}else{if(s.endless&&day%60===0){const current=evaluation(s),previous=(s.reevaluations||[])[0]||s.initialEvaluation;current.delta={delivered:s.stats.delivered-previous.stats.delivered,sales:s.stats.sales-previous.stats.sales,highQuality:s.stats.highQuality-previous.stats.highQuality};s.reevaluations=s.reevaluations||[];s.reevaluations.unshift(current);log(s,day+'日目の節目の評価',current.ending+' / 前回から納品＋'+current.delta.delivered+'件','milestone')}advance(s)}s.lastReport=report};
A.continue=s=>{check(s.ended&&s.initialEvaluation,'初回評価後に選べます');s.endless=true;s.ended=false;advance(s)};
A.settings=(s,p)=>{if(p.bgm!==undefined){integer(p.bgm,0,100);s.settings.bgm=p.bgm}if(p.sfx!==undefined){integer(p.sfx,0,100);s.settings.sfx=p.sfx}if(p.fullReport!==undefined)s.settings.fullReport=!!p.fullReport;if(p.reduced!==undefined)s.settings.reduced=!!p.reduced;if(p.short!==undefined)s.settings.short=!!p.short};
A.rename=(s,p)=>{check(typeof p.name==='string'&&p.name.trim().length>0&&p.name.length<=24,'会社名は1〜24文字です');s.name=p.name.trim()};
E.pay=pay;E.gainXP=gainXP;E.runAutomation=runAutomation;E.resolveContests=resolveContests;
if(typeof module!=='undefined'){module.exports=E;require('./planning.js');require('./recruitment.js');require('./finance.js');require('./advisor.js');require('./guidance.js');require('./dining.js');require('./progression.js')}
})(typeof globalThis!=='undefined'?globalThis:this);
