/* Optional customer-led menu puzzles: no new currency, deadline, RNG or daily chore. */
(function(root){'use strict';
const E=root.GCEngine||(typeof require!=='undefined'?require('./engine.js'):null),{D,check,integer,item,clone}=E;
D.dining=[
 {id:'picnic',title:'川辺のピクニック',customer:'rikuto',day:6,level:3,body:'練習のあとは川辺へ。片手で食べるか、みんなで広げるか。どんな二品を持っていこう？',options:[{name:'歩きながらの軽食',tags:['携帯','さっぱり'],service:'box',line:'練習帰りにも、歩きながら食べやすかった！'},{name:'芝生に広げる昼ごはん',tags:['彩り','満足'],service:'table',line:'みんなで並べたら、芝生が小さな食堂になったよ。'}]},
 {id:'reading',title:'雨の日の読み聞かせ',customer:'momo',day:16,level:6,body:'本屋のすみで、絵本の続きを。甘い休憩と、家族の軽い夕食、どちらの時間をつくる？',options:[{name:'絵本のあとのおやつ',tags:['まろやか','彩り'],service:'table',line:'お話の色が、お皿の上まで続いているみたい。'},{name:'おうちに持ち帰るごはん',tags:['家庭的','携帯'],service:'box',line:'帰ってからも、お話をしながら家族で楽しめました。'}]},
 {id:'meeting',title:'アイデアが生まれる食卓',customer:'makoto',day:31,level:9,body:'仕事仲間と過ごす一日。短い休憩にするか、一区切りの食事にするか、メニューから考えよう。',options:[{name:'会議の合間のリフレッシュ',tags:['さっぱり','携帯'],service:'box',line:'片付けも早くて、気持ちよく次のアイデアへ進めたよ。'},{name:'仕事終わりの小さな打ち上げ',tags:['濃厚','満足'],service:'table',line:'今日はがんばったね、って伝わる二品でした。'}]},
 {id:'gift',title:'町の思い出を、一皿に',customer:'nagi',day:46,level:12,body:'旅の最後に、この町の味を。おみやげの箱と、出発前の食卓から好きな届け方を選ぼう。',options:[{name:'旅先からの贈り物',tags:['彩り','香ばしい'],service:'box',line:'箱を開けた人にも、旅の続きを届けられました。'},{name:'もう一度食べたい町の味',tags:['家庭的','まろやか'],service:'table',line:'旅の終わりが、また来たい理由になりました。'}]}
];
const services={box:'ひとり分の持ち帰り箱',table:'みんなで囲む食卓'};
const available=(s,d)=>s.day>=d.day||E.level(s)>=d.level;
function diningLots(s){return s.lots.filter(l=>item(s,l.itemId)?.kind==='food'&&!l.locked&&!l.reservation&&l.expiresAfterDay>=s.day).sort((a,b)=>a.expiresAfterDay-b.expiresAfterDay||a.qualityRank-b.qualityRank)}
function diningPreview(s,p){try{const a=s.dining.active,d=D.dining.find(d=>d.id===a?.id);check(d,'先に企画を1つ選んでください');check(Array.isArray(p.lots)&&p.lots.length===2&&p.lots[0]!==p.lots[1],'料理を2品選んでください');const availableLots=diningLots(s),lots=p.lots.map(id=>availableLots.find(l=>l.lotId===id));check(lots.every(Boolean),'出せる完成品が足りません。予約・保護品・期限切れは使えません');check(lots[0].itemId!==lots[1].itemId,'違う料理を2品選ぶと、組み合わせを考えられます');check(Object.hasOwn(services,p.service),'届け方を選んでください');const brief=d.options[a.option],foods=lots.map(l=>item(s,l.itemId)),allTags=[...new Set(foods.flatMap(f=>f.tags||[]))],matches=brief.tags.filter(t=>allTags.includes(t)),misses=brief.tags.filter(t=>!allTags.includes(t));const distinct=foods[0].tags.some(t=>!foods[1].tags.includes(t))&&foods[1].tags.some(t=>!foods[0].tags.includes(t));const fit=matches.length*30,balance=distinct?14:6,service=p.service===brief.service?14:0,quality=Math.round((lots[0].qualityRank+lots[1].qualityRank));const score=fit+balance+service+quality,grade=score>=85?'忘れられない食卓':score>=65?'また食べたい食卓':score>=40?'工夫が伝わる食卓':'次の工夫が見えた食卓',reward=s.dining.album.some(r=>r.id===d.id)?0:20+Math.floor(score/5);return {ok:true,score,grade,fit,balance,service,quality,matches,misses,distinct,reward,cost:lots.reduce((n,l)=>n+l.unitCost,0),lots:clone(lots),foods:foods.map(f=>({name:f.name,tags:clone(f.tags)})),brief:clone(brief),customer:d.customer,title:d.title,feedback:[matches.length?'「'+matches.join('・')+'」が用途に合いました。':'欲しい味の特徴を加える余地があります。',distinct?'二品に違う持ち味があり、食べ比べも楽しめます。':'二品の特徴が似ています。違う持ち味を合わせると広がります。',p.service===brief.service?'届け方も、この場面にぴったりです。':'この場面は「'+services[brief.service]+'」が喜ばれます。',misses.length?'次は「'+misses.join('・')+'」を持つ商品を1品候補に。':'次は品質を磨くか、別のお題へ。']};}catch(e){return {ok:false,reason:e.message}}}
function diningPreparePreview(s,id){try{check(s.dining.active,'先に企画を選んでください');check(item(s,id)?.kind==='food'&&E.unlocked(s,id),'解放済みの料理を選んでください');const copy=clone(s),job={id:'dining-preparation',itemId:id,quantity:1,minQuality:0,temporary:true},r=E.workJob(copy,job,{preview:true,policy:s.policy==='trial'?'standard':s.policy});return {ok:true,...r};}catch(e){return {ok:false,reason:e.message}}}
E.actions.diningPrepare=(s,p)=>{const preview=diningPreparePreview(s,p.id);check(preview.ok,preview.reason);const r=E.workJob(s,{id:'dining-preparation',itemId:p.id,quantity:1,minQuality:0,temporary:true},{policy:s.policy==='trial'?'standard':s.policy});s.lastResult={title:item(s,p.id).name+'を企画の候補に',text:'使用可能な在庫1個まで準備 / 支出'+r.spent+'円・生産'+r.produce+'・加工'+r.craft+'枠',sub:'提出までは通常の在庫です。注文にも使えます。',kind:'batch'}};
E.actions.diningStart=(s,p)=>{const d=D.dining.find(d=>d.id===p.id);check(d&&available(s,d),'この企画はまだ届いていません');check(!s.dining.active,'今の企画を完成させるか、いったん戻してください');integer(p.option,0,1);s.dining.active={id:d.id,option:p.option,startedDay:s.day};s.lastResult={title:'「'+d.title+'」を考えよう',text:'期限はありません。手元の商品2品と届け方を選べます。',kind:'note'}};
E.actions.diningCancel=s=>{check(s.dining.active,'進行中の企画はありません');s.dining.active=null;s.lastResult={title:'企画をいったん戻しました',text:'費用・評判の損失なし。いつでも選び直せます。',kind:'note'}};
E.actions.diningServe=(s,p)=>{const r=diningPreview(s,p);check(r.ok,r.reason);const active=clone(s.dining.active),who=D.customers.find(c=>c.id===r.customer);E.consume(s,r.lots.map(l=>({...l,amount:1})));s.ledger.diningCost=(s.ledger.diningCost||0)+r.cost;s.rp+=r.reward;const old=s.dining.album.find(x=>x.id===active.id),record={id:active.id,option:active.option,day:s.day,score:r.score,grade:r.grade,service:p.service,menu:r.lots.map((l,i)=>({itemId:l.itemId,name:r.foods[i].name,tags:r.foods[i].tags,qualityRank:l.qualityRank,recipeVersion:l.recipeVersion})),feedback:r.feedback,rewardClaimed:true};if(!old||record.score>old.score){s.dining.album=s.dining.album.filter(x=>x.id!==active.id);s.dining.album.push(record)}s.dining.active=null;if(!old){for(const l of r.lots)s.mastery[l.itemId]=(s.mastery[l.itemId]||0)+3;const t=E.staff(s,'workshop')[0];if(t)t.history.push({day:s.day,text:r.title+'の献立づくりに参加'});}E.log(s,r.title+'・'+r.grade,r.foods.map(f=>f.name).join(' ＋ ')+' / '+r.score+'点','milestone');s.lastDining={...r,lots:undefined};s.lastResult={title:r.grade,text:who.name+'「'+(r.score>=65?r.brief.line:'この二品でやりたいことが分かりました。次の工夫も楽しみです。')+'」',sub:r.feedback.join(' ')+' / '+r.score+'点・研究P＋'+r.reward+(old?'（再挑戦の追加報酬なし）':''),kind:'dining'};};
const validate=E.validate;E.validate=s=>{validate(s);check(s.dining&&Array.isArray(s.dining.album)&&s.dining.album.length<=D.dining.length,'食卓企画の記録が不正です');const ids=new Set;for(const r of s.dining.album){check(D.dining.some(d=>d.id===r.id)&&!ids.has(r.id),'企画記録が重複または不明です');ids.add(r.id);integer(r.option,0,1);integer(r.day,1,s.day);integer(r.score,0,100);check(Object.hasOwn(services,r.service)&&r.rewardClaimed===true,'企画報酬の記録が不正です');check(Array.isArray(r.menu)&&r.menu.length===2,'献立記録が不正です');for(const m of r.menu){check(item(s,m.itemId)&&typeof m.name==='string'&&m.name.length<=100,'献立の商品が不正です');integer(m.qualityRank,0,6);integer(m.recipeVersion,0,10000);check(Array.isArray(m.tags)&&m.tags.every(t=>typeof t==='string'&&t.length<100),'献立の特徴が不正です')}}if(s.dining.active){const a=s.dining.active;check(D.dining.some(d=>d.id===a.id),'企画が不明です');integer(a.option,0,1);integer(a.startedDay,1,s.day)}if(s.ledger.diningCost!==undefined)check(Number.isFinite(s.ledger.diningCost)&&s.ledger.diningCost>=0,'試食の原価が不正です');return true};
Object.assign(E,{diningAvailable:available,diningServices:services,diningLots,diningPreview,diningPreparePreview});
})(typeof globalThis!=='undefined'?globalThis:this);
