(function(root){'use strict';
const D=root.GCData||(typeof require!=='undefined'?require('./data.js'):null),E={D,actions:{}};
const F=root.GCFlavor||(typeof require!=='undefined'?require('./flavor.js'):null);
const clone=x=>JSON.parse(JSON.stringify(x)),clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),sum=a=>a.reduce((x,y)=>x+y,0);
function check(ok,msg){if(!ok)throw Error(msg)}
function integer(v,min=0,max=1000000){check(Number.isSafeInteger(v)&&v>=min&&v<=max,'数値が有効な範囲ではありません');return v}
function hash(t){let h=2166136261;for(const c of String(t)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0||1}
function rand(s){let x=s.rng>>>0;x^=x<<13;x^=x>>>17;x^=x<<5;s.rng=x>>>0;return s.rng/4294967296}
function pick(s,a){return a[Math.floor(rand(s)*a.length)]}
function uid(s,p='id'){return p+'-'+(++s.idSeq)}
function log(s,title,text='',type='note'){s.timeline.unshift({day:s.day,title,text,type});s.timeline=s.timeline.slice(0,300)}
function item(s,id){if(id.startsWith('original:')){const r=s.recipes.find(r=>r.id===id);return r?{...r,kind:'food',price:Math.round(300+sum(Object.entries(r.recipe).map(([k,n])=>item(s,k).price*n))*.85),fee:60,original:true}:null}return D.items[id]||s.legacyItems?.[id]}
function unlocked(s,id){const i=item(s,id);if(!i)return false;if(i.original)return true;if(i.rare)return s.research.recipe>=2||s.regions.length>1;return (!i.unlock||s.research.recipe>=i.unlock||i.qualityUnlock&&s.research.quality>=i.qualityUnlock)&&(!i.dev||s.developed[id])}
const level=s=>1+Math.floor(s.companyXP/25),season=s=>D.seasons[Math.floor((s.day-1)/15)%4],trend=s=>D.trends[s.trendIndex];
function staff(s,role){return s.staff.filter(x=>x.assigned===role)}
function power(s,role){const key=D.roles[role].stat;return Math.min(45,sum(staff(s,role).map(x=>(x.stats[key]||0)+(x.level-1)*2)))}
function special(s,role,tag){return staff(s,role).some(x=>x.special===tag||x.spec===tag)}
function useStaff(s,role,n=1,product=null){for(const t of staff(s,role)){t.usedDay=s.day;t.exp+=n;while(t.exp>=t.level*10){t.exp-=t.level*10;t.level++;log(s,t.name+'がLv'+t.level+'に','得意技の研修で役割を伸ばせます。','growth')}if(product){t.products[product]=(t.products[product]||0)+n;t.lastWork=product}}}
function capacity(s){return (s.scenario==='small'?24:40)+(s.facilities.warehouse-1)*16+s.research.storage*8+Math.floor(power(s,'warehouse')/5)*5}
function productionLimit(s){return 3+s.facilities.farm-1+Math.floor(s.research.production/2)}
function craftLimit(s){return (s.scenario==='luxury'?2:5)+s.facilities.workshop-1+Math.floor(s.research.processing/2)}
function batch(s,policy=s.policy){const p=D.policies[policy];check(!!p,'製造方針が不明です');return Math.max(1,Math.floor((3+s.research.processing+Math.floor(power(s,'workshop')/10)+(special(s,'workshop','batch')?2:0))*p.size))}
function produceBatch(s){return 5+s.facilities.farm+s.research.production+Math.floor(power(s,'farm')/8)+(special(s,'farm','harvest')?1:0)}
function supplyRank(s,id){return clamp(Math.max(s.supplierLevel+(D.items[id]?.rare?1:0),s.materialRanks[id]||0),0,6)}
function supplyUnit(s){return power(s,'sales')>=8||special(s,'sales','small')?1:5}
function shelf(s){return 3+Math.floor((s.facilities.warehouse-1)/2)+Math.floor(s.research.storage/3)+(power(s,'warehouse')>=10?1:0)+(special(s,'warehouse','fresh')?1:0)}
function qty(s,id,min=0,reservation=null){return sum(s.lots.filter(l=>l.itemId===id&&l.qualityRank>=min&&l.expiresAfterDay>=s.day&&(!l.reservation||l.reservation===reservation)&&!l.locked).map(l=>l.quantity))}
const total=s=>sum(s.lots.map(l=>l.quantity));
function addLot(s,id,n,q=0,potential=q,cost=0,options={}){integer(n,1);integer(q,0,6);const l={lotId:uid(s,'lot'),itemId:id,quantity:n,qualityRank:q,materialPotential:potential,madeDay:s.day,expiresAfterDay:s.day+shelf(s)-1,unitCost:cost,reservation:null,reworkCount:0,recipeVersion:item(s,id)?.recipeVersion||0,locked:false,...options};s.lots.push(l);s.catalog[id]=Math.max(s.catalog[id]??-1,q);useStaff(s,'warehouse',1);return l}
function planTake(s,id,n,min=0,reservation=null,qualityFirst=false,allowLocked=false){let remaining=n;const out=[];const lots=s.lots.filter(l=>l.itemId===id&&l.qualityRank>=min&&l.expiresAfterDay>=s.day&&(!l.reservation||l.reservation===reservation)&&(!l.locked||allowLocked)).sort((a,b)=>(reservation?(Number(b.reservation===reservation)-Number(a.reservation===reservation)):0)||(qualityFirst?b.qualityRank-a.qualityRank:0)||a.expiresAfterDay-b.expiresAfterDay||a.qualityRank-b.qualityRank);for(const l of lots){if(remaining<=0)break;const amount=Math.min(remaining,l.quantity);out.push({...l,amount});remaining-=amount}return {ok:remaining===0,missing:remaining,lots:out}}
function consume(s,plans){let cost=0;for(const p of plans){const l=s.lots.find(l=>l.lotId===p.lotId);check(l&&l.quantity>=p.amount,'在庫が変わりました。もう一度確認してください');l.quantity-=p.amount;cost+=p.amount*l.unitCost}s.lots=s.lots.filter(l=>l.quantity>0);return cost}
function quality(s,id,plans,policy=s.policy,recipeOverride=null){const i=recipeOverride||item(s,id);const weights=i.weights||Object.fromEntries(Object.keys(i.recipe).map(k=>[k,1/Object.keys(i.recipe).length]));let potential=0,finish=0;for(const k of Object.keys(i.recipe)){const ls=plans.filter(l=>l.itemId===k),n=sum(ls.map(l=>l.amount));check(n>0,'材料の計画がありません');potential+=(weights[k]||0)*sum(ls.map(l=>l.materialPotential*l.amount))/n;finish+=(weights[k]||0)*sum(ls.map(l=>l.qualityRank*l.amount))/n}const cap=clamp(Math.floor(potential+1e-8)+2,0,6),earned=s.guarantees[id]||((i.original&&i.formal)?3:0),floor=Math.min(cap,earned);const standard=s.standardized[id]||0;let center=.12+s.research.quality*.57+(s.facilities.workshop-1)*.12+power(s,'workshop')*.037+Math.min(1.2,(s.mastery[id]||0)/35)+D.policies[policy].quality+Math.min(1.7,potential*.38)-Math.max(0,potential-finish)*.28+standard*.3;
if(special(s,'workshop','bread')&&['bread','milkBread','premiumBread'].includes(id))center+=.35;
if(special(s,'workshop','finish')&&policy==='careful')center+=.4;const team=staff(s,'farm').some(t=>(t.special==='harvest'||t.spec==='harvest')&&t.usedDay===s.day)&&special(s,'workshop','bread')&&['bread','milkBread','premiumBread'].includes(id);if(team)center+=.35;
const logs=Array.from({length:7},(_,q)=>q<floor||q>cap?-Infinity:-Math.pow((q-center)/Math.max(.25,.86-standard*.08),2)/2),maxLog=Math.max(...logs);const weightsQ=logs.map(v=>v===-Infinity?0:Math.exp(v-maxLog)),denom=sum(weightsQ),probabilities=weightsQ.map(x=>x/denom);const affinity=i.affinity||null,adjusted=F.distribution(probabilities,affinity);return {potential,cap,floor,earned,team,baseProbabilities:probabilities,affinity,probabilities:adjusted,stable:floor,likely:adjusted.indexOf(Math.max(...adjusted)),note:earned>cap?D.ranks[earned]+'保証には素材改善が必要':''}}
function craftPlan(s,id,n=1,options={}){try{integer(n,1,1000);const i=options.recipe||item(s,id);check(i?.recipe,'加工レシピがありません');check(options.recipe||unlocked(s,id),'レシピを研究・開発してください');const policy=options.policy||s.policy,limit=options.auto?options.autoBatch:batch(s,policy);check(n<=Math.max(1,limit-(s.buff?.kind==='repair'?1:0)),'1バッチは'+Math.max(1,limit-(s.buff?.kind==='repair'?1:0))+'個までです');check(options.auto||s.used.craft<craftLimit(s),'今日の加工枠を使い切りました');const plans=[],missing=[];for(const [base,amount] of Object.entries(i.recipe)){const actual=options.substitute?.[base]||base;check(actual===base||({wheat:'premiumWheat',vegetable:'freshVegetable',meat:'brandMeat',milk:'richMilk'}[base]===actual),'使えない代替素材です');const p=planTake(s,actual,amount*n,0,options.reservation,null);if(!p.ok)missing.push({id:actual,n:p.missing});plans.push(...p.lots.map(l=>({...l,recipeKey:base})))}check(!missing.length,missing.map(m=>(item(s,m.id)?.name||m.id)+' '+m.n+'個不足').join(' / '));const normalized=plans.map(p=>({...p,itemId:p.recipeKey}));const q=quality(s,id,normalized,policy,i);const fee=Math.ceil((i.fee||20)*n*D.policies[policy].fee*(s.rivalWins.volume&&policy==='mass'?.9:1));check(s.money>=fee,'加工費が不足しています');const final=total(s)-sum(plans.map(l=>l.amount))+n;check(final<=capacity(s),'加工後の倉庫容量が足りません');const materialCost=sum(plans.map(l=>l.unitCost*l.amount));return {ok:true,id,n,plans,q,fee,materialCost,totalCost:materialCost+fee,final,policy,recipe:i}}catch(e){return {ok:false,reason:e.message,id,n}}}
function manufacture(s,p,options={}){check(p.ok,p.reason);consume(s,p.plans);s.money-=p.fee;s.ledger.cashOut+=p.fee;s.ledger.direct+=p.fee;let draw=null,q=p.q.floor;if(!options.preview){if(p.q.affinity){draw=F.draw(s,p.q.baseProbabilities,p.q.affinity,rand);q=draw.quality}else{let roll=rand(s);for(q=0;q<6;q++){roll-=p.q.probabilities[q];if(roll<0)break}}}addLot(s,p.id,p.n,q,p.q.potential,(p.materialCost+p.fee)/p.n,{recipeVersion:p.recipe.recipeVersion||0,...(draw?{flavorRoll:draw}:{})});if(!options.auto)s.used.craft++;useStaff(s,'workshop',1,p.id);s.mastery[p.id]=(s.mastery[p.id]||0)+p.n;s.stats.crafted+=p.n;if(q>=4&&p.recipe.kind!=='material')s.stats.highQuality+=p.n;if(p.policy==='trial'){s.rp+=4;s.discoveries['trial:'+p.id]=true}const prev=s.records[p.id]??-1;if(q>prev){s.records[p.id]=q;log(s,'品質の新記録',p.recipe.name+' が '+D.ranks[q]+' に。','quality')}s.lastResult={title:p.recipe.name+' ×'+p.n,text:'品質 '+D.ranks[q]+' ・加工枠 '+(options.auto?'自動設備':'1')+' ・直接費 '+p.fee+'円',kind:q>prev&&q>=2?'quality':'craft',quality:q,flavorRoll:draw,sub:draw?'抽選 '+draw.raw.toFixed(1)+' ＋ 相性 '+draw.compatibility+' ＋ 偶然 '+draw.random+' → '+draw.adjusted.toFixed(1):''};return q}
function standardCost(s,id,seen=new Set()){check(!seen.has(id),'循環したレシピです');const i=item(s,id);check(i,'不明な商品');if(!i.recipe)return i.cost||0;const next=new Set(seen);next.add(id);return (i.fee||0)+sum(Object.entries(i.recipe).map(([k,n])=>standardCost(s,k,next)*n))}
function makeStaff(id){const d=D.staff.find(x=>x.id===id);return {id,name:d.name,assigned:d.role,nextAssignment:null,usedDay:0,level:1,exp:0,stats:Object.fromEntries(['production','craft','sales','research','logistics'].map((k,i)=>[k,d.stats[i]])),special:d.special,spec:null,rarity:d.rarity,trait:d.trait,products:{},history:[]}}
function dayLedger(s){return {startCash:s.money,sales:0,cogs:0,materialSpend:0,direct:0,investment:0,cashOut:0,cashIn:0,waste:0,wasteCost:0,operating:0,deliveries:0,deliveredUnits:0,fees:0,otherIncome:0}}
function newGame(seed='GOCHISOU',scenario='standard',name='こもれび食品'){check(D.scenarios[scenario],'シナリオが不明です');const s={saveSchemaVersion:D.schema,gameRulesVersion:D.rules,contentVersion:D.content,runId:'run-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8),seed:String(seed).slice(0,60),rng:hash(seed),transactionSeq:0,lastTx:null,idSeq:0,name:String(name).slice(0,24)||'こもれび食品',scenario,day:1,money:D.scenarios[scenario].money,rp:0,reputation:5,companyXP:0,levelClaimed:1,facilities:{farm:1,workshop:1,warehouse:1,lab:1},research:{production:0,processing:0,quality:0,storage:0,sales:0,recipe:0},lots:[],used:{produce:0,craft:0,accept:0,analysis:0},staff:[makeStaff('minori')],recruitment:{rng:hash(String(seed)+'|hiring'),round:0,lastDay:0,candidates:[],history:[],lastCampaign:null},dining:{active:null,album:[]},finance:{aidDay:0,reliefUntil:0,autoWork:false,target:1200,soldDay:1,sold:0},candidates:[],orders:[],customers:{},cancels:{},guarantees:{},mastery:{},standardized:{},catalog:{},records:{},materialXP:{},materialRanks:{},supplierLevel:0,regions:['town'],region:'town',regionStats:{},developed:{},policy:'standard',recipes:[],signature:null,discoveries:{},auto:{},wholesale:{},dailyCrop:'wheat',dailyTarget:6,workPlan:{enabled:false,orders:true,deliver:true,targetItem:'bread',target:0,budget:1200,keepCraft:1,policy:'standard'},workPlanUsage:{day:1,spent:0},harvestProgress:{day:1,items:{}},investments:{brand:0,ads:0,quality:0,vip:0,patent:0},contestEntries:[],contestHistory:[],rivalWins:{},rivalCooldowns:{},timeline:[],reports:[],titles:[],stats:{sales:0,profit:0,delivered:0,failed:0,waste:0,crafted:0,highQuality:0,highDeliveries:0,originalDeliveries:0,wholesale:0},settings:{bgm:0,sfx:35,reduced:false,short:false},trendIndex:0,event:null,nextBuff:null,buff:null,ended:false,endless:false,initialEvaluation:null,reevaluations:[],historyOffers:[],legacy:null};s.ledger=dayLedger(s);addLot(s,'wheat',8,0,0,12);addLot(s,'vegetable',4,0,0,15);s.staff.forEach(t=>t.usedDay=0);s.candidates=[order(s,'bread',3,0,'sakura'),order(s,'salad',2,0,'rikuto'),order(s,'wheat',6,0,'sakura')];log(s,'小さな会社、はじまる','まずはパン3個を作って、さくらさんに届けよう。','milestone');return s}
function contractBonus(s,i,customer){const tags=i.tags||[];return Math.min(.9,s.research.sales*.04+(tags.includes(season(s).tag)?.08:0)+(tags.includes(trend(s).tag)?.1:0)+D.regions[s.region].tags.filter(t=>tags.includes(t)).length*.07+(s.investments.brand&&i.price>=800?Math.min(.18,s.investments.brand*.06):0)+(s.rivalWins.local&&s.region==='town'?.05:0)+(s.rivalWins.luxury&&i.price>=800?.05:0)+(s.investments.patent&&i.original?.12:0)+Math.min(.12,(s.customers[customer]?.delivered||0)*.01+Math.max(0,(s.customers[customer]?.legacyLevel||1)-1)*.03))}
function quoteReward(s,o){const bonus=s.buff?.kind==='delivery'?0:Math.min(.2,power(s,'sales')*.003+(special(s,'sales','local')&&o.region==='town'?.05:0));return Math.round(o.reward*(1+bonus))}
function order(s,id,n,q,customerId,extra={}){const i=item(s,id),c=D.customers.find(x=>x.id===customerId)||D.customers[0],reward=Math.round(i.price*n*(1+contractBonus(s,i,c.id)+q*.12));return {id:uid(s,'order'),title:c.use,customer:c.id,itemId:id,quantity:n,minQuality:q,duration:q>=3?5:3,reward,rep:2+q,loss:4+q*2,region:s.region,recipeVersion:i.recipeVersion||0,guarantee:q>=4?4:q>=3?3:q>=2?2:0,...extra}}
function generateCandidates(s){const customers=D.customers.filter(c=>s.regions.includes(c.region)&&(c.region===s.region||s.adsUntil>=s.day));const legal=Object.keys(D.items).filter(id=>unlocked(s,id)&&D.items[id].kind==='food');if(s.signature&&item(s,s.signature)?.formal)legal.push(s.signature);if(s.adsUntil>=s.day){const themed=legal.filter(id=>item(s,id).tags.some(t=>D.regions[s.region].tags.includes(t)));legal.push(...themed)}const basics=['bread','salad','wheat','vegetable'];const first=pick(s,basics);const a=[order(s,first,first==='wheat'||first==='vegetable'?4:2,0,pick(s,customers).id)];let choices=legal.filter(id=>!s.historyOffers.slice(-4).includes(id));if(choices.length<2)choices=legal;for(let j=1;j<3;j++){const id=pick(s,choices),customer=pick(s,customers);const relation=(s.customers[customer.id]?.delivered||0)+(s.customers[customer.id]?.legacyLevel>=4?6:s.customers[customer.id]?.legacyLevel>=3?3:0);const q=j===2&&s.day>=6?Math.min(4,Math.floor(s.research.quality/2)+1+(relation>=6?1:0)):Math.min(1,Math.floor(s.research.quality/3));a.push(order(s,id,2+(j===1&&s.research.processing>0?1:0),q,customer.id,{challenge:q>0,prefix:relation>=6?'指名':''}));s.historyOffers.push(id)}s.historyOffers=s.historyOffers.slice(-30);s.candidates=a}
function planning(s,o){const requirements=o.requirements||[{itemId:o.itemId,quantity:o.quantity}];const p={ok:requirements.every(r=>planTake(s,r.itemId,r.quantity,o.minQuality,o.id).ok)};if(p.ok)return {label:'現在の在庫で納品可能',ready:true,steps:[],crafts:0,produces:0,cost:0};const stock={};for(const l of s.lots)if(!l.locked&&(!l.reservation||l.reservation===o.id)&&l.expiresAfterDay>=s.day)stock[l.itemId]=(stock[l.itemId]||0)+l.quantity;const steps=[];let crafts=0,produces=0,cost=0;function need(id,n,top=false,depth=0){if(depth>12)throw Error('レシピ循環');const have=top?qty(s,id,o.minQuality,o.id):stock[id]||0,use=Math.min(n,have);stock[id]=Math.max(0,(stock[id]||0)-use);n-=use;if(n<=0)return;const i=item(s,id);if(!i)return; if(i.recipe){for(const [k,v]of Object.entries(i.recipe))need(k,n*v,false,depth+1);crafts+=Math.ceil(n/batch(s));cost+=(i.fee||0)*n;steps.push({id,n,type:'craft'})}else if(i.farm){produces+=Math.ceil(n/produceBatch(s));cost+=i.cost*n;steps.push({id,n,type:'produce'})}else{cost+=Math.ceil(n/supplyUnit(s))*supplyUnit(s)*i.cost;steps.push({id,n,type:'buy',locked:!unlocked(s,id)})}}
requirements.forEach(r=>need(r.itemId,r.quantity,true));let label=steps.some(x=>x.locked)?'現在は素材入手不可':qty(s,o.itemId,0,o.id)>=o.quantity?'品質改善が必要':o.minQuality>0?'製造と品質条件の確認が必要':'追加製造で可能';return {label,ready:false,steps,crafts,produces,cost,estimated:true}}
function productionRank(s,id){return clamp(s.materialRanks[id]||0,0,6)}
function growMaterial(s,id,n){s.materialXP[id]=(s.materialXP[id]||0)+n;let rank=productionRank(s,id);while(rank<6&&s.materialXP[id]>=12+rank*10){s.materialXP[id]-=12+rank*10;rank++;s.materialRanks[id]=rank;log(s,item(s,id).name+'の生産技術 '+D.ranks[rank],'今後の入庫素材が成長。以前の在庫はそのまま。','growth')}}
function nextContest(s,key){const pending=s.contestEntries.find(e=>e.key===key&&e.day>=s.day);if(pending)return pending.day;const c=D.contests[key];let d=c.first;while(d<s.day||s.contestHistory.some(h=>h.key===key&&h.day===d))d=d<60?60+c.first:d+c.period;return d}
function contestScore(s,key,lot){const c=D.contests[key],i=item(s,lot.itemId),qualityScore=lot.qualityRank*10,fit=i.tags.includes(c.tag)?20:5,craftsmanship=Math.min(15,(s.mastery[lot.itemId]||0)/2),original=i.original&&i.formal?8:0;return {qualityScore,fit,craftsmanship,original,base:20+qualityScore+fit+craftsmanship+original}}
function rivalPreview(s,key,lot){const r=D.rivals[key],i=item(s,lot.itemId),fit=i.tags.includes(r.tag)?15:0,score=lot.qualityRank*10+fit+Math.min(10,(s.mastery[lot.itemId]||0)/4)+10;return {score,chance:clamp(.5+(score-r.threshold)/30,.05,.95),fit}}
function evaluation(s){const wins=s.contestHistory.filter(h=>h.score>=55).length,relations=Object.values(s.customers).filter(c=>c.delivered>=6).length,axes={利益:clamp(s.stats.profit/800,0,100),信用:clamp(s.reputation,0,100),品質:clamp((Math.max(0,...Object.values(s.records)))*16,0,100),顧客:clamp(relations*25,0,100),人材:clamp(sum(s.staff.map(t=>t.level-1))*8,0,100),開発:clamp(s.recipes.filter(r=>r.formal).length*45+Object.keys(s.developed).length*12,0,100),地域:clamp((s.regions.length-1)*20,0,100)};let ending='のんびり工房';if(s.stats.delivered>=15)ending='地元密着';if(s.research.quality>=4)ending='職人企業';if(s.recipes.some(r=>r.formal))ending='研究開発';if((s.stats.highDeliveries||0)>=12)ending='高級ブランド';if(s.regions.length>=5)ending='全国チェーン';if(s.regions.includes('overseas')&&(s.regionStats.overseas||0)>=8)ending='世界進出';if(Object.keys(s.rivalWins).length>=4)ending='業界制覇';if(wins>=3&&s.stats.highQuality>=20&&relations>=3)ending='ごちそう王';const route=Object.entries(axes).sort((a,b)=>b[1]-a[1])[0][0];const repStaff=[...s.staff].sort((a,b)=>sum(Object.values(b.products))-sum(Object.values(a.products)))[0];const customer=Object.entries(s.customers).sort((a,b)=>b[1].delivered-a[1].delivered)[0];const scenarioSuccess=s.scenario==='small'?s.stats.waste<=10&&s.stats.delivered>=20:s.scenario==='luxury'?s.stats.highQuality>=10:s.scenario==='local'?relations>=2:s.scenario==='team'?s.contestHistory.some(h=>h.key==='nationalFeast'&&h.score>=55):true;return {day:s.day,ending,axes,strongest:route,titles:clone(s.titles),product:s.signature?item(s,s.signature).name:Object.entries(s.mastery).sort((a,b)=>b[1]-a[1])[0]?.[0]||'これからの一皿',staff:repStaff?.name||'あなた',customer:customer?.[0]||null,scenarioSuccess,stats:clone(s.stats),turns:s.timeline.filter(t=>t.type==='milestone'||t.type==='award').slice(0,8)}}
function achievements(s){const tests={'資金繰りの達人':s.stats.profit>=30000,'ブランド育成家':s.investments.brand>=2&&s.stats.highQuality>=10,'品質職人':Object.values(s.records).some(q=>q>=5),'品評会の覇者':s.contestHistory.some(h=>h.key==='nationalFeast'&&h.score>=90),'商品開発者':s.recipes.some(r=>r.formal),'地域展開の鬼':s.regions.length>=4,'ライバルハンター':Object.keys(s.rivalWins).length>=4,'人材育成家':s.staff.some(t=>t.level>=5),'図鑑収集家':Object.keys(s.catalog).length>=15,'海外開拓者':s.regions.includes('overseas')};for(const [k,v]of Object.entries(tests))if(v&&!s.titles.includes(k)){s.titles.push(k);log(s,'称号「'+k+'」','会社の歩みに刻まれました。','milestone')}}
function validate(s){check(s&&typeof s==='object'&&!Array.isArray(s),'保存形式が違います');check(typeof s.runId==='string'&&/^[A-Za-z0-9:._-]{1,140}$/.test(s.runId)&&!['__proto__','prototype','constructor'].includes(s.runId),'会社IDが不正です');check(s.saveSchemaVersion===D.schema,'対応していないセーブ版です');integer(s.day,1,100000);integer(s.transactionSeq,0,1e9);integer(s.rng,0,4294967295);integer(s.money,0,1e12);integer(s.rp,0,1e12);integer(s.companyXP,0,1e12);integer(s.reputation,0,1e12);check(s.gameRulesVersion===D.rules,'対応していないゲームルール版です');check(D.scenarios[s.scenario]&&D.regions[s.region],'地域またはシナリオが不正です');check(typeof s.name==='string'&&s.name.length<=100,'会社名が長すぎます');check(Array.isArray(s.lots)&&s.lots.length<=30000,'在庫データが大きすぎます');const ids=new Set;for(const l of s.lots){check(!ids.has(l.lotId),'ロットIDが重複しています');ids.add(l.lotId);check(item(s,l.itemId),'不明な商品があります');integer(l.quantity,1,1e7);integer(l.qualityRank,0,6);check(Number.isFinite(l.materialPotential)&&l.materialPotential>=0&&l.materialPotential<=6,'素材潜在力が不正です');check(Number.isFinite(l.unitCost)&&l.unitCost>=0,'原価が不正です');integer(l.madeDay,1,100000);integer(l.expiresAfterDay,1,1000000);integer(l.reworkCount,0,100);check(l.expiresAfterDay>=l.madeDay,'期限が不正です')}
for(const field of ['materialXP','materialRanks','guarantees','mastery','standardized','investments','wholesale','regionStats','rivalCooldowns','catalog','records']){check(s[field]&&typeof s[field]==='object'&&!Array.isArray(s[field]),'数値設定が不正です：'+field);for(const value of Object.values(s[field]))integer(value,0,['materialRanks','guarantees','catalog','records'].includes(field)?6:1e9)}check(D.policies[s.policy]&&Object.keys(D.policies).includes(s.policy),'製造方針が不正です');integer(s.supplierLevel,0,6);integer(s.idSeq,0,1e9);for(const a of Object.values(s.auto)){integer(a.level,1,10000);integer(a.target,0,999);integer(a.budget,0,100000);integer(a.minQuality,0,6);check(typeof a.enabled==='boolean','設備設定が不正です')}integer(s.settings.bgm,0,100);integer(s.settings.sfx,0,100);for(const k of Object.keys(D.research))integer(s.research[k],0,10000);for(const k of Object.keys(D.facilities))integer(s.facilities[k],1,10000);for(const v of Object.values(s.used))integer(v,0,1e6);check(s.orders.length<500&&s.staff.length<=500&&s.recipes.length<=1000,'保存件数が多すぎます');for(const o of [...s.orders,...s.candidates]){check(D.customers.some(c=>c.id===o.customer),'注文の顧客が不明です');check(typeof o.id==='string'&&o.id.length<140,'注文IDが不正です');integer(o.quantity,1,1e7);integer(o.minQuality,0,6);integer(o.reward,0,1e12);check(item(s,o.itemId),'注文の商品が不明です');if(o.dueDay)integer(o.dueDay,1,1000000);integer(o.duration,1,1000);integer(o.rep,0,100000);integer(o.loss,0,100000);if(o.requirements){check(Array.isArray(o.requirements)&&o.requirements.length<=30,'注文の内訳が不正です');for(const r of o.requirements){check(item(s,r.itemId),'注文の素材が不明です');integer(r.quantity,1,1e7)}}}for(const t of s.staff){check(Object.keys(D.roles).includes(t.assigned)&&(!t.nextAssignment||Object.keys(D.roles).includes(t.nextAssignment)),'スタッフ配置が不正です');integer(t.level,1,10000);integer(t.exp,0,1e9);for(const v of Object.values(t.stats))integer(v,0,10000)}for(const r of s.recipes){check(typeof r.name==='string'&&r.name.length<=100&&r.recipe&&Object.keys(r.recipe).length>0,'レシピが不正です');standardCost(s,r.id)}
function walk(x,d=0){check(d<40,'データの階層が深すぎます');if(typeof x==='number')check(Number.isFinite(x),'有限でない数値があります');else if(x&&typeof x==='object')for(const [k,v]of Object.entries(x)){check(!['__proto__','constructor','prototype'].includes(k),'安全でないキーがあります');walk(v,d+1)}}walk(s);return true}
function transact(state,type,payload={},token=state.transactionSeq+1){try{check(token===state.transactionSeq+1,'この操作はすでに処理済みか、古い画面の操作です');check(E.actions[type],'未定義の操作です');check(!state.ended||['continue','settings','rename'].includes(type),'営業の評価が完了しました。継続を選んでください');const s=clone(state);E.actions[type](s,payload);s.transactionSeq++;s.lastTx={id:s.runId+':'+s.transactionSeq,type,dayBefore:state.day,dayAfter:s.day};achievements(s);validate(s);return {ok:true,state:s}}catch(e){return {ok:false,error:e.message,state}}}
Object.assign(E,{F,clone,clamp,sum,check,integer,hash,rand,pick,uid,log,item,unlocked,level,season,trend,staff,power,special,useStaff,capacity,productionLimit,craftLimit,batch,produceBatch,supplyUnit,supplyRank,shelf,qty,total,addLot,planTake,consume,quality,craftPlan,manufacture,standardCost,makeStaff,dayLedger,newGame,order,quoteReward,generateCandidates,planning,productionRank,growMaterial,nextContest,contestScore,rivalPreview,evaluation,validate,transact});root.GCEngine=E;if(typeof module!=='undefined')module.exports=E;
})(typeof globalThis!=='undefined'?globalThis:this);
