/* Recovery paths use no real time, debt or staff loss. */
(function(root){'use strict';const E=root.GCEngine,{D,check,integer,clone}=E,A=E.actions;
function operatingCost(s){return s.finance.aidDay&&s.day<=s.finance.reliefUntil?0:20+s.staff.length*10}
function aidPreview(s){const f=s.finance,nextDay=f.aidDay?f.aidDay+D.finance.aidInterval:s.day;return {ok:!s.ended&&s.money<=D.finance.aidThreshold&&s.day>=nextDay,nextDay,amount:D.finance.aid,reason:s.ended?'継続経営を選んでください':s.money>D.finance.aidThreshold?'手元資金500円以下で利用できます':s.day<nextDay?nextDay+'日目から再び相談できます':''}}
A.recoveryAid=s=>{const p=aidPreview(s);check(p.ok,p.reason);s.finance.aidDay=s.day;s.finance.reliefUntil=s.day+D.finance.reliefDays-1;s.money+=p.amount;s.ledger.otherIncome+=p.amount;E.log(s,'協同組合の再建支援',p.amount+'円を受領。'+s.finance.reliefUntil+'日目まで日次費用を免除。返済は不要です。','milestone');s.lastResult={title:'もう一度、おいしいを届けよう',text:'支援金1,000円 / '+s.finance.reliefUntil+'日目まで日次費用0円。借金やスタッフの離脱はありません。',kind:'support'}};
A.contractWork=(s,p={})=>{const n=p.n??1;integer(n,1,10000);check(n<=E.craftLimit(s)-s.used.craft,'必要な加工枠が残っていません');s.used.craft+=n;const income=D.finance.workPay*n;s.money+=income;s.ledger.otherIncome+=income;s.ledger.contractIncome=(s.ledger.contractIncome||0)+income;E.useStaff(s,'workshop',n);s.lastResult={title:'地域のお手伝い、完了',text:'加工'+n+'枠 → '+income+'円。材料・先払いは不要です。',kind:'cash'}};
function stockSalePreview(s,id,n){try{const l=s.lots.find(l=>l.lotId===id);check(l&&!l.locked&&!l.reservation,'予約・保護されていない在庫を選んでください');check(l.expiresAfterDay>=s.day,'期限切れの在庫は買い取れません');integer(n,1,l.quantity);const used=s.finance.soldDay===s.day?s.finance.sold:0;check(n<=D.finance.saleLimit-used,'在庫買取は1日10個までです');const unit=Math.floor(Math.min(E.item(s,l.itemId).price*.25,l.unitCost*.65));check(unit>0,'この在庫には買取価格が付きません');return {ok:true,unit,income:unit*n,cost:l.unitCost*n,n,id}}catch(e){return {ok:false,reason:e.message}}}
A.stockSale=(s,p)=>{const q=stockSalePreview(s,p.id,p.n);check(q.ok,q.reason);const lot=s.lots.find(l=>l.lotId===p.id),cost=E.consume(s,[{...lot,amount:p.n}]);if(s.finance.soldDay!==s.day){s.finance.soldDay=s.day;s.finance.sold=0}s.finance.sold+=p.n;s.money+=q.income;s.stats.sales+=q.income;s.ledger.sales+=q.income;s.ledger.cogs+=cost;s.lastResult={title:'余剰在庫を買い取ってもらいました',text:E.item(s,lot.itemId).name+' ×'+p.n+' / 受取 '+q.income+'円。通常の注文より安い買取です。',kind:'cash'}};
A.financeConfig=(s,p)=>{check(typeof p.autoWork==='boolean','受託の設定が不正です');const target=p.target??s.finance.target;integer(target,500,3000);s.finance.autoWork=p.autoWork;s.finance.target=target;s.lastResult={title:p.autoWork?'不足分のお手伝いをスタッフへ':'自動の受託作業を停止',text:'閉店時、注文の仕事の後に余った加工枠で補います。試作用に残す枠は使いません。',kind:'note'}};
function runFinanceWork(s){const f=s.finance,keep=s.workPlan.enabled?s.workPlan.keepCraft:0,frames=Math.max(0,E.craftLimit(s)-s.used.craft-keep),need=Math.max(0,f.target+operatingCost(s)-s.money),n=f.autoWork?Math.min(frames,Math.ceil(need/D.finance.workPay)):0;if(n)A.contractWork(s,{n});return {enabled:f.autoWork,frames:n,income:n*D.finance.workPay,reason:!f.autoWork?'停止中':!need?'目標の手元資金に届いています':!frames?'使える加工枠がありません（試作用の確保を含む）':n*D.finance.workPay<need?'残りは次の営業日に補います':'お手伝いで資金を補います'}}
function cashStatus(s){const f=s.finance,expense=operatingCost(s),remaining=Math.max(0,E.craftLimit(s)-s.used.craft);return {expense,normalExpense:20+s.staff.length*10,remaining,workIncome:remaining*D.finance.workPay,low:s.money<Math.max(1200,expense*3),aid:aidPreview(s),saleRemaining:Math.max(0,D.finance.saleLimit-(f.soldDay===s.day?f.sold:0))}}
const baseValidate=E.validate;E.validate=s=>{baseValidate(s);const f=s.finance;check(f&&typeof f.autoWork==='boolean','資金繰り設定が不正です');integer(f.aidDay,0,s.day);integer(f.reliefUntil,0,1000000);integer(f.target,500,3000);integer(f.soldDay,1,s.day);integer(f.sold,0,D.finance.saleLimit);check((!f.aidDay&&f.reliefUntil===0)||(f.aidDay&&f.reliefUntil===f.aidDay+D.finance.reliefDays-1),'支援期間の記録が不正です');return true};
Object.assign(E,{operatingCost,aidPreview,stockSalePreview,runFinanceWork,cashStatus});
})(typeof globalThis!=='undefined'?globalThis:this);
