/* Order guidance is read-only. Only real available lots support exact quality odds. */
(function(root){'use strict';
const E=root.GCEngine||(typeof require!=='undefined'?require('./engine.js'):null),{D,item,clone}=E;
const link=(title,text,label,action,p={},kind='prepare')=>({title,text,label,action,p,kind});
function researchGuide(s,id,target){const d=D.research[id],cost=d.base*(s.research[id]+1);return link(d.name+'をLv'+target+'へ',d.name+'は現在Lv'+s.research[id]+'。次の1段階は研究P'+cost+'（手元'+s.rp+'P）。'+(s.rp<cost?'不足分は営業終了時の研究で増えます。':''),d.name+'の条件を見る','guideResearch',{id},'unlock')}
function unlockGuide(s,id){const d=item(s,id);if(E.unlocked(s,id))return null;if(d.rare)return researchGuide(s,'recipe',2);if(s.research.recipe<(d.unlock||0)&&!(d.qualityUnlock&&s.research.quality>=d.qualityUnlock))return researchGuide(s,'recipe',d.unlock);return link(d.name+'を商品開発で解放','開発費'+d.devCost+'円・研究P'+(20+d.unlock*10)+'。'+D.regions[d.region].short+'へ進出、または会社Lv'+(d.unlock+2)+'が必要です。','商品の開発へ','go',{to:'make/original'},'unlock')}
function costGuide(s,reason){if(/資金|加工費|費用/.test(reason))return link('先に製造資金を用意する',reason+'。材料不要の受託作業で資金を増やせます。','資金繰りへ','go',{to:'trade/finance'},'money');if(/倉庫|超過/.test(reason))return link('先に倉庫の空きを作る',reason+'。納品か在庫の売却、倉庫拡張を選べます。','在庫と売却を見る','go',{to:'trade/finance'},'capacity');if(/加工枠|生産枠/.test(reason))return link('今日の'+(/生産/.test(reason)?'生産':'加工')+'枠を使い切りました','今日進めたい場合は設備強化で枠を増やせます。明日に回す場合は納期を確認してください。','設備と増える枠を見る','go',{to:'grow/facilities'},'frames');return link('この準備から進めよう',reason,'製造画面へ','go',{to:'make/craft'});}
function materialGuide(s,id,cap,required,potential){const d=item(s,id);return link('今回の最高は'+D.ranks[cap]+'、要求は'+D.ranks[required], '実際に使う材料の潜在力は'+potential.toFixed(2)+'。要求品質には加重平均'+(required-2)+'以上が必要です。品質研究だけでは素材上限は上がりません。','使う素材の改善方法','guideMaterials',{id,required},'cap')}
function qualityGuide(s,id,n,q,required,reservation){const d=item(s,id),chance=q.probabilities.slice(required).reduce((a,b)=>a+b,0);if(q.cap<required)return materialGuide(s,id,q.cap,required,q.potential);if(chance<1-1e-10){const standard=s.standardized[id]||0,next=Math.min(4,standard+2),canStandard=standard<3&&required<=4;return {...link(d.name+' '+D.ranks[required]+'以上は '+(chance*100).toFixed(1)+'%', '現在の材料・'+D.policies[s.policy].name+'・'+n+'個を1バッチで製造する場合。安定'+D.ranks[q.floor]+'／最高'+D.ranks[q.cap]+'。おまかせは品質を保証できないため停止します。',canStandard?'安定製造にする条件を見る':'品質の確率を見て製造',''+(canStandard?'guideStandard':'guidePrepare'),canStandard?{id,required}:{id,n,rank:required,reservation},'chance'),chance,alternative:{label:'確率を見て製造する',action:'guidePrepare',p:{id,n,rank:required,reservation}}};}return link('次は'+d.name+'を'+n+'個加工', 'このバッチは'+D.ranks[q.floor]+'以上を保証。今回の最高は'+D.ranks[q.cap]+'です。','製造する個数を確認','guidePrepare',{id,n,rank:required,reservation});}
function orderGuidance(s,o){const active=s.orders.some(x=>x.id===o.id),reservation=active?o.id:null,plan=E.planning(s,o),acceptBlock=!active?(s.used.accept>=E.acceptLimit(s)?'今日は新規受注'+E.acceptLimit(s)+'件の上限です。明日の候補から選べます。':s.orders.length>=2+Math.floor(s.research.sales/2)?'受注枠が満杯です。受注中の注文を納品すると空きます。':''):'';
 let next;
 function need(id,n,min=0,path=[]){const d=item(s,id);if(path.includes(id)||path.length>12)return link('このレシピは個別確認が必要です','循環または入手経路を確認してください。','レシピ帳へ','go',{to:'make/original'});
  const have=E.qty(s,id,min,reservation),missing=n-have;if(missing<=0)return null;
  const un=unlockGuide(s,id);if(un)return un;
  const hidden=s.lots.find(l=>l.itemId===id&&l.qualityRank>=min&&l.expiresAfterDay>=s.day&&(l.locked||l.reservation&&l.reservation!==reservation));
  if(hidden&&E.qty(s,id,0,reservation)===0)return link(d.name+'が保護・別注文用になっています','保護品は勝手に使いません。必要なら在庫画面で対象の保護・予約を解除してください。','該当する在庫を見る','guideInventory',{id},'reserved');
  if(min>0&&d.recipe){const l=s.lots.find(l=>l.itemId===id&&l.expiresAfterDay>=s.day&&!l.locked&&!l.reservation&&l.reworkCount===0&&l.qualityRank===min-1&&Math.floor(l.materialPotential+1e-8)+2>=min);if(l){const amount=Math.min(missing,l.quantity,E.batch(s)),rp=[50,50,50,70,100,150][l.qualityRank]*amount;return link(d.name+' '+amount+'個を'+D.ranks[min]+'に改善', '在庫'+D.ranks[l.qualityRank]+'を1段階上げれば条件に届きます。研究P'+rp+'・加工1枠（手元'+s.rp+'P／加工残り'+Math.max(0,E.craftLimit(s)-s.used.craft)+'枠）。期限は延びません。','この在庫を品質改善','guideImprove',{id:l.lotId,n:amount},'improve')}}
  if(d.recipe){const batch=Math.max(1,E.batch(s)-(s.buff?.kind==='repair'?1:0)),count=Math.min(missing,batch);for(const [k,v] of Object.entries(d.recipe)){const child=need(k,v*count,0,[...path,id]);if(child)return {...child,forItem:id,forQuantity:count};}const p=E.craftPlan(s,id,count,{reservation});if(!p.ok)return costGuide(s,p.reason);return qualityGuide(s,id,count,p.q,min,reservation);}
  if(d.farm){const q=E.productionRank(s,id);if(q<min)return link(d.name+'の生産技術を'+D.ranks[min]+'へ','現在'+D.ranks[q]+'。次の段階まで素材経験'+(12+q*10-(s.materialXP[id]||0))+'。収穫量で育つため、余剰を作りすぎず日常注文と並行して進めましょう。','畑の育成と収穫を見る','go',{to:'make/produce'},'cap');const count=Math.min(missing,E.produceBatch(s)),copy=clone(s);try{E.actions.produce(copy,{id,n:count})}catch(e){return costGuide(s,e.message)}return link('まず'+d.name+'を'+count+'個収穫', '次の工程にあと'+missing+'個必要。今回'+count+'個・'+count*d.cost+'円・生産1枠。','必要な個数を収穫','guidePrepare',{id,n:count,rank:min,reservation});}
  if(d.buy){if(E.supplyRank(s,id)<min)return link(d.name+'の仕入れ品質を上げる','現在'+D.ranks[E.supplyRank(s,id)]+'、要求'+D.ranks[min]+'。契約改善後の新しい入荷から品質が変わります。','仕入れ契約を改善','supplierSheet',{},'cap');const count=Math.ceil(missing/E.supplyUnit(s))*E.supplyUnit(s),copy=clone(s);try{E.actions.buy(copy,{id,n:count})}catch(e){return costGuide(s,e.message)}return link('まず'+d.name+'を'+count+'個仕入れる','次の工程にあと'+missing+'個必要。'+E.supplyUnit(s)+'個単位のため購入'+count+'個・'+(s.money-copy.money)+'円です。','必要な数量で仕入れ','guidePrepare',{id,n:count,rank:min,reservation});}
  return link(d.name+'の入手先がありません','旧データの商品など、現在の生産方法がない商品です。受注済みなら期限相談も検討してください。','契約の準備を読む','planSheet',{id:o.id},'unavailable');
 }
 if(plan.ready)next=link('必要な品質・数量がそろっています','追加製造は不要です。'+(active?'今すぐ納品できます。':'受注後に納品できます。'),active?'この注文を納品する':'契約内容を見る',active?'do':'acceptSheet',active?{type:'deliver',p:{id:o.id}}:{id:o.id},'ready');
 else for(const r of o.requirements||[{itemId:o.itemId,quantity:o.quantity}]){next=need(r.itemId,r.quantity,o.minQuality);if(next)break;}
 const qualityNote=!plan.ready&&o.minQuality>0&&!['chance','cap','improve'].includes(next?.kind)?'要求は'+D.ranks[o.minQuality]+'以上。材料がそろうと、実際の品質確率が表示されます。現時点では成功を保証しません。':'';
 if(acceptBlock&&next?.action==='acceptSheet'){next={...next,label:s.used.accept>=E.acceptLimit(s)?'今日の残りと閉店予定を見る':'受注中の注文を先に仕上げる',action:s.used.accept>=E.acceptLimit(s)?'dayPreview':'activeOrders',p:{}};}
 return {plan,active,acceptBlock,next,qualityNote};
}
Object.assign(E,{orderGuidance,unlockGuide});
})(typeof globalThis!=='undefined'?globalThis:this);
