/* Guided first delivery, bounded delivery growth and persistent town invitations. */
(function(root){'use strict';
const E=root.GCEngine||(typeof require!=='undefined'?require('./engine.js'):null),{D,check,integer,clone}=E,A=E.actions;
const chapters=[
 {id:'regular',day:3,who:'sakura',title:'喫茶室に、いつものパンを',body:'「週末は少し多めにお願いしたいな」。まとめて届けるか、まず製法を学ぶか。会社のペースで選ぼう。',offer:['bread',4,0],offerName:'パン4個の相談を聞く',learn:'delivery',learnName:'まずは製造量を増やす工夫',learnText:'研究P＋12。加工研究・工房の効果を比較する。'},
 {id:'picnic',day:7,who:'rikuto',title:'放課後、川辺でピクニック',body:'「練習のあと、みんなで食べたい！」。まとまった注文と、二品の献立づくり。いつもと違う届け方へ。',offer:['salad',4,0],offerName:'サラダ4個の相談を聞く',learn:'dining',learnName:'二品のピクニック献立を考える',learnText:'研究P＋12。期限のない食卓企画へ。'},
 {id:'festival',day:12,who:'sakura',title:'パン祭りまで、あと少し',body:'「工房の名前、町のみんなに覚えてほしいね」。品評会は品質・お題・熟練で評価。会社Lvだけでは決まりません。',offer:['bread',3,2],offerName:'良品パンの挑戦案件を見る',learn:'contest',learnName:'出品できるパンを確かめる',learnText:'研究P＋12。15日目のパン祭りの条件を確認。'},
 {id:'street',day:18,who:'momo',title:'商店街から届いたお便り',body:'「本屋のお客さまにも、あなたの味を」。日常の定番を育てるか、新しい地域へ準備を進めるか。',offer:['deli',4,0],offerName:'読み聞かせ会の注文を見る',learn:'region',learnName:'商店街への進出条件を確かめる',learnText:'研究P＋12。会社Lv3・評判12・資金3,500円から。'},
 {id:'busy',day:26,who:'rikuto',title:'応援席にも、ごちそうを',body:'「今度は応援に来る人の分も」。大口は何日かに分けて準備できます。個数と加工枠を比べてみよう。',offer:['bread',6,0],offerName:'パン6個の注文を見る',learn:'delivery',learnName:'一度に作れる数を見直す',learnText:'研究P＋12。量産・加工研究・受注上限を比較。'},
 {id:'signature',day:37,who:'sakura',title:'あなたの会社らしい、一皿を',body:'「この工房といえば、あの味」。品質だけでなく、食材の相性と使う場面から看板商品を考えてみよう。',offer:['premiumBread',2,2],offerName:'こだわりの差し入れ注文を見る',learn:'original',learnName:'自分だけのレシピを考える',learnText:'研究P＋12。食材の相性と配合を見ながら試作へ。'},
 {id:'memory',day:48,who:'nagi',title:'旅の記憶に残るごちそう',body:'「箱を開けたとき、この町を思い出せるように」。売上を伸ばす注文と、用途に合う二品の企画から選ぼう。',offer:['bento',4,0],offerName:'旅立ちの弁当注文を見る',learn:'dining',learnName:'町の思い出の献立を考える',learnText:'研究P＋12。食卓企画で特徴と届け方を組み合わせる。'},
 {id:'finale',day:56,who:'sakura',title:'ここまでの味を、全国へ',body:'「最初のパン、覚えていますよ」。60日目も営業できます。品評会もいつものお届けも、会社の歩みに残しましょう。',offer:['bread',4,2],offerName:'常連さんの記念日注文を見る',learn:'contest',learnName:'全国品評会の出品条件を見る',learnText:'研究P＋12。正式なオリジナルレシピが対象。'}
];
const acceptLimit=s=>Math.min(5,3+Math.floor(s.research.sales/3));
function initialProgress(s,legacy=false){return {tutorial:{enabled:!legacy,step:legacy?5:0},units:0,unitsFromDay:s.day,completeCount:!legacy||s.stats.delivered===0,seen:legacy?chapters.filter(c=>c.day<s.day).map(c=>c.id):[],lastStory:null,focus:'delivery'};}
// The source state is never changed by forecasts or advice.
function syncTutorial(s){const t=s.progress.tutorial;if(s.stats.delivered>0)t.step=Math.max(4,t.step);else if(s.orders.length||s.used.accept>0)t.step=Math.max(1,t.step);if(s.workPlan.enabled&&s.stats.delivered>0)t.step=5;}
const baseNew=E.newGame;E.newGame=(...args)=>{const s=baseNew(...args);s.progress=initialProgress(s);return s};
const baseUpgrade=E.upgrade;E.upgrade=s=>{baseUpgrade(s);if(s.gameRulesVersion==='2.3.0'){s.progress=initialProgress(s,true);if(s.ledger.deliveries>0){s.ledger.deliveredUnits=0;s.ledger.deliveredUnitsPartial=true;}s.gameRulesVersion=D.rules;s.contentVersion=D.content;E.log(s,'みのりの案内と町の便り','現在の会社を引き継ぎ。新しい納品個数は更新後から計測。案内は設定から再開できます。','milestone')}return s};
E.deliveryProgress=(s,o)=>{const n=(o.requirements||[{quantity:o.quantity}]).reduce((n,r)=>n+r.quantity,0);s.progress.units+=n;s.ledger.deliveredUnits=(s.ledger.deliveredUnits||0)+n;};
function morningEvent(s){if(s.event?.story)return s.event;const c=chapters.find(c=>s.day>=c.day&&!s.progress.seen.includes(c.id));if(c){s.progress.seen.push(c.id);return {story:c.id,arrivedDay:s.day};}return s.day%4===0?{index:Math.floor(s.day/4-1)%D.events.length}:null;}
function storyPreview(s){const c=chapters.find(c=>c.id===s.event?.story);if(!c)return null;let [id,n,q]=c.offer;const fallback=!E.unlocked(s,id);if(fallback)id=q>0?'bread':'salad';return {...c,offerName:fallback?E.item(s,id).name+'の注文で応える（未解放品の代わり）':c.offerName,itemId:id,quantity:n,minQuality:q,duration:4};}
function storyOrder(s,c){return E.order(s,c.itemId,c.quantity,c.minQuality,c.who,{duration:4,title:c.title,challenge:c.minQuality>0,storyId:c.id});}
function invitation(s){const p=storyPreview(s);if(!p)return null;const copy=clone(s),o=storyOrder(copy,p);return {...p,reward:E.quoteReward(s,o)};}
A.storyChoice=(s,p)=>{const c=invitation(s);check(c,'この便りは対応済みです');check(['offer','learn'].includes(p.choice),'対応を選んでください');if(p.choice==='offer'){s.candidates=[storyOrder(s,c),...s.candidates].slice(0,3);s.progress.focus='delivery';}else{s.rp+=12;s.progress.focus=c.learn;}s.progress.lastStory={id:c.id,choice:p.choice,day:s.day};s.event=null;E.log(s,c.title,p.choice==='offer'?'相談を注文候補へ。受注するまでは契約・期限なし。':c.learnName+' / 研究P＋12','milestone');s.lastResult={title:p.choice==='offer'?'注文候補にお便りを追加':'次の工夫が見えてきました',text:p.choice==='offer'?E.item(s,c.itemId).name+' ×'+c.quantity+' / '+D.ranks[c.minQuality]+'以上 / 受注した日から4営業日':c.learnText,kind:'story'};};
A.tutorial=(s,p)=>{check(['resume','skip','finish'].includes(p.mode),'案内設定が不明です');if(p.mode==='resume'){s.progress.tutorial={enabled:true,step:s.stats.delivered>0?4:0};syncTutorial(s);}else if(p.mode==='finish')s.progress.tutorial.step=5;else s.progress.tutorial.enabled=false;};
function nextOperation(s,o){const active=s.orders.some(x=>x.id===o.id);if(!active){const g=E.orderGuidance(s,o);if(g.acceptBlock)return g.next;return {title:E.item(s,o.itemId).name+'の注文を引き受けよう',text:'まず条件を確認。受注したら、必要な数だけ材料を用意します。',label:'注文の条件を確認する',action:'acceptSheet',p:{id:o.id}};}return E.orderGuidance(s,o).next;}
function coach(s){const t=s.progress.tutorial;if(s.ended)return {title:'会社の'+D.scenarios[s.scenario].days+'日間を振り返ろう',text:'最後の日の営業結果まで評価に含まれています。',label:'経営評価を見る',action:'evaluation',p:{}};
 if(t.enabled&&t.step<5){if(s.stats.delivered>0)return {tutorial:true,step:4,title:'繰り返しの仕込みは、任せて大丈夫',text:'納品できました！ これからは注文を選び、収穫・加工・お届けをまとめて任せられます。',label:'任せ方を選んで、案内を終える',action:'tutorialWork',p:{}};
 const o=[...s.orders].sort((a,b)=>a.dueDay-b.dueDay)[0]||s.candidates.find(o=>o.itemId==='bread'&&o.minQuality===0)||s.candidates.find(o=>o.minQuality===0);if(o){const n=nextOperation(s,o),step=!s.orders.length?0:E.planning(s,o).ready?3:E.qty(s,'flour',0,o.id)>0?2:1;return {...n,tutorial:true,step, text:(!s.orders.length?(s.day===1&&E.qty(s,'wheat')>=6?'みのり「はじめは品質Eで大丈夫。小麦はもう用意してあります」。':'みのり「まずは品質Eの案件から。必要な準備を順番に案内しますね」。'):n.text),footer:step===1?'小麦 → 小麦粉 → パン。下のボタンが必要な工程を開きます。':step===3?'製造しただけでは納品実績になりません。お届けで報酬と実績が増えます。':'注文の必要数を引き継ぐので、数え直さなくて大丈夫。'};}}
 const urgent=[...s.orders].sort((a,b)=>a.dueDay-b.dueDay)[0];if(urgent&&s.workPlan.enabled&&E.closingForecast(s).scheduledIds.includes(urgent.id))return {title:'仕込みとお届けは、チームにおまかせ',text:'この注文は閉店時にお届けできます。自分で同じ収穫を繰り返す必要はありません。次の工夫を選ぶか、閉店予定を確認しましょう。',label:'費用とお届け予定を確認する',action:'dayPreview',p:{},eyebrow:'受注したあとの進め方'};if(urgent&&urgent.dueDay<=s.day)return {...nextOperation(s,urgent),eyebrow:'今日が納期'};
 if(s.event){const c=invitation(s);return {title:c?.title||D.events[s.event.index].name,text:c?'お客さまから便りが届きました。挑戦する内容を自分で選べます。':D.events[s.event.index].body,label:c?'お便りを開いて、次の工夫を選ぶ':'相談の内容を見る',action:'eventSheet',p:{},eyebrow:'町からのお便り'};}
 if(urgent)return {...nextOperation(s,urgent),eyebrow:'受注中の仕事'};
 const offer=s.candidates.find(o=>o.storyId)||s.candidates.find(o=>E.offerPreview(s,o.id).ok);if(offer&&s.used.accept<acceptLimit(s))return {...nextOperation(s,offer),eyebrow:offer.storyId?'便りから生まれた注文':'今日のおすすめ'};
 return {title:'今日はここで、ひと区切り',text:'残り枠を使い切る必要はありません。任意の成長を選ぶか、閉店予定を確認しましょう。',label:'閉店すると進むことを見る',action:'dayPreview',p:{},eyebrow:'あなたのペースで'};
}
function contestPreparation(s,key){try{const c=D.contests[key];check(c,'大会が不明です');const day=E.nextContest(s,key);check(s.day>=Math.max(5,day-10)&&s.day<day,'大会の受付期間外です');const id=c.original?s.recipes.find(r=>r.formal)?.id:c.product||'bread';check(id,'まず正式なオリジナルレシピを完成させてください');const copy=clone(s),job={id:'contest-preparation',itemId:id,quantity:1,minQuality:0,temporary:true},r=E.workJob(copy,job,{preview:true,policy:s.policy==='trial'?'standard':s.policy});return {ok:true,id,...r};}catch(e){return {ok:false,reason:e.message}}}
A.contestPrepare=(s,p)=>{const r=contestPreparation(s,p.key);check(r.ok,r.reason);const work=E.workJob(s,{id:'contest-preparation',itemId:r.id,quantity:1,minQuality:0,temporary:true},{policy:s.policy==='trial'?'standard':s.policy});s.lastResult={title:'出品候補を1個用意しました',text:'準備費 '+work.spent+'円 / 生産'+work.produce+'・加工'+work.craft+'枠。まだ出品はしていません。',kind:'craft'};};
const focusLinks={delivery:{title:'納品をもっと増やす',label:'個数・件数の伸ばし方を見る',action:'deliveryGuide',p:{}},dining:{title:'二品でつくる、特別な食卓',label:'お客さまの企画を選ぶ',action:'diningSheet',p:{}},region:{title:'次の地域で、お客さまと出会う',label:'地域の進出条件を見る',action:'go',p:{to:'trade/regions'}},original:{title:'会社の看板商品をつくる',label:'配合と相性を見る',action:'go',p:{to:'make/original'}},contest:{title:'次の品評会に挑戦する',label:'出品条件と日程を見る',action:'go',p:{to:'more/contests'}}};
function growthOptions(s){const choices=[];if(s.research.processing<6){const copy=clone(s);copy.research.processing++;choices.push({title:'加工研究',text:'1枠 '+E.batch(s)+' → '+E.batch(copy)+'個 / 加工 '+E.craftLimit(s)+' → '+E.craftLimit(copy)+'枠',cost:D.research.processing.base*(s.research.processing+1),currency:'P',action:'researchSheet',p:{id:'processing'},affordable:s.rp>=D.research.processing.base*(s.research.processing+1)});}if(s.facilities.workshop<6){const cost=Math.round(D.facilities.workshop.base*Math.pow(1.65,s.facilities.workshop-1));choices.push({title:'工房の増築',text:'加工 '+E.craftLimit(s)+' → '+(E.craftLimit(s)+1)+'枠 / 1枠の個数は変わりません',cost,currency:'円',action:'facilitySheet',p:{id:'workshop'},affordable:s.money>=cost});}if(s.research.sales<6){const copy=clone(s);copy.research.sales++;choices.push({title:'販売研究',text:'同時受注 '+(2+Math.floor(s.research.sales/2))+' → '+(2+Math.floor(copy.research.sales/2))+'件 / 新規受注 '+acceptLimit(s)+' → '+acceptLimit(copy)+'件/日',cost:D.research.sales.base*(s.research.sales+1),currency:'P',action:'researchSheet',p:{id:'sales'},affordable:s.rp>=D.research.sales.base*(s.research.sales+1)});}return choices;}
function nextChapter(s){return chapters.find(c=>!s.progress.seen.includes(c.id))||null;}
const oldTransact=E.transact;E.transact=(state,type,p,token)=>{const r=oldTransact(state,type,p,token);if(r.ok){syncTutorial(r.state);const count=r.state.stats.delivered-state.stats.delivered,units=r.state.progress.units-state.progress.units;if(count>0&&type!=='nextDay'&&r.state.lastResult)r.state.lastResult.sub=(r.state.lastResult.sub?r.state.lastResult.sub+' / ':'')+'納品 ＋'+count+'件・'+units+'個';}return r;};
const validate=E.validate;E.validate=s=>{validate(s);const p=s.progress;check(p&&typeof p==='object','案内の記録がありません');check(typeof p.tutorial?.enabled==='boolean','案内設定が不正です');integer(p.tutorial.step,0,5);integer(p.units,0,1e12);integer(p.unitsFromDay,1,s.day);check(typeof p.completeCount==='boolean','納品集計の範囲が不正です');check(Object.hasOwn(focusLinks,p.focus),'次の目標が不正です');check(Array.isArray(p.seen)&&p.seen.length<=chapters.length&&new Set(p.seen).size===p.seen.length&&p.seen.every(id=>chapters.some(c=>c.id===id)),'便りの記録が不正です');if(s.event?.story){check(chapters.some(c=>c.id===s.event.story)&&p.seen.includes(s.event.story),'便りが不明です');integer(s.event.arrivedDay,1,s.day);}else if(s.event)integer(s.event.index,0,D.events.length-1);if(p.lastStory){check(chapters.some(c=>c.id===p.lastStory.id)&&['offer','learn'].includes(p.lastStory.choice),'便りの選択が不正です');integer(p.lastStory.day,1,s.day);}if(s.ledger.deliveredUnitsPartial!==undefined)check(typeof s.ledger.deliveredUnitsPartial==='boolean','納品個数の集計範囲が不正です');if(s.ledger.deliveredUnits!==undefined)integer(s.ledger.deliveredUnits,0,1e12);return true;};
Object.assign(E,{contestPreparation,acceptLimit,morningEvent,storyInvitation:invitation,coach,deliveryGrowth:growthOptions,nextChapter,focusLinks,chapters,initialProgress});
})(typeof globalThis!=='undefined'?globalThis:this);
