/* Applications are rolled only by a paid, atomic recruitment action. */
(function(root){'use strict';
const E=root.GCEngine,{D,check,integer,clone,uid,log,rand}=E,A=E.actions;
const names=['あかり','ひなた','ことは','つむぎ','みつき','ふうか','すず','いろは','まひろ','なつめ','あさひ','りつ','いおり','ゆず','かなた','こはる','そう','わかば','みずき','とうま'];
const surnames=['花村','森野','日向','小鳥遊','朝倉','葉山','水瀬','高梨','星野','若松','橘','白石','青野','小森','秋山','藤井','中原','佐久間','野々村','春日'];
const colors=['#cf896b','#81a48c','#b199bb','#c8a452','#759fb1','#ad8d71','#bd8198','#6da7a1'];
const hair=['#5a4437','#756048','#473f3d','#926743','#80766a'];
const skills={farm:['harvest'],workshop:['bread','batch','finish'],sales:['small','local'],lab:['study'],warehouse:['fresh']};
const voices={farm:'一緒に、畑からおいしくしましょう。',workshop:'あなたの看板の味を、育てたいです。',sales:'お客さまの声、持ち帰ってきますね。',lab:'試して分かったことを、次の一皿へ。',warehouse:'大切な素材を、最後まで生かしましょう。'};
const choose=(r,a)=>a[Math.floor(rand(r)*a.length)];
function staffLimit(s){return s.scenario==='team'?2:16}
function recruitmentOdds(key,index=0){const c=D.recruitment[key];check(c,'募集方法が不明です');const weights=c.odds.map((v,i)=>index===0&&i<c.guarantee?0:v),sum=weights.reduce((a,b)=>a+b,0);return weights.map(v=>v/sum)}
function rarityAt(q,probabilities){let c=0;for(let i=0;i<probabilities.length;i++){c+=probabilities[i];if(q<c)return i}return probabilities.length-1}
function recruitPreview(s,key,focus='any'){try{check(Object.hasOwn(D.recruitment,key),'募集方法が不明です');check(focus==='any'||Object.hasOwn(D.roles,focus),'募集職種が不明です');const d=D.recruitment[key];check(!s.ended,'継続経営を選んでください');check(s.recruitment.lastDay!==s.day,'求人募集は1営業日1回です');check(s.staff.length<staffLimit(s),'在籍人数の上限です。今いる仲間を育てましょう');check(s.money>=d.cost,'募集費が足りません。資金繰りから立て直せます');return {ok:true,cost:d.cost,count:d.count,cashAfter:s.money-d.cost,replaces:s.recruitment.candidates.length}}catch(e){return {ok:false,reason:e.message}}}
function generatedStaff(s,role,rarity){const r=s.recruitment,primary=D.roles[role].stat,statKeys=Object.values(D.roles).map(x=>x.stat),stats=Object.fromEntries(statKeys.map(k=>[k,1+Math.floor(rand(r)*5)]));stats[primary]=7+rarity*3+Math.floor(rand(r)*5);const second=choose(r,statKeys.filter(k=>k!==primary));stats[second]=4+Math.floor(rand(r)*6);const special=choose(r,skills[role]);let name='';for(let attempt=0;attempt<500;attempt++){name=choose(r,surnames)+' '+choose(r,names);if(![...s.staff,...r.candidates].some(t=>t.name===name))break}if([...s.staff,...r.candidates].some(t=>t.name===name))name+=' '+(s.idSeq+1);
return {id:uid(s,'talent'),name,assigned:role,homeRole:role,nextAssignment:null,usedDay:0,level:1,exp:0,stats,special,spec:null,rarity:D.staffRarities[rarity],rarityIndex:rarity,trait:D.staffSkills[special].name,products:{},history:[],color:choose(r,colors),appearance:{hair:choose(r,hair),glasses:rand(r)<.3,style:Math.floor(rand(r)*3)},line:voices[role],recruitmentRound:r.round,appliedDay:s.day};}
A.recruit=(s,p)=>{const pre=recruitPreview(s,p.campaign,p.focus||'any');check(pre.ok,pre.reason);const r=s.recruitment,c=D.recruitment[p.campaign];s.money-=pre.cost;s.ledger.cashOut+=pre.cost;s.ledger.investment+=pre.cost;r.round++;r.lastDay=s.day;r.lastCampaign=p.campaign;r.candidates=[];for(let i=0;i<c.count;i++){const rarity=rarityAt(rand(r),recruitmentOdds(p.campaign,i)),role=p.focus&&p.focus!=='any'?p.focus:choose(r,Object.keys(D.roles));r.candidates.push(generatedStaff(s,role,rarity))}r.history.unshift({day:s.day,campaign:p.campaign,cost:c.cost,count:c.count,names:r.candidates.map(t=>t.name),rarities:r.candidates.map(t=>t.rarity)});r.history=r.history.slice(0,30);log(s,'求人の返事が届きました',c.name+' / '+c.count+'名の応募。候補は次の募集まで待ってくれます。','milestone');s.lastResult={title:c.count+'名から応募が届きました',text:'能力と特技を見比べて、仲間を選びましょう。採用時の追加費用はありません。',kind:'recruit'}};
A.hire=(s,p)=>{const index=s.recruitment.candidates.findIndex(t=>t.id===p.id);check(index>=0,'この応募者はいません。求人募集から仲間を探してください');check(!s.staff.some(t=>t.id===p.id),'このスタッフは採用済みです');check(s.staff.length<staffLimit(s),'在籍人数の上限です');const t=s.recruitment.candidates[index];s.recruitment.candidates.splice(index,1);t.hiredDay=s.day;t.history.push({day:s.day,text:'求人に応募し、会社の仲間になった'});s.staff.push(t);log(s,t.name+'が仲間になった',t.trait+' / '+t.line,'milestone');s.lastResult={title:t.name+'「よろしくお願いします！」',text:t.trait+' / '+D.roles[t.assigned].name+'に配属。日次費用＋10円。',kind:'growth'}};
function staffImpact(s,t){const copy=clone(s);if(!copy.staff.some(x=>x.id===t.id))copy.staff.push(clone(t));return {role:D.roles[t.assigned].name,powerBefore:E.power(s,t.assigned),powerAfter:E.power(copy,t.assigned),capacityBefore:E.capacity(s),capacityAfter:E.capacity(copy),produceBefore:E.produceBatch(s),produceAfter:E.produceBatch(copy),craftBefore:E.batch(s),craftAfter:E.batch(copy),researchBefore:4+s.facilities.lab*4+Math.floor(E.power(s,'lab')/2)+(E.special(s,'lab','study')?4:0)+(s.rivalWins.lab?3:0),researchAfter:4+s.facilities.lab*4+Math.floor(E.power(copy,'lab')/2)+(E.special(copy,'lab','study')?4:0)+(copy.rivalWins.lab?3:0)}}
const baseValidate=E.validate;E.validate=s=>{baseValidate(s);const r=s.recruitment;check(r&&Array.isArray(r.candidates)&&r.candidates.length<=6&&Array.isArray(r.history)&&r.history.length<=30,'求人データが不正です');integer(r.rng,0,4294967295);integer(r.round,0,1e9);integer(r.lastDay,0,s.day);check(r.lastCampaign===null||Object.hasOwn(D.recruitment,r.lastCampaign),'募集記録が不明です');for(const h of r.history){check(h&&Object.hasOwn(D.recruitment,h.campaign)&&Array.isArray(h.names)&&Array.isArray(h.rarities)&&h.names.length===h.count&&h.rarities.length===h.count,'募集履歴が不正です');integer(h.day,1,s.day);integer(h.cost,0,1000000);integer(h.count,2,6);for(const name of h.names)check(typeof name==='string'&&name.length<=100,'募集者名が不正です');for(const rarity of h.rarities)check(D.staffRarities.includes(rarity),'募集時のレアリティが不正です')}const ids=new Set;for(const t of [...s.staff,...r.candidates]){check(typeof t.id==='string'&&t.id.length<=140&&!ids.has(t.id),'スタッフIDが重複または不正です');ids.add(t.id);check(typeof t.name==='string'&&t.name.length<=100,'スタッフ名が不正です');for(const k of ['production','craft','sales','research','logistics'])integer(t.stats[k],0,10000);if(t.color)check(/^#[0-9a-f]{6}$/i.test(t.color),'人物色が不正です');if(t.appearance){check(/^#[0-9a-f]{6}$/i.test(t.appearance.hair),'髪色が不正です');integer(t.appearance.style,0,2);check(typeof t.appearance.glasses==='boolean','人物設定が不正です')}}for(const t of r.candidates){check(Object.hasOwn(D.roles,t.assigned)&&Object.hasOwn(D.staffSkills,t.special),'応募者の役割が不正です');integer(t.rarityIndex,0,3);check(t.rarity===D.staffRarities[t.rarityIndex],'応募者のレアリティが不正です');check(t.level===1&&t.exp===0&&t.usedDay===0&&Array.isArray(t.history)&&t.products&&typeof t.line==='string'&&t.line.length<=200,'応募者の記録が不正です');integer(t.appliedDay,1,s.day);integer(t.recruitmentRound,1,r.round)}return true};
Object.assign(E,{staffLimit,recruitmentOdds,rarityAt,recruitPreview,staffImpact});
})(typeof globalThis!=='undefined'?globalThis:this);
