'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),E=require('../actions.js'),S=require('../storage.js');
const fresh=()=>E.newGame('ADVICE-56');
function act(s,type,p={},token){const r=E.transact(s,type,p,token);assert.ok(r.ok,type+': '+r.error);return r.state}
function job(s,id='bread',n=3,q=0,due=s.day){const o={...E.order(s,id,n,q,'sakura'),dueDay:due,acceptedDay:s.day,auto:false};s.orders.push(o);return o}
test('daily advice and candidate shortcuts are pure, including repeated reads and RNG',()=>{const s=fresh(),before=JSON.stringify(s),a=E.todayStatus(s);assert.ok(a.newOffers.length);assert.ok(a.growth.length);assert.deepEqual(E.todayStatus(s),a);assert.equal(JSON.stringify(s),before);assert.ok(a.remaining.produce>0);assert.ok(a.remaining.craft>0)});
test('closing forecast removes deadline and expiry warnings when auto delivery actually consumes the stock',()=>{let s=fresh();s.lots=[];s.dailyCrop='off';const o=job(s,'bread',3);o.auto=true;E.addLot(s,'bread',3,0,0,20,{expiresAfterDay:1});const c=E.closingForecast(s);assert.ok(c.ok,c.reason);assert.deepEqual(c.scheduledIds,[o.id]);assert.equal(c.risks.filter(x=>['deadline','expiry'].includes(x.kind)).length,0);const actual=act(s,'nextDay',{day:1});assert.deepEqual(actual.lastReport,c.report);assert.equal(actual.stats.delivered,1)});
test('auto delivery enabled alone cannot hide an unfulfillable deadline',()=>{const s=fresh();s.dailyCrop='off';s.lots=[];const o=job(s,'bread',3,4);o.auto=true;E.addLot(s,'bread',3,0,0,20,{expiresAfterDay:1});const c=E.closingForecast(s);assert.ok(c.risks.some(x=>x.kind==='deadline'&&x.id===o.id));assert.ok(c.risks.some(x=>x.kind==='expiry'));assert.equal(c.scheduledIds.length,0)});
test('delegated forecast shares the actual closing transaction and shows only additional spending',()=>{let s=fresh();s.lots=[];const o=job(s);s=act(s,'workPreset',{mode:'orders'});s=act(s,'produce',{id:'wheat',n:3});const before=JSON.stringify(s),c=E.closingForecast(s);assert.deepEqual(c.scheduledIds,[o.id]);assert.equal(c.report.materialSpend+c.report.direct-s.ledger.materialSpend-s.ledger.direct,126);assert.equal(JSON.stringify(s),before);assert.deepEqual(act(s,'nextDay',{day:1}).lastReport,c.report)});
test('spare frames are not presented as executable orders when no funds or usable stock remain',()=>{const s=fresh();s.money=0;s.lots=[];s.dailyCrop='off';s.used.accept=3;const o=job(s);const a=E.todayStatus(s);assert.ok(a.remaining.produce&&a.remaining.craft);assert.equal(a.choices.length,0);assert.equal(a.newOffers.length,0);assert.equal(a.active[0].id,o.id);assert.equal(a.active[0].ok,false);assert.ok(a.close.risks.some(x=>x.kind==='deadline'))});
test('optional affordable research is still shown after all daily frames are used',()=>{const s=fresh();s.used.produce=E.productionLimit(s);s.used.craft=E.craftLimit(s);s.rp=100;const a=E.todayStatus(s);assert.equal(a.remaining.produce+a.remaining.craft,0);assert.ok(a.growth.some(g=>g.label==='研究'));assert.equal(s.rp,100)});
test('ready delivery grouping allocates shared stock once and respects reservations',()=>{let s=fresh();s.lots=[];const first=job(s,'bread',3),second=job(s,'bread',3);E.addLot(s,'bread',3);const r=E.readyDeliveries(s);assert.deepEqual(r.ids,[first.id]);s=act(s,'deliverReady');assert.equal(s.stats.delivered,1);assert.equal(s.orders[0].id,second.id);let reserved=fresh();reserved.lots=[];job(reserved,'bread',3);const target=job(reserved,'bread',3);E.addLot(reserved,'bread',3,0,0,20,{reservation:target.id});assert.deepEqual(E.readyDeliveries(reserved).ids,[target.id])});
test('single candidate action matches separate acceptance and guaranteed preparation',()=>{let s=fresh();const id=s.candidates[0].id,p=E.offerPreview(s,id);assert.ok(p.ok,p.reason);let separate=act(s,'accept',{id});separate=act(separate,'prepareOrder',{id,deliver:true});const token=s.transactionSeq+1,quick=act(s,'acceptAndDeliver',{id},token);for(const key of ['money','lots','rng','staff','orders','candidates','stats','used','companyXP','materialXP'])assert.deepEqual(quick[key],separate[key],key);assert.equal(quick.stats.delivered,1);assert.equal(E.transact(quick,'acceptAndDeliver',{id},token).ok,false)});
test('failed candidate shortcut cannot accept, spend money, consume frames or advance RNG',()=>{const s=fresh();s.used.craft=E.craftLimit(s);const before=JSON.stringify(s),r=E.transact(s,'acceptAndDeliver',{id:s.candidates[0].id});assert.equal(r.ok,false);assert.equal(JSON.stringify(s),before);assert.equal(r.state,s)});
test('preset choices expose meaningful limits and disable only the disclosed extra crop',()=>{let s=fresh();s=act(s,'workPreset',{mode:'orders'});assert.equal(E.presetName(s),'注文を全部任せる');assert.equal(s.workPlan.budget,1200);assert.equal(s.workPlan.keepCraft,0);assert.equal(s.workPlan.target,0);assert.equal(s.dailyCrop,'off');s=act(s,'workPreset',{mode:'creative'});assert.equal(s.workPlan.keepCraft,1);assert.equal(E.presetName(s),'試作の余力を残す');s=act(s,'workPreset',{mode:'manual'});assert.equal(s.workPlan.enabled,false);assert.equal(s.dailyCrop,'off');const old=JSON.stringify(s);assert.equal(E.transact(s,'workPreset',{mode:'unknown'}).ok,false);assert.equal(JSON.stringify(s),old)});
test('intermediate flour cannot consume the frame reserved for personal experimentation',()=>{let s=fresh();s.dailyCrop='off';s.lots=[];E.addLot(s,'wheat',6);job(s);s=act(s,'workPlan',{enabled:true,keepCraft:E.craftLimit(s)-1});const before={money:s.money,lots:E.clone(s.lots),rng:s.rng};s=act(s,'runWorkPlan');assert.equal(s.used.craft,0);assert.equal(s.money,before.money);assert.equal(s.rng,before.rng);assert.deepEqual(s.lots,before.lots);assert.match(s.lastDelegation.stops[0].reason,/自分用/);s=act(s,'workPlan',{keepCraft:E.craftLimit(s)-2});s=act(s,'runWorkPlan');assert.equal(s.used.craft,2);assert.equal(s.stats.delivered,1)});
test('v55 save upgrade preserves custom work settings, all assets and first evaluation',()=>{let s=fresh();s.contentVersion='55.0';s.gameRulesVersion='2.1.0';delete s.recruitment;delete s.finance;s.workPlan={...s.workPlan,enabled:true,budget:415,keepCraft:2,target:3};s.settings.fullReport=true;const old=E.clone(s),up=S.parse(JSON.stringify(S.envelope(s))).runs[s.runId];assert.equal(up.contentVersion,E.D.content);for(const key of ['workPlan','workPlanUsage','lots','money','orders','staff','recipes','dailyCrop','settings','initialEvaluation'])assert.deepEqual(up[key],old[key],key)});
test('ended company offers no misleading available job until continuation is chosen',()=>{const s=fresh();s.ended=true;const o=job(s);assert.equal(E.preparePreview(s,o.id).ok,false);assert.equal(E.offerPreview(s,s.candidates[0].id).ok,false);const a=E.todayStatus(s);assert.equal(a.choices.length+a.newOffers.length+a.growth.length,0);assert.equal(a.close.report,null)});
test('budget and held-frame stopping explanations lead to the relevant setting',()=>{assert.equal(E.stopAdvice('おまかせの残り予算が不足しています').link,'予算を調整');assert.equal(E.stopAdvice('今日の加工枠が不足しています（自分用に1枠を確保中）').link,'任せ方を変える');assert.equal(E.stopAdvice('今日の加工枠が不足しています').to,'grow/facilities')});
