'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),E=require('../actions.js'),S=require('../storage.js');
const fresh=()=>E.newGame('WORK-55');
function act(s,a,p={},token){const r=E.transact(s,a,p,token);assert.ok(r.ok,a+': '+r.error);return r.state}
function order(s,id='bread',n=3,q=0){const o=E.order(s,id,n,q,'sakura');s.orders.push({...o,dueDay:s.day+2,acceptedDay:s.day,auto:false});return o.id}
function fail(s,a,p,pattern){const before=JSON.stringify(s),r=E.transact(s,a,p);assert.equal(r.ok,false);assert.equal(JSON.stringify(s),before);if(pattern)assert.match(r.error,pattern)}
function planOn(s,extra={}){return act(s,'workPlan',{enabled:true,keepCraft:0,...extra})}
test('bundle preview is pure and matches manual chain cost, lots, quality, staff and RNG',()=>{let s=fresh();s.lots=[];const id=order(s),before=JSON.stringify(s),p=E.preparePreview(s,id);assert.ok(p.ok,p.reason);assert.equal(p.produce,1);assert.equal(p.craft,2);assert.equal(p.spent,162);assert.equal(JSON.stringify(s),before);let manual=E.clone(s);for(const step of p.steps)manual=act(manual,step.type,{id:step.id,n:step.n,policy:'standard'});manual=act(manual,'reserve',{id});const bundle=act(s,'prepareOrder',{id});assert.deepEqual(bundle.lots,manual.lots);assert.deepEqual(bundle.staff,manual.staff);assert.equal(bundle.rng,manual.rng);assert.deepEqual(bundle.materialXP,manual.materialXP);assert.equal(bundle.money,manual.money);assert.deepEqual(bundle.used,manual.used)});
test('failed bundle is atomic after intermediate steps and double tap is rejected',()=>{let s=fresh();const id=order(s);s.used.craft=4;fail(s,'prepareOrder',{id},/加工枠/);s.used.craft=0;const token=s.transactionSeq+1;s=act(s,'prepareOrder',{id,deliver:true},token);assert.equal(s.stats.delivered,1);const r=E.transact(s,'prepareOrder',{id,deliver:true},token);assert.equal(r.ok,false);assert.equal(r.state,s)});
test('bundle and work plan protect locked, reserved and high-quality order stocks',()=>{let s=fresh();s.lots=[];const locked=E.addLot(s,'wheat',6,6,6,12,{locked:true}),other=E.addLot(s,'wheat',6,6,6,12,{reservation:'another-order'}),id=order(s);s=act(s,'prepareOrder',{id});assert.equal(s.lots.find(l=>l.lotId===locked.lotId).quantity,6);assert.equal(s.lots.find(l=>l.lotId===other.lotId).quantity,6);assert.ok(s.lots.filter(l=>l.itemId==='bread').every(l=>l.materialPotential===0&&l.reservation===id));});
test('bundle is allowed with full warehouse if crafting decreases net volume',()=>{let s=fresh();s.lots=[];s.scenario='small';E.addLot(s,'vegetable',24);const id=order(s,'salad',3);const p=E.preparePreview(s,id);assert.ok(p.ok,p.reason);s=act(s,'prepareOrder',{id});assert.equal(E.total(s),21)});
test('work plan uses normal daily frames and one daily budget across run-now and close',()=>{let s=fresh();s.lots=[];s.dailyCrop='off';order(s);s=planOn(s,{budget:100,targetItem:'salad',target:1,deliver:false});s=act(s,'runWorkPlan');assert.ok(s.workPlanUsage.spent<=100);const spent=s.workPlanUsage.spent;assert.ok(s.used.produce>0&&s.used.craft>0);s=act(s,'nextDay',{day:1});assert.ok(s.lastReport.delegation.spent+spent<=100);assert.ok(s.lastReport.delegation.stops.length);const saved=S.parse(JSON.stringify(S.envelope(s))).runs[s.runId];assert.deepEqual(s,saved)});
test('quality challenge is stopped before spending or RNG; guaranteed E cap remains C',()=>{let s=fresh();s.lots=[];E.addLot(s,'flour',2,0,0,12);order(s,'bread',2,4);s.guarantees.bread=4;s=planOn(s);const before={money:s.money,rng:s.rng,lots:E.clone(s.lots)};s=act(s,'runWorkPlan');assert.equal(s.money,before.money);assert.equal(s.rng,before.rng);assert.deepEqual(s.lots,before.lots);assert.match(s.lastDelegation.stops[0].reason,/保証/);assert.equal(s.used.craft,0)});
test('routine prepares partial batches over days and reserves them until full delivery',()=>{let s=fresh();s.lots=[];s.dailyCrop='off';order(s,'bread',6);s=planOn(s,{keepCraft:3,budget:1000});s=act(s,'nextDay',{day:1});assert.equal(s.stats.delivered,0);assert.equal(E.qty(s,'bread',0,s.orders[0].id),3);assert.equal(s.lastReport.delegation.craft,2);s=act(s,'nextDay',{day:2});assert.equal(s.stats.delivered,1);assert.equal(s.orders.length,0);assert.equal(s.lastReport.delegation.delivered,1)});
test('work plan reserves a single own batch across compound recipe requirements',()=>{let s=fresh();s.lots=[];E.addLot(s,'flour',4,0,0,12);const id=order(s,'flour',3);s.orders[0].requirements=[{itemId:'flour',quantity:3},{itemId:'bread',quantity:3}];s=act(s,'prepareOrder',{id,deliver:true});assert.equal(s.stats.delivered,1);assert.equal(s.orders.length,0)});
test('production XP is based on stored quantity, capped per crop/day and independent of splitting',()=>{let large=fresh(),small=E.clone(large);large=act(large,'produce',{id:'wheat',n:3});for(let i=0;i<3;i++)small=act(small,'produce',{id:'wheat',n:1});assert.deepEqual(large.materialXP,small.materialXP);assert.equal(large.staff[0].exp,small.staff[0].exp);let capped=fresh();for(let i=0;i<3;i++)capped=act(capped,'produce',{id:'wheat',n:8});assert.equal(capped.materialXP.wheat,4);let overflow=fresh();overflow.lots=[];E.addLot(overflow,'vegetable',39);overflow=act(overflow,'produce',{id:'wheat',n:8,overflow:true});assert.equal(overflow.materialXP.wheat,0);assert.equal(overflow.stats.waste,7)});
test('v53/v54 upgrade preserves assets, contracts, evaluation and old lot quality',()=>{let s=fresh();s.gameRulesVersion='2.0.0';s.contentVersion='54.0';delete s.workPlan;delete s.workPlanUsage;delete s.harvestProgress;const id=order(s);E.addLot(s,'bread',1,6,0,500);const old=E.clone(s),raw=JSON.stringify(S.envelope(s)),storage={data:{[S.KEY]:raw},getItem(k){return this.data[k]||null},setItem(k,v){this.data[k]=v}},store=S.createStore(storage);const env=store.load(),up=env.runs[s.runId];assert.equal(up.gameRulesVersion,E.D.rules);assert.equal(up.workPlan.enabled,false);assert.deepEqual(up.lots,old.lots);assert.deepEqual(up.orders,old.orders);assert.equal(up.orders[0].id,id);assert.equal(up.money,old.money);store.save(env);assert.equal(storage.data[S.BACKUP],raw)});
test('work-plan save failure cannot close the same day twice in memory',()=>{let s=planOn(fresh()),id=order(s);s=act(s,'nextDay',{day:1});const before=E.clone(s);fail(s,'nextDay',{day:1},/処理済み/);assert.deepEqual(s,before);assert.equal(s.stats.delivered,1);assert.ok(!s.orders.find(o=>o.id===id))});
test('day60 includes delegated final delivery and final first evaluation remains permanent',()=>{let s=fresh();s.day=60;s.dailyCrop='off';s.lots=[];E.addLot(s,'wheat',6);order(s);s=planOn(s);s=act(s,'nextDay',{day:60});assert.equal(s.day,60);assert.equal(s.ended,true);assert.equal(s.initialEvaluation.stats.delivered,1);const first=E.clone(s.initialEvaluation);s=act(s,'continue');s=act(s,'nextDay',{day:61});assert.equal(s.day,62);assert.deepEqual(s.initialEvaluation,first)});
test('invalid work settings and forged affinity data are rejected on import',()=>{let s=fresh();fail(s,'workPlan',{budget:-1});fail(s,'workPlan',{target:Infinity});fail(s,'workPlan',{enabled:'yes'});s.workPlan.keepCraft=-1;assert.throws(()=>S.parse(JSON.stringify(S.envelope(s))));s=fresh();s.day=6;s.research.recipe=2;E.addLot(s,'flour',1);E.addLot(s,'milk',1);s=act(s,'prototype',{name:'テスト',main:'flour',ingredients:{flour:1,milk:1}});s.recipes[0].affinity.bonus=24;assert.throws(()=>S.parse(JSON.stringify(S.envelope(s))),/相性/)});
test('seven compatibility tiers sum with a cap and never reward duplicate premium families',()=>{const a=E.F.analyze({flour:1,milk:1}),duplicate=E.F.analyze({flour:2,milk:1,richMilk:3});assert.equal(a.total,3);assert.equal(a.bonus,12);assert.equal(a.weak,false);assert.deepEqual(a,duplicate);const tiers=new Set;for(const x of Object.keys(E.D.items))for(const y of Object.keys(E.D.items))for(const d of E.F.analyze({[x]:1,[y]:1}).details)tiers.add(d.tier);assert.deepEqual([...tiers].sort(),[-1,-2,-3,0,1,2,3].sort());const bad=E.F.analyze({sweets:1,meat:1,deli:1,bento:1});assert.ok(bad.total<0);assert.ok(bad.bonus>=-24);assert.equal(bad.weak,false)});
test('weak total, including positive/negative cancellation, adds bounded saved-RNG randomness',()=>{const a=E.F.analyze({wheat:1,vegetable:1});assert.equal(a.total,0);assert.equal(a.weak,true);const base=[.3,.4,.3,0,0,0,0],s=fresh(),start=E.clone(s),draw=E.F.draw(s,base,a,E.rand),repeat=E.F.draw(start,base,a,E.rand);assert.deepEqual(draw,repeat);assert.equal(s.rng,start.rng);assert.ok(draw.random>=-8&&draw.random<=8);assert.equal(draw.adjusted,Math.max(0,Math.min(999,Math.round(draw.raw*10)+draw.random*10))/10);const mixed=E.F.analyze({bread:1,sweets:1,meat:1});assert.equal(mixed.total,1);assert.equal(mixed.weak,true)});
test('displayed affinity probabilities exactly equal all discrete draw outcomes',()=>{const base=[0,0,.1,.35,.4,.15,0];for(const a of [E.F.analyze({flour:1,milk:1}),E.F.analyze({sweets:1,deli:1}),E.F.analyze({wheat:1,vegetable:1}),E.F.analyze({bread:1,sweets:1,meat:1})]){const probs=E.F.distribution(base,a),counts=Array(7).fill(0),jitter=a.weak?17:1;for(let raw=0;raw<1000;raw++)for(let j=0;j<jitter;j++){const values=[(raw+.25)/1000,(j+.25)/17];const draw=E.F.draw({},base,a,()=>values.shift());counts[draw.quality]++}for(let q=0;q<7;q++)assert.ok(Math.abs(probs[q]-counts[q]/(1000*jitter))<1e-10);assert.equal(probs[0]+probs[1]+probs[6],0);assert.ok(Math.abs(probs.reduce((a,b)=>a+b,0)-1)<1e-10)}});
test('positive and negative affinity move quality in the stated direction without exceeding E origin ceiling',()=>{let s=fresh();s.day=6;s.research.recipe=2;s.research.quality=2;E.addLot(s,'flour',1);E.addLot(s,'milk',1);const draft=E.recipeDraft(s,{name:'ミルク',main:'flour',ingredients:{flour:1,milk:1}}),plan=E.craftPlan(s,'draft',1,{recipe:draft,policy:'trial'});assert.ok(plan.ok);const q=plan.q,mean=a=>a.reduce((v,p,i)=>v+p*i,0);assert.equal(q.cap,2);assert.ok(mean(q.probabilities)>=mean(q.baseProbabilities));assert.equal(q.probabilities.slice(3).reduce((a,b)=>a+b,0),0);const negative=E.F.distribution(q.baseProbabilities,E.F.analyze({sweets:1,deli:1}));assert.ok(mean(negative)<=mean(q.baseProbabilities))});
test('prototype preview does not roll and saved tasting preserves exact correction after resume/revision',()=>{let s=fresh();s.day=6;s.research.recipe=2;s.lots=[];E.addLot(s,'wheat',5);E.addLot(s,'vegetable',5);const p={name:'素朴な新作',main:'wheat',ingredients:{wheat:1,vegetable:1}},rng=s.rng,draft=E.recipeDraft(s,p);for(let i=0;i<10;i++)E.craftPlan(s,'draft',1,{recipe:draft,policy:'trial'});assert.equal(s.rng,rng);s=act(s,'prototype',p);const old=E.clone(s.recipes[0]),tasting=old.lastTasting.flavorRoll;assert.ok(tasting);const restored=S.parse(JSON.stringify(S.envelope(s))).runs[s.runId];assert.deepEqual(restored.recipes[0].lastTasting,old.lastTasting);s=act(s,'prototype',{...p,parent:old.id,ingredients:{wheat:2,vegetable:1}});assert.deepEqual(s.recipes[0],old);assert.equal(s.recipes[1].recipeVersion,2)});
