'use strict';const assert=require('node:assert/strict'),test=require('node:test'),fs=require('fs'),path=require('path'),E=require('../actions.js'),S=require('../storage.js');
function fresh(){return E.newGame('ACCEPTANCE-53')}
function doIt(s,a,p={},token){const r=E.transact(s,a,p,token);assert.ok(r.ok,a+': '+r.error);return r.state}
function fail(s,a,p={},match){const original=JSON.stringify(s),r=E.transact(s,a,p);assert.equal(r.ok,false,a+' should fail');assert.equal(JSON.stringify(s),original,'failed transaction mutated input');if(match)assert.match(r.error,match);return r}
function stock(s,id,n,q=0,p=q,opts={}){return E.addLot(s,id,n,q,p,E.item(s,id)?.cost||10,opts)}
class Memory{constructor(){this.data={};this.fail=null}getItem(k){return this.data[k]??null}setItem(k,v){if(this.fail===k||this.fail==='all')throw Error('QuotaExceeded');this.data[k]=v}}
test('T01 representative production→processing→contract→delivery→research→hire→assignment',()=>{let s=fresh();s=doIt(s,'produce',{id:'wheat',n:3});s=doIt(s,'craft',{id:'flour',n:3});s=doIt(s,'craft',{id:'bread',n:3});s=doIt(s,'accept',{id:s.candidates[0].id});s=doIt(s,'deliver',{id:s.orders[0].id});assert.equal(s.stats.delivered,1);s=doIt(s,'nextDay',{day:1});s.rp=100;s=doIt(s,'research',{id:'quality'});s=doIt(s,'recruit',{campaign:'flyer',focus:'workshop'});const hired=s.recruitment.candidates[0].id;s=doIt(s,'hire',{id:hired});s=doIt(s,'assign',{id:hired,role:'lab'});assert.equal(s.staff.find(x=>x.id===hired).assigned,'lab');assert.equal(s.day,2);E.validate(s)});
test('T02 warehouse free2, buy5 retains2 discards3 only with consent; all-discard allowed explicit',()=>{let s=fresh();s.lots=[];stock(s,'wheat',E.capacity(s)-2);const money=s.money;fail(s,'buy',{id:'milk',n:5},/確認/);s=doIt(s,'buy',{id:'milk',n:5,overflow:true});assert.equal(E.qty(s,'milk'),2);assert.equal(money-s.money,450);assert.equal(s.stats.waste,3);s=doIt(s,'buy',{id:'milk',n:5,overflow:true});assert.equal(s.stats.waste,8);fail(s,'buy',{id:'milk',n:1},/単位/)});
test('T03 full warehouse processing uses net capacity',()=>{let s=fresh();s.lots=[];stock(s,'wheat',E.capacity(s));s=doIt(s,'craft',{id:'flour',n:1});assert.equal(E.total(s),E.capacity(s)-1)});
test('T04 new milk never resets old expiry',()=>{let s=fresh();s=doIt(s,'buy',{id:'milk',n:5});const old=s.lots.find(l=>l.itemId==='milk');s=doIt(s,'nextDay',{day:1});s=doIt(s,'buy',{id:'milk',n:5});const milks=s.lots.filter(l=>l.itemId==='milk');assert.equal(milks[0].expiresAfterDay,old.expiresAfterDay);assert.equal(milks[1].expiresAfterDay,4)});
test('T05 partial consumption, reservation split and rework retain lot metadata',()=>{let s=fresh();s.lots=[];const l=stock(s,'bread',5,0,2,{expiresAfterDay:3,reworkCount:0});s.candidates=[E.order(s,'bread',2,0,'sakura')];s=doIt(s,'accept',{id:s.candidates[0].id});s=doIt(s,'reserve',{id:s.orders[0].id});assert.equal(s.lots.length,2);assert.ok(s.lots.every(x=>x.expiresAfterDay===3&&x.qualityRank===0));s.rp=500;const free=s.lots.find(x=>!x.reservation);s=doIt(s,'improve',{id:free.lotId,n:1});const done=s.lots.find(x=>x.reworkCount===1);assert.equal(done.expiresAfterDay,3);fail(s,'improve',{id:done.lotId,n:1},/改善済み/);s=doIt(s,'deliver',{id:s.orders[0].id});assert.equal(E.total(s),3)});
test('T06 E material and A guarantee strictly yields C; preview agrees',()=>{let s=fresh();s.lots=[];stock(s,'flour',3,0,0);s.guarantees.bread=4;const p=E.craftPlan(s,'bread',1);assert.equal(p.q.cap,2);assert.equal(p.q.floor,2);assert.equal(p.q.probabilities[2],1);s=doIt(s,'craft',{id:'bread',n:1});assert.equal(s.lots.find(l=>l.itemId==='bread').qualityRank,2)});
test('T07 unused rare lot has no effect; explicit substitution changes potential',()=>{const a=fresh(),b=E.clone(a);stock(b,'premiumWheat',2,6,6);assert.deepEqual(E.craftPlan(a,'flour',1).q,E.craftPlan(b,'flour',1).q);assert.equal(E.craftPlan(b,'flour',1,{substitute:{wheat:'premiumWheat'}}).q.cap,6)});
test('T08 flour retains original E potential even with C guarantee',()=>{let s=fresh();s.guarantees.flour=2;s.guarantees.bread=4;s=doIt(s,'craft',{id:'flour',n:2});assert.equal(s.lots.find(l=>l.itemId==='flour').materialPotential,0);s=doIt(s,'craft',{id:'bread',n:2});assert.equal(s.lots.find(l=>l.itemId==='bread').qualityRank,2)});
test('T09 dueDay day10 + 3 days = 12, candidates never expire contracts twice',()=>{let s=fresh();s.day=10;s.lots=[];s.candidates=[E.order(s,'bread',2,0,'sakura')];s=doIt(s,'accept',{id:s.candidates[0].id});assert.equal(s.orders[0].dueDay,12);for(let d=10;d<=12;d++)s=doIt(s,'nextDay',{day:d});assert.equal(s.day,13);assert.equal(s.orders.length,0);assert.equal(s.stats.failed,1)});
test('T10 skipping candidates does not affect reputation or company XP',()=>{let s=fresh(),rep=s.reputation,xp=s.companyXP;s=doIt(s,'skip',{id:s.candidates[0].id});assert.equal(s.reputation,rep);assert.equal(s.companyXP,xp);assert.equal(s.candidates.length,2)});
test('T11 analysis changes candidates only and capped once/day',()=>{let s=fresh();s.rp=150;s=doIt(s,'accept',{id:s.candidates[0].id});const contract=E.clone(s.orders);s=doIt(s,'market');assert.deepEqual(s.orders,contract);fail(s,'market',{},/1日1回/)});
test('T12 same transaction sequence accepted only once; previews do not change RNG',()=>{let s=fresh(),token=s.transactionSeq+1;s=doIt(s,'produce',{id:'wheat',n:1},token);const r=E.transact(s,'produce',{id:'wheat',n:1},token);assert.equal(r.ok,false);const rng=s.rng;for(let i=0;i<30;i++)E.craftPlan(s,'flour',1);assert.equal(s.rng,rng)});
test('T13 serialized daily commit cannot be repeated on reload',()=>{let s=fresh();s=doIt(s,'nextDay',{day:1});const restored=S.parse(JSON.stringify(S.envelope(s))).runs[s.runId];fail(restored,'nextDay',{day:1},/処理済み/);assert.equal(restored.day,2);assert.equal(restored.reports.length,1)});
test('T14 localStorage failure keeps previous persisted state and retry same commit',()=>{const memory=new Memory,store=S.createStore(memory);assert.equal(store.load(),null);let env=store.save(S.envelope(fresh())),s=env.runs[env.current];s=doIt(s,'nextDay',{day:1});env.runs[env.current]=s;memory.fail=S.KEY;assert.throws(()=>store.save(env),/保存できません/);assert.equal(S.parse(memory.getItem(S.KEY)).runs[s.runId].day,1);assert.equal(store.pending.runs[s.runId].day,2);memory.fail=null;env=store.save(env);assert.equal(env.runs[s.runId].day,2);assert.equal(env.runs[s.runId].reports.length,1)});
test('T15 moving logistician does not destroy existing overcapacity stock',()=>{let s=fresh();s.staff.push(E.makeStaff('haru'));s.lots=[];stock(s,'wheat',E.capacity(s));s.staff.find(t=>t.id==='haru').usedDay=0;const qty=E.total(s);s=doIt(s,'assign',{id:'haru',role:'lab'});assert.ok(E.total(s)>E.capacity(s));assert.equal(E.total(s),qty)});
test('T16 automation respects locked inputs, reservations, budget and quality',()=>{let s=fresh();s.lots=[];s.dailyCrop='off';stock(s,'wheat',10,4,4,{locked:true});s.auto.flourMill={level:1,enabled:true,target:2,budget:500,minQuality:0,status:''};s=doIt(s,'nextDay',{day:1});assert.equal(E.qty(s,'flour'),0);assert.match(s.auto.flourMill.status,/不足/);s.lots[0].locked=false;s.auto.flourMill.budget=0;s=doIt(s,'nextDay',{day:2});assert.equal(E.qty(s,'flour'),0);assert.match(s.auto.flourMill.status,/予算/);s.auto.flourMill.budget=500;s.auto.flourMill.minQuality=5;s=doIt(s,'nextDay',{day:3});assert.match(s.auto.flourMill.status,/保証/)});
test('T17 original revision creates separate recipe, lot and contract identities',()=>{let s=fresh();s.day=8;s.lots=[];stock(s,'flour',5,3,3);stock(s,'milk',5,3,3);s.rp=300;s=doIt(s,'prototype',{name:'一号',main:'flour',ingredients:{flour:1,milk:1}});let first=s.recipes[0];while(first.completion<100){s=doIt(s,'refine',{id:first.id});first=s.recipes[0]}s=doIt(s,'formalize',{id:first.id});s.candidates=[E.order(s,first.id,1,0,'sakura')];s=doIt(s,'accept',{id:s.candidates[0].id});const before=E.clone(s.orders[0]);s=doIt(s,'prototype',{name:'二号',main:'flour',ingredients:{flour:2,milk:1},parent:first.id});assert.equal(s.recipes.length,2);assert.equal(s.recipes[1].recipeVersion,2);assert.deepEqual(s.orders[0],before);assert.ok(s.lots.some(l=>l.itemId===first.id))});
test('T18 reputation drop and paid ads never lower or buy company experience',()=>{let s=fresh();s.companyXP=100;s.levelClaimed=5;s.money=100000;const lvl=E.level(s);s=doIt(s,'invest',{id:'ads'});assert.equal(s.companyXP,100);s.reputation=0;assert.equal(E.level(s),lvl)});
test('T19 day60 final sale included; day61 only after explicit continue',()=>{let s=fresh();s.day=60;s.lots=[];stock(s,'bread',2);s.candidates=[E.order(s,'bread',2,0,'sakura')];s=doIt(s,'accept',{id:s.candidates[0].id});s=doIt(s,'deliver',{id:s.orders[0].id});s=doIt(s,'nextDay',{day:60});assert.equal(s.day,60);assert.equal(s.initialEvaluation.stats.delivered,1);assert.equal(s.ended,true);const first=E.clone(s.initialEvaluation);s=doIt(s,'continue');assert.equal(s.day,61);s=doIt(s,'nextDay',{day:61});assert.deepEqual(s.initialEvaluation,first)});
test('T20 sample submitted day5 scored day15 once; expiry irrelevant',()=>{let s=fresh();s.day=5;s.lots=[];const lot=stock(s,'bread',1,4,3,{expiresAfterDay:5});s=doIt(s,'contest',{key:'breadCup',lot:lot.lotId});assert.equal(s.lots.length,0);assert.equal(s.contestEntries[0].lot.qualityRank,4);for(let d=5;d<=15;d++)s=doIt(s,'nextDay',{day:d});assert.equal(s.contestHistory.length,1);s=doIt(s,'nextDay',{day:16});assert.equal(s.contestHistory.length,1)});
const legacyFixture={day:10,money:23450,reputation:50,researchPoints:400,facilities:{farm:2,workshop:2,warehouse:2,lab:2},research:{production:2,quality:2,processing:1,storage:0,sales:1,recipe:2},inventory:{milk:6,bread:5,wheat:10,originalDish:2},qualityStock:{bread:{E:1,D:1,A:5},originalDish:{B:2}},stockAges:{milk:2,bread:1},productRarity:{wheat:'C',milk:'D'},orderSkills:{bread:'A'},stats:{levelRewardClaimed:5,totalSales:50000,ordersDone:15},staff:[{id:3,name:'旧こむぎ',assigned:'workshop',level:4,exp:2,stats:{production:2,craft:8,sales:2,research:2,logistics:2}}],orders:[{id:1,title:'旧複合契約',req:{bread:2,milk:1},reward:1300,rep:3,left:1,days:4,status:'active',minQuality:'D'},{id:2,title:'旧候補',req:{bread:2},reward:500,rep:2,left:2,days:3,status:'open',minQuality:'E'}],originalRecipe:{name:'初代',ingredients:{wheat:1,milk:1},rank:'B'},contestEntries:{breadCup:{resultDay:15,product:'bread',rank:'A',baseScore:75,resolved:false}},unlockedRegions:['town','shopping'],region:'shopping',unlockedTitles:{qualityMaster:true}};
test('T21 synthetic v52 fixture preserves assets, multi-item contracts, grades and notes',()=>{let s=S.migrateV52(legacyFixture);assert.equal(s.money,23450);assert.equal(E.total(s),23);assert.equal(E.qty(s,'bread',4),5);assert.equal(s.guarantees.bread,4);assert.equal(s.orders[0].dueDay,11);assert.equal(E.level(s),5);assert.equal(s.levelClaimed,5);assert.equal(s.recipes[0].recipeVersion,1);assert.equal(s.contestEntries[0].day,15);assert.ok(s.legacy.migrationLog.some(t=>t.includes('不一致')));assert.deepEqual(s.legacy.original,legacyFixture);const bread=E.qty(s,'bread'),milk=E.qty(s,'milk');s=doIt(s,'deliver',{id:s.orders[0].id});assert.equal(E.qty(s,'bread'),bread-2);assert.equal(E.qty(s,'milk'),milk-1)});
test('T22 corrupt data is not initialized; second tab conflict and backup valid',()=>{const mem=new Memory,one=S.createStore(mem);one.load();let env=one.save(S.envelope(fresh()));const two=S.createStore(mem),other=two.load();env.runs[env.current]=doIt(env.runs[env.current],'nextDay',{day:1});one.save(env);assert.throws(()=>two.save(other),/別タブ/);assert.equal(one.backup().runs[env.current].day,1);mem.setItem(S.KEY,'{broken');assert.throws(()=>S.createStore(mem).load(),/壊れ/);assert.equal(mem.getItem(S.KEY),'{broken');const restored=one.restore();assert.equal(restored.runs[restored.current].day,1)});
test('T23 separate scenario preserves company and deduplicates shared profile',()=>{const s=fresh();s.titles=['品質職人'];let env=S.envelope(s);S.syncProfile(env);S.syncProfile(env);assert.equal(env.profile.titles.length,1);const other=E.newGame('SAME','small');env.runs[other.runId]=other;env.current=other.runId;S.validateEnvelope(env);assert.equal(env.runs[s.runId].money,s.money);assert.equal(env.runs[other.runId].scenario,'small')});
test('T25 muted and reduced-motion preferences persist',()=>{let s=fresh();s=doIt(s,'settings',{bgm:0,sfx:0,reduced:true,short:true});const env=S.parse(JSON.stringify(S.envelope(s)));assert.deepEqual(env.runs[s.runId].settings,{bgm:0,sfx:0,reduced:true,short:true})});
test('T26 used staff reassignment delayed until following morning',()=>{let s=fresh();s=doIt(s,'produce',{id:'wheat',n:1});const xp=s.staff[0].exp;s=doIt(s,'assign',{id:'minori',role:'lab'});assert.equal(s.staff[0].assigned,'farm');assert.equal(s.staff[0].nextAssignment,'lab');assert.equal(s.staff[0].exp,xp);s.dailyCrop='off';s=doIt(s,'nextDay',{day:1});assert.equal(s.staff[0].assigned,'lab');assert.equal(s.staff[0].exp,xp)});
test('invalid inputs never partially consume resources',()=>{let s=fresh();for(const n of [-1,NaN,Infinity,.5,999999999]){fail(s,'buy',{id:'milk',n});fail(s,'craft',{id:'bread',n})}fail(s,'craft',{id:'bread',n:1});const bad=E.clone(s);bad.lots[0].qualityRank=7;assert.throws(()=>S.parse(JSON.stringify(S.envelope(bad))));const injected=E.clone(s);injected.name='<img src=x onerror=alert(1)>';const text=S.createStore(new Memory).export(S.envelope(injected));assert.ok(text.includes('<img'))});
test('same seed and action sequence produce identical economic state',()=>{let a=fresh(),b=fresh();for(let day=1;day<=15;day++){a=doIt(a,'nextDay',{day});b=doIt(b,'nextDay',{day})}assert.equal(a.rng,b.rng);assert.equal(a.money,b.money);assert.deepEqual(a.candidates,b.candidates)});
test('finite scenario ends on its own final business day',()=>{let s=E.newGame('SCENARIO','small');for(let d=1;d<=30;d++)s=doIt(s,'nextDay',{day:d});assert.equal(s.ended,true);assert.equal(s.day,30);assert.equal(s.initialEvaluation.day,30)});
if(process.env.WRITE_FIXTURE)fs.writeFileSync(path.join(__dirname,'synthetic-v52-save.json'),JSON.stringify(legacyFixture,null,2));
test('typed validation rejects nonfinite production and malicious import requirements',()=>{const s=fresh();for(const n of [NaN,Infinity,-1,.1])fail(s,'produce',{id:'wheat',n});const bad=E.clone(s);bad.orders=[{...bad.candidates[0],dueDay:3,requirements:[{itemId:'bread',quantity:-4}]}];assert.throws(()=>S.parse(JSON.stringify(S.envelope(bad))))});
test('recovery from corrupt main preserves raw corrupt data and loads valid incoming backup',()=>{const m=new Memory;m.setItem(S.KEY,'{broken');const store=S.createStore(m);assert.throws(()=>store.load());const env=store.recover(S.envelope(fresh()));assert.equal(env.runs[env.current].day,1);assert.equal(m.getItem(S.KEY+'.corrupt'),'{broken');S.parse(m.getItem(S.KEY))});
test('staff sales bonus quotes current assignment, locks upon acceptance and contracts remain fixed',()=>{let s=fresh();s.staff.push(E.makeStaff('aoi'));const id=s.candidates[0].id,base=s.candidates[0].reward;assert.ok(E.quoteReward(s,s.candidates[0])>base);s=doIt(s,'accept',{id});const reward=s.orders[0].reward;s=doIt(s,'assign',{id:'aoi',role:'lab'});assert.equal(s.staff.find(t=>t.id==='aoi').assigned,'sales');assert.equal(s.orders[0].reward,reward)});
test('ignoring warned adverse event uses declared free response',()=>{let s=fresh();s.event={index:3};s=doIt(s,'nextDay',{day:1});assert.equal(s.buff.kind,'price');assert.equal(s.day,2)});
test('insolvent company can recover via contract work without debt or lost staff',()=>{let s=fresh();s.lots=[];s.money=0;const staff=s.staff.length;s=doIt(s,'contractWork');assert.equal(s.money,220);s=doIt(s,'produce',{id:'wheat',n:4});s=doIt(s,'nextDay',{day:1});assert.ok(s.money>=0);assert.equal(s.staff.length,staff)});
test('endless v52 migration does not incorrectly restart day60 evaluation',()=>{const old=E.clone(legacyFixture);old.day=90;old.endless=true;old.stats.endEvaluated=true;let s=S.migrateV52(old);assert.equal(s.endless,true);assert.equal(s.initialEvaluation.legacyEstimate,true);s=doIt(s,'nextDay',{day:90});assert.equal(s.day,91)});
test('T05 exact-lot merge preserves every semantic field and never refreshes expiry',()=>{let s=fresh();s.lots=[];stock(s,'bread',2,2,1,{madeDay:1,expiresAfterDay:3,reworkCount:1});stock(s,'bread',3,2,1,{madeDay:1,expiresAfterDay:3,reworkCount:1});stock(s,'bread',1,2,1,{madeDay:1,expiresAfterDay:4,reworkCount:1});s=doIt(s,'mergeLots');assert.equal(s.lots.length,2);assert.equal(s.lots[0].quantity,5);assert.equal(s.lots[0].expiresAfterDay,3);assert.equal(s.lots[0].reworkCount,1)});
test('import rejects prototype property names in identity-bearing fields',()=>{const s=fresh();s.candidates[0].customer='__proto__';assert.throws(()=>S.parse(JSON.stringify(S.envelope(s))));assert.equal({}.delivered,undefined)});
test('initial calendar has no accidental day45 repeat; endless reassessment preserves first result',()=>{let s=fresh();s.day=16;assert.equal(E.nextContest(s,'breadCup'),75);s.day=60;s=doIt(s,'nextDay',{day:60});const first=E.clone(s.initialEvaluation);s=doIt(s,'continue');for(let day=61;day<=120;day++)s=doIt(s,'nextDay',{day});assert.equal(s.reevaluations.length,1);assert.equal(s.reevaluations[0].day,120);assert.deepEqual(s.initialEvaluation,first)});
test('migration maps known v52 customer levels, advanced research and rare staff into new roles',()=>{const old=E.clone(legacyFixture);old.customerReputation={families:80,students:22};old.lateResearch={standardization:2};old.staff[0].role='artisan';old.staff[0].rarity='epic';const s=S.migrateV52(old);assert.equal(s.customers.sakura.legacyLevel,5);assert.equal(s.customers.sakura.stage,3);assert.equal(s.customers.sakura.delivered,0);assert.equal(s.standardized.bread,2);assert.equal(s.staff[0].special,'finish')});
test('explicit minori/komugi combination improves distribution without changing material ceiling',()=>{let s=fresh();s.staff.push(E.makeStaff('komugi'));stock(s,'flour',2,0,0);const base=E.craftPlan(s,'bread',1);s=doIt(s,'produce',{id:'wheat',n:1});const boosted=E.craftPlan(s,'bread',1);assert.equal(boosted.q.team,true);assert.equal(boosted.q.cap,base.q.cap);assert.ok(boosted.q.probabilities[2]>base.q.probabilities[2])});
test('reserved materials are excluded from automatic processing and wholesale',()=>{let s=fresh();s.lots=[];s.dailyCrop='off';stock(s,'flour',2);s.candidates=[E.order(s,'flour',2,0,'sakura')];s=doIt(s,'accept',{id:s.candidates[0].id});s=doIt(s,'reserve',{id:s.orders[0].id});s.auto.breadFactory={level:1,enabled:true,target:2,budget:500,minQuality:0,status:''};s.wholesale.flour=5;s=doIt(s,'nextDay',{day:1});assert.equal(E.qty(s,'bread'),0);assert.equal(s.lots.find(l=>l.itemId==='flour').quantity,2);assert.equal(s.stats.wholesale,0)});
test('large legacy quality research remains numerically stable and respects E material ceiling',()=>{let s=fresh();s.research.quality=10000;s.lots=[];stock(s,'flour',1);const plan=E.craftPlan(s,'bread',1);assert.ok(plan.q.probabilities.every(Number.isFinite));assert.ok(Math.abs(plan.q.probabilities.reduce((a,b)=>a+b,0)-1)<1e-10);s=doIt(s,'craft',{id:'bread',n:1});assert.equal(s.lots[0].qualityRank,2)});
test('migrated supply-material quality is retained in new purchases',()=>{const old=E.clone(legacyFixture);old.productRarity.milk='A';let s=S.migrateV52(old);s=doIt(s,'buy',{id:'milk',n:5});assert.equal(s.lots.filter(l=>l.itemId==='milk').at(-1).qualityRank,4)});
