'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),E=require('../actions.js'),S=require('../storage.js');
const fresh=()=>E.newGame('STORY-58');
const act=(s,type,p={})=>{const r=E.transact(s,type,p);assert.equal(r.ok,true,r.error);return r.state};
function clear(s){s.lots=[];s.day=21;s.research.recipe=3;return s}
function lot(s,id,q=0,n=1,potential=q,extra={}){return E.addLot(s,id,n,q,potential,E.standardCost(s,id),extra)}
function order(s,id='bento',n=2,q=2){return E.order(s,id,n,q,'makoto')}
function dinner(){let s=clear(fresh());s=act(s,'diningStart',{id:'picnic',option:0});const b=lot(s,'bread'),v=lot(s,'salad');return {s,p:{lots:[b.lotId,v.lotId],service:'box'}}}

test('bento advice begins with a real missing ingredient and valid procurement unit',()=>{let s=clear(fresh());lot(s,'vegetable',0,4);const g=E.orderGuidance(s,order(s));assert.equal(g.next.p.id,'meat');assert.equal(g.next.p.n,5);assert.match(g.next.title,/肉.*5個/);assert.match(g.qualityNote,/C以上/);assert.match(g.qualityNote,/保証しません/)});
test('advice advances from buying to intermediate craft to target quality using current state',()=>{let s=clear(fresh());lot(s,'vegetable',0,4);const o=order(s);let g=E.orderGuidance(s,o);s=act(s,'buy',{id:g.next.p.id,n:g.next.p.n});g=E.orderGuidance(s,o);assert.equal(g.next.p.id,'deli');s=act(s,'craft',{id:'deli',n:2});g=E.orderGuidance(s,o);assert.equal(g.next.kind,'chance');assert.equal(g.next.p.id,'bento');assert.equal(g.next.action,'guideStandard');assert.equal(g.next.alternative.p.rank,2)});
test('exact odds use craftPlan and first-batch quantity, never hypothetical materials',()=>{const s=clear(fresh());lot(s,'deli',0,2);lot(s,'vegetable',0,2);const o=order(s),g=E.orderGuidance(s,o),p=E.craftPlan(s,'bento',2);assert.equal(g.next.chance,p.q.probabilities.slice(2).reduce((a,b)=>a+b,0));assert.match(g.next.text,/2個を1バッチ/)});
test('material cap guides to material growth, not ineffective quality research',()=>{const s=clear(fresh());lot(s,'deli',2,2,0);lot(s,'vegetable',0,2);s.guarantees.bento=4;const g=E.orderGuidance(s,order(s,'bento',2,3));assert.equal(g.next.kind,'cap');assert.equal(g.next.action,'guideMaterials');assert.match(g.next.title,/最高はC、要求はB/);assert.match(g.next.text,/品質研究だけでは素材上限は上がりません/)});
test('research unlock is explicit and takes precedence over collecting unusable ingredients',()=>{const s=fresh(),g=E.orderGuidance(s,order(s));assert.equal(g.next.action,'guideResearch');assert.equal(g.next.p.id,'recipe');assert.match(g.next.title,/Lv3/);assert.match(g.next.text,/25/)});
test('one-step rework recommends the actual lot and preserves its deadline on execution',()=>{let s=clear(fresh()),l=lot(s,'bento',1,2,1),expiry=l.expiresAfterDay;s.rp=100;const g=E.orderGuidance(s,order(s));assert.equal(g.next.kind,'improve');assert.equal(g.next.p.id,l.lotId);assert.equal(g.next.p.n,2);s=act(s,'improve',g.next.p);assert.equal(s.lots[0].qualityRank,2);assert.equal(s.lots[0].expiresAfterDay,expiry)});
test('zero funds, spent frames, capacity and protected stock get concrete separate routes',()=>{let s=clear(fresh());s.money=0;assert.equal(E.orderGuidance(s,order(s,'salad',1,0)).next.kind,'money');s.money=1000;s.used.produce=E.productionLimit(s);assert.equal(E.orderGuidance(s,order(s,'salad',1,0)).next.kind,'frames');s.used.produce=0;lot(s,'wheat',0,E.capacity(s));assert.equal(E.orderGuidance(s,order(s,'salad',1,0)).next.kind,'capacity');s.lots=[];lot(s,'salad',0,1,0,{locked:true});assert.equal(E.orderGuidance(s,order(s,'salad',1,0)).next.kind,'reserved')});
test('accept limits are explained independently from manufacturing readiness',()=>{const s=clear(fresh());lot(s,'bento',2,2,1);s.used.accept=3;const g=E.orderGuidance(s,order(s));assert.equal(g.next.kind,'ready');assert.match(g.acceptBlock,/新規受注3件/);s.used.accept=0;s.orders=[order(s),order(s)];assert.match(E.orderGuidance(s,order(s)).acceptBlock,/受注枠が満杯/)});
test('advice never mutates cash, RNG, staffing or inventory through repeated rendering',()=>{const s=clear(fresh()),o=order(s),before=JSON.stringify(s);for(let i=0;i<20;i++)E.orderGuidance(s,o);assert.equal(JSON.stringify(s),before)});
test('quality target never leaks into intermediate guidance and preserves order reservation',()=>{const s=clear(fresh()),o=order(s);s.orders=[{...o,dueDay:s.day+2,acceptedDay:s.day}];lot(s,'vegetable',0,4);lot(s,'meat',0,5);const g=E.orderGuidance(s,o);assert.equal(g.next.p.rank,0);assert.equal(g.next.p.reservation,o.id);assert.equal(g.next.p.id,'deli')});
test('whole-day simulations and previews leave optional invitation untouched and never expire it',()=>{let s=fresh();s.day=6;s=act(s,'diningStart',{id:'picnic',option:1});const active=E.clone(s.dining.active);s.dailyCrop='off';for(let i=0;i<12;i++)s=act(s,'nextDay',{day:s.day});assert.deepEqual(s.dining.active,active);assert.equal(s.dining.album.length,0)});
test('dining unlock by day or company level, single active slot, lossless cancellation',()=>{let s=fresh();assert.equal(E.transact(s,'diningStart',{id:'picnic',option:0}).ok,false);s.companyXP=50;s=act(s,'diningStart',{id:'picnic',option:0});const before=E.clone(s);assert.equal(E.transact(s,'diningStart',{id:'picnic',option:1}).ok,false);s=act(s,'diningCancel');for(const k of ['money','rp','reputation','lots','used','rng'])assert.deepEqual(s[k],before[k]);assert.equal(s.dining.active,null)});
test('E bread and E salad match a picnic; quality cannot outweigh purpose and serving style',()=>{const {s,p}=dinner(),r=E.diningPreview(s,p);assert.equal(r.ok,true);assert.equal(r.score,88);assert.equal(r.fit,60);assert.equal(r.quality,0);assert.equal(r.reward,37);const x=lot(s,'premiumBread',6),y=lot(s,'brandSweets',6);assert.ok(E.diningPreview(s,{lots:[x.lotId,y.lotId],service:'table'}).score<r.score);assert.equal(E.diningPreview(s,{...p,service:'table'}).score,74)});
test('preview and actual score match exactly with no gameplay RNG use',()=>{let {s,p}=dinner();const rng=s.rng,before=JSON.stringify(s),r=E.diningPreview(s,p);for(let i=0;i<8;i++)E.diningPreview(s,p);assert.equal(JSON.stringify(s),before);s=act(s,'diningServe',p);assert.equal(s.rng,rng);assert.equal(s.dining.album[0].score,r.score);assert.equal(s.lastDining.score,r.score);assert.equal(s.rp,r.reward);assert.equal(s.lots.length,0)});
test('dining consumes one of each and cannot use reserved, protected, expired, raw or same food',()=>{for(const kind of ['reservation','locked','expired','raw','same']){const {s,p}=dinner(),l=s.lots[0];if(kind==='reservation')l.reservation='other';if(kind==='locked')l.locked=true;if(kind==='expired')l.expiresAfterDay=s.day-1;if(kind==='raw')l.itemId='wheat';if(kind==='same')s.lots[1].itemId=l.itemId;const before=JSON.stringify(s);assert.equal(E.transact(s,'diningServe',p).ok,false,kind);assert.equal(JSON.stringify(s),before)}});
test('double submission cannot repeat rewards or consume another sample',()=>{let {s,p}=dinner();const seq=s.transactionSeq+1;s=act(s,'diningServe',p);assert.equal(E.transact(s,'diningServe',p,seq).ok,false);assert.equal(E.transact(s,'diningServe',p).ok,false);assert.equal(s.dining.album.length,1)});
test('replay records improvement but no repeated research or mastery reward',()=>{let {s,p}=dinner();s=act(s,'diningServe',p);const rp=s.rp,mastery=E.clone(s.mastery);s=act(s,'diningStart',{id:'picnic',option:0});const b=lot(s,'bread',6),v=lot(s,'salad',6);s=act(s,'diningServe',{lots:[b.lotId,v.lotId],service:'box'});assert.equal(s.rp,rp);assert.deepEqual(s.mastery,mastery);assert.equal(s.dining.album.length,1);assert.equal(s.dining.album[0].score,100);assert.match(s.lastResult.sub,/追加報酬なし/)});
test('sample cost affects profit once without a second cash charge or false sales',()=>{let {s,p}=dinner();const r=E.diningPreview(s,p),cash=s.money;s.dailyCrop='off';s=act(s,'diningServe',p);assert.equal(s.money,cash);assert.equal(s.ledger.sales,0);assert.equal(s.ledger.diningCost,r.cost);s=act(s,'nextDay',{day:s.day});assert.equal(s.lastReport.profit,-r.cost-s.lastReport.operating);assert.equal(s.lastReport.cashChange,-s.lastReport.operating)});
test('dining dishes can be prepared through the ordinary batch engine with no extra clicks per material',()=>{let s=fresh();s.day=6;s.lots=[];s=act(s,'diningStart',{id:'picnic',option:0});const pre=E.diningPreparePreview(s,'bread');assert.equal(pre.ok,true);assert.equal(pre.craft,2);const before=s.money;s=act(s,'diningPrepare',{id:'bread'});assert.equal(E.qty(s,'bread'),1);assert.equal(before-s.money,pre.spent);assert.ok(s.lots.every(l=>!l.reservation));const after=s.money;s=act(s,'diningPrepare',{id:'bread'});assert.equal(s.money,after);assert.equal(E.qty(s,'bread'),1)});
test('sample preparation is atomic and honors order locks and limited frames',()=>{let s=fresh();s.day=6;s.lots=[];s=act(s,'diningStart',{id:'picnic',option:0});s.used.craft=E.craftLimit(s)-1;const before=JSON.stringify(s),r=E.transact(s,'diningPrepare',{id:'bread'});assert.equal(r.ok,false);assert.equal(JSON.stringify(s),before)});
test('all four briefs have feasible E-quality pairings without imposing a single high-price dish',()=>{for(const d of E.D.dining){for(let option=0;option<2;option++){let s=clear(fresh());s.day=46;s.research.recipe=6;s.developed={milkBread:true,staminaBento:true,fruitParfait:true,luxurySet:true};s=act(s,'diningStart',{id:d.id,option});const rows=Object.keys(E.D.items).filter(id=>E.item(s,id).kind==='food').map(id=>lot(s,id));let best=0;for(let a=0;a<rows.length;a++)for(let b=a+1;b<rows.length;b++)best=Math.max(best,E.diningPreview(s,{lots:[rows[a].lotId,rows[b].lotId],service:d.options[option].service}).score);assert.ok(best>=88,d.id+'/'+option+': '+best)}}});
test('v57 migration preserves real prior rules, all assets, recruiters, contracts and RNG',()=>{const fs=require('node:fs'),s=JSON.parse(fs.readFileSync(__dirname+'/advanced-test-save.json','utf8')),raw=s.runs?s.runs[s.current]:s;raw.gameRulesVersion='2.2.0';raw.contentVersion='57.0';delete raw.dining;const before=E.clone(raw),out=S.parse(JSON.stringify(raw)).runs[raw.runId];for(const k of ['money','lots','orders','staff','recruitment','finance','rng','used','initialEvaluation','workPlan'])assert.deepEqual(out[k],before[k],k);assert.deepEqual(out.dining,{active:null,album:[]});assert.equal(out.gameRulesVersion,E.D.rules)});
test('album and active brief survive save restart; invalid score and duplicate album fail import',()=>{let {s,p}=dinner();s=act(s,'diningServe',p);s=act(s,'diningStart',{id:'reading',option:1});const restored=S.parse(JSON.stringify(s)).runs[s.runId];assert.deepEqual(restored.dining,s.dining);for(const mode of ['score','duplicate','option']){const copy=E.clone(s);if(mode==='score')copy.dining.album[0].score=101;if(mode==='duplicate')copy.dining.album.push(copy.dining.album[0]);if(mode==='option')copy.dining.active.option=2;assert.throws(()=>S.parse(JSON.stringify(copy)))}});
