'use strict';
// Executes the shipped HTML and real DOM events in jsdom. NOT browser layout/device QA.
// Test dependency only: npm install --prefix <path> jsdom; NODE_PATH=<path>/node_modules node --test ...
const {JSDOM,VirtualConsole}=require('jsdom');
const fs=require('node:fs'),path=require('node:path'),test=require('node:test'),assert=require('node:assert/strict');
const E=require('../actions.js'),S=require('../storage.js');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
function setup(options={}){
  const data={...(options.data||{})},errors=[],flags={failWrite:false};
  const virtualConsole=new VirtualConsole();virtualConsole.on('jsdomError',e=>errors.push(e.message));virtualConsole.on('error',e=>errors.push(String(e)));
  const dom=new JSDOM(html,{url:options.url||'https://example.test/game/',runScripts:'dangerously',pretendToBeVisual:true,virtualConsole,beforeParse(w){
    w.scrollTo=()=>{};
    if(options.audioFail)w.AudioContext=class{constructor(){throw Error('audio unavailable')}};
    if(options.nativeDialog){w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false;w.setTimeout(()=>this.dispatchEvent(new w.Event('close')),0)}}
    Object.defineProperty(w,'localStorage',{get(){if(options.denied)throw new w.DOMException('Storage denied','SecurityError');return {getItem:k=>data[k]??null,setItem:(k,v)=>{if(flags.failWrite)throw new w.DOMException('Quota exceeded','QuotaExceededError');data[k]=String(v)}}}});
  }});
  const w=dom.window,d=w.document;
  function click(action,predicate=()=>true){const el=[...d.querySelectorAll('[data-a]')].find(el=>el.dataset.a===action&&!el.disabled&&predicate(JSON.parse(el.dataset.p||'{}')));assert.ok(el,'enabled button '+action);el.click();return el}
  function start(){click(options.denied?'temporaryStart':'welcomeStart');d.getElementById('new-name').value='スマホ検証食品';click('startNew');assert.ok(w.GCApp.state)}
  return {dom,w,d,data,flags,errors,click,start,close:()=>w.close()};
}
const routes=['home','make/plan','make/craft','make/produce','make/buy','make/inventory','make/original','trade/orders','trade/finance','trade/customers','trade/wholesale','trade/regions','grow/staff','grow/recruit','grow/research','grow/facilities','grow/auto','grow/invest','more/book','more/contests','more/rivals','more/timeline','more/settings'];
test('distributed HTML has all executable scripts and styles inline and boots without sibling files',()=>{const t=setup({url:'file:///isolated/index.html'});try{assert.equal(t.d.querySelectorAll('script[src],link[rel=stylesheet],img[src]').length,0);assert.ok(t.d.querySelector('style').textContent.includes('.company-scene'));assert.ok(t.d.getElementById('boot-panel').hidden);assert.ok(t.d.querySelector('[data-a=welcomeStart]'));assert.match(t.d.body.textContent,/ファイルから開いています/);assert.deepEqual(t.errors,[])}finally{t.close()}});
test('real DOM clicks complete manufacturing, acceptance, delivery, day close and save resume',()=>{const t=setup();try{t.start();for(const id of ['flour','bread']){t.w.GCApp.go('make/craft');t.click('craftSheet',p=>p.id===id);assert.equal(t.d.getElementById('craft-n').value,'3');t.click('craftExecute');if(t.d.getElementById('sheet').open)t.click('close')}t.w.GCApp.go('trade/orders');t.click('acceptSheet',p=>p.id===t.w.GCApp.state.candidates[0].id);t.click('do',p=>p.type==='accept');if(t.d.getElementById('sheet').open)t.click('close');t.click('do',p=>p.type==='deliver');assert.equal(t.w.GCApp.state.stats.delivered,1);t.click('close');t.click('dayPreview');t.click('endDay');assert.equal(t.w.GCApp.state.day,2);assert.deepEqual(t.errors,[]);const next=setup({data:t.data});try{assert.equal(next.w.GCApp.state.day,2);assert.equal(next.w.GCApp.state.stats.delivered,1);assert.deepEqual(next.errors,[])}finally{next.close()}}finally{t.close()}});
test('all 23 routes render in actual DOM and expose only registered handlers',()=>{const t=setup();try{const env=S.parse(fs.readFileSync(path.join(__dirname,'advanced-test-save.json'),'utf8'));t.w.GCApp.loadForTest(env.runs[env.current]);for(const route of routes){t.w.GCApp.go(route);for(const el of t.d.querySelectorAll('[data-a]'))assert.ok(t.w.GCApp.handlers.includes(el.dataset.a),route+':'+el.dataset.a);assert.ok(!t.d.getElementById('main').textContent.includes('undefined'),route)}assert.deepEqual(t.errors,[])}finally{t.close()}});
test('content URI with denied localStorage and unavailable audio can still play temporarily',()=>{const t=setup({url:'content://media/external/file/42',denied:true,audioFail:true});try{t.start();t.w.GCApp.go('make/craft');t.click('craftSheet',p=>p.id==='flour');t.click('craftExecute');assert.equal(t.w.GCApp.state.used.craft,1);assert.match(t.d.getElementById('header').textContent,/一時プレイ/);assert.deepEqual(t.errors,[])}finally{t.close()}});
test('pasted backup imports from denied-storage welcome without requiring a prior new game',()=>{const t=setup({denied:true});try{const state=E.newGame('PASTE');state.name='復元できた会社';t.click('import');t.d.getElementById('import-text').value=JSON.stringify(S.envelope(state));t.click('importText');t.click('importConfirm');assert.equal(t.w.GCApp.state.name,state.name);assert.match(t.d.getElementById('save-warning').textContent,/一時プレイ/);assert.deepEqual(t.errors,[])}finally{t.close()}});
test('temporary backup export uses portable JSON and does not claim an unconfirmed file save',()=>{const t=setup({denied:true});try{t.start();t.w.GCApp.go('more/settings');t.click('export');const text=t.d.getElementById('export-text').value;assert.equal(S.parse(text).runs[t.w.GCApp.state.runId].name,'スマホ検証食品');assert.ok(!t.d.querySelector('[data-a=exportShare]'));t.click('exportDownload');assert.match(t.d.getElementById('toast').textContent,/文字コピー/);assert.deepEqual(t.errors,[])}finally{t.close()}});
test('write failure is visible, settings never falsely report saved, temporary continuation remains usable',()=>{const t=setup();try{t.start();t.flags.failWrite=true;t.w.GCApp.go('more/settings');t.d.getElementById('bgm').value='20';t.click('settingsSave');assert.match(t.d.getElementById('toast').textContent,/保存はできていません/);assert.match(t.d.getElementById('save-warning').textContent,/保存できません/);t.click('temporaryContinue');t.w.GCApp.go('make/craft');t.click('craftSheet',p=>p.id==='flour');t.click('craftExecute');assert.equal(t.w.GCApp.state.used.craft,1);assert.deepEqual(t.errors,[])}finally{t.close()}});
test('invalid procurement quantities are blocked and overflow requires the live checkbox',()=>{const t=setup();try{t.start();const state=E.newGame('OVERFLOW');state.lots=[];E.addLot(state,'wheat',E.capacity(state)-2,0,0,12);t.w.GCApp.loadForTest(state);t.w.GCApp.go('make/buy');t.click('buySheet',p=>p.id==='milk');const n=t.d.getElementById('buy-n');n.value='-5';n.dispatchEvent(new t.w.Event('input',{bubbles:true}));assert.ok(t.d.querySelector('[data-a=buyExecute]').disabled);assert.ok(!t.d.getElementById('buy-preview').textContent.includes('-5円'));n.value='5';n.dispatchEvent(new t.w.Event('input',{bubbles:true}));assert.ok(t.d.querySelector('[data-a=buyExecute]').disabled);t.d.getElementById('buy-overflow').click();assert.ok(!t.d.querySelector('[data-a=buyExecute]').disabled);t.click('buyExecute');assert.equal(E.qty(t.w.GCApp.state,'milk'),2);assert.equal(t.w.GCApp.state.stats.waste,3);assert.deepEqual(t.errors,[])}finally{t.close()}});
test('failed actions preserve the open input sheet and consume nothing',()=>{const t=setup();try{t.start();t.w.GCApp.go('make/produce');t.click('produceSheet',p=>p.id==='wheat');const before=JSON.stringify(t.w.GCApp.state);t.d.getElementById('produce-n').value='-1';t.d.getElementById('produce-n').dispatchEvent(new t.w.Event('input',{bubbles:true}));assert.ok(t.d.querySelector('[data-a=produceExecute]').disabled);t.d.querySelector('[data-a=produceExecute]').click();assert.equal(JSON.stringify(t.w.GCApp.state),before);assert.ok(t.d.getElementById('sheet').open);assert.equal(t.d.getElementById('produce-n').value,'-1');assert.deepEqual(t.errors,[])}finally{t.close()}});
test('delayed native dialog close event does not close the next input dialog',async()=>{const t=setup({nativeDialog:true});try{t.start();t.w.GCApp.go('make/craft');t.click('craftSheet',p=>p.id==='flour');await new Promise(r=>setTimeout(r,10));assert.ok(t.d.getElementById('sheet').open);assert.ok(t.d.body.classList.contains('modal-open'));assert.match(t.d.getElementById('sheet-title').textContent,/製造計画/);assert.deepEqual(t.errors,[])}finally{t.close()}});
test('v53 saved envelope resumes in v54 using the same storage key',()=>{const state=E.newGame('V53');state.contentVersion='53.0';state.name='v53から継続';const t=setup({data:{[S.KEY]:JSON.stringify(S.envelope(state))}});try{assert.equal(t.w.GCApp.state.runId,state.runId);assert.equal(t.w.GCApp.state.name,state.name);assert.match(t.d.title,/ごちそう/);assert.deepEqual(t.errors,[])}finally{t.close()}});
test('imported staff names remain literal text in dialog titles',()=>{const t=setup();try{const state=E.newGame('TITLE');state.staff[0].name='<img src=x onerror=alert(1)> & 仲間';t.w.GCApp.loadForTest(state);t.w.GCApp.go('grow/staff');t.click('assignSheet');assert.equal(t.d.getElementById('sheet-title').textContent,state.staff[0].name+'の配置');assert.equal(t.d.getElementById('sheet-title').querySelectorAll('img,script').length,0);assert.deepEqual(t.errors,[])}finally{t.close()}});
test('batch preparation DOM carries the contract and delivers once without menu hopping',()=>{const t=setup();try{t.start();t.w.GCApp.go('trade/orders');t.click('acceptSheet',p=>p.id===t.w.GCApp.state.candidates[0].id);t.click('do',p=>p.type==='accept');const id=t.w.GCApp.state.orders[0].id;t.click('planSheet',p=>p.id===id);assert.match(t.d.getElementById('sheet-body').textContent,/まとめて準備/);assert.ok(t.d.getElementById('bundle-deliver').checked);const button=t.click('bundleExecute');assert.equal(t.w.GCApp.state.stats.delivered,1);assert.equal(t.w.GCApp.state.used.craft,2);button.click();assert.equal(t.w.GCApp.state.stats.delivered,1);assert.equal(t.d.getElementById('sheet').open,false);assert.deepEqual(t.errors,[])}finally{t.close()}});
test('work plan form persists, executes at close, and shares daily budget after resume',()=>{const t=setup();try{let s=E.newGame('WORK-DOM');s=E.transact(s,'accept',{id:s.candidates[0].id}).state;t.w.GCApp.loadForTest(s);t.w.GCApp.go('make/plan');t.d.getElementById('work-enabled').checked=true;t.d.getElementById('work-keep').value='0';t.d.getElementById('work-budget').value='300';t.click('workSave');assert.equal(t.w.GCApp.state.workPlan.budget,300);assert.ok(t.w.GCApp.state.workPlan.enabled);t.click('dayPreview');assert.match(t.d.getElementById('sheet-body').textContent,/閉店すると進むこと/);t.click('endDay');assert.equal(t.w.GCApp.state.day,2);assert.equal(t.w.GCApp.state.stats.delivered,1);assert.equal(t.w.GCApp.state.lastReport.delegation.craft,2);const next=setup({data:t.data});try{assert.ok(next.w.GCApp.state.workPlan.enabled);assert.equal(next.w.GCApp.state.workPlanUsage.spent,90)}finally{next.close()}assert.deepEqual(t.errors,[])}finally{t.close()}});
test('neutral original recipe shows live ingredient corrections and preserves tasting in history',()=>{const t=setup();try{const s=E.newGame('FLAVOR-DOM');s.day=6;s.lots=[];E.addLot(s,'wheat',4);E.addLot(s,'vegetable',4);t.w.GCApp.loadForTest(s);t.w.GCApp.go('make/original');t.d.getElementById('draft-name').value='若葉のごちそう';t.d.getElementById('draft-main').value='wheat';for(const el of t.d.querySelectorAll('[data-ingredient]'))el.value='0';for(const id of ['wheat','vegetable'])t.d.getElementById('ing-'+id).value='1';t.d.getElementById('draft-name').dispatchEvent(new t.w.Event('input',{bubbles:true}));assert.match(t.d.getElementById('draft-preview').textContent,/合計 0/);assert.match(t.d.getElementById('draft-preview').textContent,/−8〜＋8/);const rng=t.w.GCApp.state.rng;t.click('prototypeSheet');assert.match(t.d.getElementById('sheet-body').textContent,/補正を含む確率/);assert.equal(t.w.GCApp.state.rng,rng);t.click('prototypeExecute');assert.match(t.d.getElementById('sheet-body').textContent,/抽選.*相性.*偶然/);t.click('close');t.click('recipeHistory');assert.match(t.d.getElementById('sheet-body').textContent,/前回の試食/);assert.deepEqual(t.errors,[])}finally{t.close()}});
test('ordinary repeat deliveries use a toast; first delivery still has its milestone sheet',()=>{const t=setup();try{let s=E.newGame('QUIET');s.stats.delivered=1;const o=E.order(s,'wheat',2,0,'sakura');s.orders.push({...o,dueDay:3,acceptedDay:1});t.w.GCApp.loadForTest(s);t.w.GCApp.go('trade/orders');t.click('do',p=>p.type==='deliver');assert.equal(t.w.GCApp.state.stats.delivered,2);assert.equal(t.d.getElementById('sheet').open,false);assert.match(t.d.getElementById('toast').textContent,/ありがとう/);assert.deepEqual(t.errors,[])}finally{t.close()}});
test('closing dialog distinguishes executable work, optional growth and planned staff work',()=>{const t=setup();try{t.start();assert.match(t.d.getElementById('daybar').textContent,/対応できる候補/);t.click('dayPreview');const sheet=t.d.getElementById('sheet');assert.ok(sheet.classList.contains('closing-dialog'));assert.match(sheet.textContent,/今日できること/);assert.match(sheet.textContent,/任意の成長/);assert.match(sheet.textContent,/余力は使い切らなくて大丈夫/);assert.match(sheet.textContent,/閉店すると進むこと/);assert.equal(t.w.GCApp.state.day,1);assert.deepEqual(t.errors,[])}finally{t.close()}});
test('preset is enabled in one click with advanced controls kept collapsed',()=>{const t=setup();try{t.start();t.w.GCApp.go('make/plan');assert.equal(t.d.querySelector('.work-details').open,false);t.click('do',p=>p.type==='workPreset'&&p.p.mode==='orders');assert.equal(t.w.GCApp.state.workPlan.enabled,true);assert.equal(t.w.GCApp.state.workPlan.keepCraft,0);assert.equal(t.w.GCApp.state.dailyCrop,'off');assert.match(t.d.querySelector('.preset-card.selected').textContent,/注文を全部任せる/);const next=setup({data:t.data});try{assert.equal(next.w.GCApp.state.workPlan.keepCraft,0);assert.equal(next.w.GCApp.state.dailyCrop,'off')}finally{next.close()}assert.deepEqual(t.errors,[])}finally{t.close()}});
test('candidate card completes accept, materials, processing and delivery in one click',()=>{const t=setup();try{t.start();t.w.GCApp.go('trade/orders');const id=t.w.GCApp.state.candidates[0].id;const button=t.click('do',p=>p.type==='acceptAndDeliver'&&p.p.id===id);assert.equal(t.w.GCApp.state.stats.delivered,1);assert.equal(t.w.GCApp.state.used.craft,2);assert.equal(t.w.GCApp.state.orders.length,0);assert.equal(t.d.getElementById('sheet').open,false);button.click();assert.equal(t.w.GCApp.state.stats.delivered,1);assert.deepEqual(t.errors,[])}finally{t.close()}});
test('routine closing returns directly to home while detailed daily reports remain optional',()=>{const t=setup();try{t.start();t.click('dayPreview');t.click('endDay');assert.equal(t.w.GCApp.state.day,2);assert.equal(t.d.getElementById('sheet').open,false);assert.match(t.d.getElementById('toast').textContent,/営業完了/);assert.ok(t.d.querySelector('[data-a=report]'));t.w.GCApp.go('more/settings');t.d.getElementById('full-report').checked=true;t.click('settingsSave');t.click('dayPreview');t.click('endDay');assert.ok(t.d.getElementById('sheet').open);assert.match(t.d.getElementById('sheet-title').textContent,/おつかれさま/);const next=setup({data:t.data});try{assert.equal(next.w.GCApp.state.settings.fullReport,true)}finally{next.close()}assert.deepEqual(t.errors,[])}finally{t.close()}});
test('unfulfilled automatic order warns at close and never says it is safe to skip',()=>{const t=setup();try{const s=E.newGame('DANGER');s.lots=[];s.money=0;s.dailyCrop='off';s.used.accept=3;const o=E.order(s,'bread',3,4,'sakura');s.orders.push({...o,dueDay:1,acceptedDay:1,auto:true});t.w.GCApp.loadForTest(s);t.click('dayPreview');const text=t.d.getElementById('sheet-body').textContent;assert.match(text,/このまま閉店すると未納品/);assert.ok(!text.includes('次の日へ進めても大丈夫'));t.click('endDay');assert.equal(t.w.GCApp.state.stats.failed,1);assert.ok(t.d.getElementById('sheet').open);assert.match(t.d.getElementById('sheet-title').textContent,/おつかれさま/);assert.deepEqual(t.errors,[])}finally{t.close()}});
test('closing forecast displays automatic delivery without a false expiring-inventory warning',()=>{const t=setup();try{const s=E.newGame('CLOSING');s.dailyCrop='off';s.lots=[];const o=E.order(s,'bread',3,0,'sakura');s.orders.push({...o,dueDay:1,acceptedDay:1,auto:true});E.addLot(s,'bread',3,0,0,20,{expiresAfterDay:1});t.w.GCApp.loadForTest(s);t.click('dayPreview');const text=t.d.getElementById('sheet-body').textContent;assert.match(text,/スタッフが 1件お届け/);assert.ok(!text.includes('3個が閉店時に廃棄'));assert.match(t.d.querySelector('[data-a=endDay]').textContent,/任せて/);assert.deepEqual(t.errors,[])}finally{t.close()}});
test('cash recovery is discoverable from home with no money and no work frames',()=>{const t=setup();try{const s=E.newGame('CASH-DOM');s.money=0;s.lots=[];s.used.craft=E.craftLimit(s);t.w.GCApp.loadForTest(s);assert.match(t.d.getElementById('main').textContent,/再建支援/);t.click('go',p=>p.to==='trade/finance');t.click('aidSheet');assert.match(t.d.getElementById('sheet-body').textContent,/返済不要/);t.click('do',p=>p.type==='recoveryAid');assert.equal(t.w.GCApp.state.money,1000);assert.equal(t.w.GCApp.state.finance.reliefUntil,3);assert.deepEqual(t.errors,[])}finally{t.close()}});
test('bulk commission validates count and retains input on a failed stale action',()=>{const t=setup();try{const s=E.newGame('WORK-CASH');s.money=0;s.lots=[];t.w.GCApp.loadForTest(s);t.w.GCApp.go('trade/finance');let n=t.d.getElementById('contract-n');n.value='-2';n.dispatchEvent(new t.w.Event('input',{bubbles:true}));assert.ok(t.d.querySelector('[data-a=contractExecute]').disabled);n.value='3';n.dispatchEvent(new t.w.Event('input',{bubbles:true}));assert.match(t.d.getElementById('contract-preview').textContent,/660円/);t.click('contractExecute');assert.equal(t.w.GCApp.state.money,660);assert.equal(t.w.GCApp.state.used.craft,3);assert.deepEqual(t.errors,[])}finally{t.close()}});
test('recruitment starts with no fixed candidates and shows cost, odds and replacement before payment',()=>{const t=setup();try{t.start();t.w.GCApp.go('grow/recruit');assert.equal(t.d.querySelectorAll('.applicant-card').length,0);assert.match(t.d.getElementById('main').textContent,/まだ応募者はいません/);t.d.getElementById('recruit-focus').value='lab';t.click('recruitSheet',p=>p.campaign==='listing');assert.match(t.d.getElementById('sheet-body').textContent,/1,200円/);assert.match(t.d.getElementById('sheet-body').textContent,/1人目はレア以上/);const before=t.w.GCApp.state.money,button=t.click('do',p=>p.type==='recruit');assert.equal(t.w.GCApp.state.money,before-1200);assert.equal(t.d.querySelectorAll('.applicant-card').length,3);assert.ok(t.w.GCApp.state.recruitment.candidates.every(t=>t.assigned==='lab'));button.click();assert.equal(t.w.GCApp.state.money,before-1200);assert.deepEqual(t.errors,[])}finally{t.close()}});
test('applicant profile shows all stats and hiring impact, then adopts exactly the revealed person',()=>{const t=setup();try{let s=E.newGame('HIRE-DOM');s=E.transact(s,'recruit',{campaign:'flyer',focus:'workshop'}).state;t.w.GCApp.loadForTest(s);t.w.GCApp.go('grow/recruit');const first=s.recruitment.candidates[0];t.click('talentSheet',p=>p.id===first.id);const body=t.d.getElementById('sheet-body');for(const x of ['農家','職人','営業','研究員','物流','日次費用＋10円','採用時の費用0円'])assert.ok(body.textContent.includes(x),x);assert.equal(body.querySelectorAll('.talent-stats>div').length,5);const money=t.w.GCApp.state.money;t.click('do',p=>p.type==='hire');assert.equal(t.w.GCApp.state.money,money);assert.equal(t.w.GCApp.state.staff[1].name,first.name);assert.deepEqual(JSON.parse(JSON.stringify(t.w.GCApp.state.staff[1].stats)),first.stats);t.click('close');t.w.GCApp.go('grow/staff');t.click('talentSheet',p=>p.id===first.id);assert.match(t.d.getElementById('sheet-title').textContent,/プロフィール/);assert.deepEqual(t.errors,[])}finally{t.close()}});
test('applicants and portraits survive save resume without a fresh roll',()=>{const t=setup();try{t.start();t.w.GCApp.go('grow/recruit');t.click('recruitSheet',p=>p.campaign==='flyer');t.click('do',p=>p.type==='recruit');const original=JSON.stringify(t.w.GCApp.state.recruitment),next=setup({data:t.data});try{assert.equal(JSON.stringify(next.w.GCApp.state.recruitment),original);next.w.GCApp.go('grow/recruit');assert.equal(next.d.querySelectorAll('.applicant-card').length,2);assert.deepEqual(next.errors,[])}finally{next.close()}assert.deepEqual(t.errors,[])}finally{t.close()}});
test('automatic cash recovery setting persists and closing preview discloses exact work income',()=>{const t=setup();try{const s=E.newGame('AUTO-MONEY');s.money=0;s.dailyCrop='off';t.w.GCApp.loadForTest(s);t.w.GCApp.go('trade/finance');t.d.getElementById('finance-auto').checked=true;t.d.getElementById('finance-target').value='1200';t.click('financeSave');t.click('dayPreview');assert.match(t.d.getElementById('sheet-body').textContent,/資金のお手伝い：5枠/);assert.match(t.d.getElementById('sheet-body').textContent,/1,100円/);t.click('endDay');assert.equal(t.w.GCApp.state.money,1070);assert.equal(t.w.GCApp.state.finance.autoWork,true);assert.deepEqual(t.errors,[])}finally{t.close()}});
test('buyback quantity changes show exact revenue and do not use protected lots',()=>{const t=setup();try{const s=E.newGame('SELL-DOM');s.lots=[];const free=E.addLot(s,'wheat',5,0,0,12);const locked=E.addLot(s,'milk',5,0,0,60,{locked:true});t.w.GCApp.loadForTest(s);t.w.GCApp.go('trade/finance');assert.equal(t.d.getElementById('sale-lot').options.length,1);assert.equal(t.d.getElementById('sale-lot').value,free.lotId);t.d.getElementById('sale-n').value='3';t.d.getElementById('sale-n').dispatchEvent(new t.w.Event('input',{bubbles:true}));assert.match(t.d.getElementById('sale-preview').textContent,/21円/);t.click('saleExecute');assert.equal(t.w.GCApp.state.money,6021);assert.equal(t.w.GCApp.state.lots.find(l=>l.lotId===locked.lotId).quantity,5);assert.deepEqual(t.errors,[])}finally{t.close()}});
test('imported applicant text remains literal and reduced-motion mode still exposes recruitment outcome',()=>{const t=setup();try{let s=E.newGame('HIRE-XSS');s.settings.reduced=true;s=E.transact(s,'recruit',{campaign:'flyer'}).state;s.recruitment.candidates[0].name='<img src=x onerror=alert(1)>';t.w.GCApp.loadForTest(s);t.w.GCApp.go('grow/recruit');assert.ok(!t.d.getElementById('main').querySelector('img'));assert.ok(t.d.body.classList.contains('reduced'));t.click('talentSheet',p=>p.id===s.recruitment.candidates[0].id);assert.ok(!t.d.getElementById('sheet-body').querySelector('img'));assert.match(t.d.getElementById('sheet-title').textContent,/<img/);assert.deepEqual(t.errors,[])}finally{t.close()}});

test('v58 order card explains exact first step and carries procurement quantity into the next dialog',()=>{const t=setup();try{const s=E.newGame('NEXT');s.day=21;s.research.recipe=3;s.lots=[];E.addLot(s,'vegetable',4,0,0,15);s.candidates=[E.order(s,'bento',2,2,'makoto')];t.w.GCApp.loadForTest(s);t.w.GCApp.go('trade/orders');assert.match(t.d.getElementById('main').textContent,/まず肉を5個仕入れる/);assert.ok(!t.d.getElementById('main').textContent.includes('製造と品質条件の確認が必要'));t.click('guidePrepare',p=>p.id==='meat');assert.equal(t.d.getElementById('buy-n').value,'5');t.click('buyExecute');assert.match(t.d.getElementById('main').textContent,/次はおうちの惣菜を2個加工/);t.click('guidePrepare',p=>p.id==='deli');assert.equal(t.d.getElementById('craft-n').value,'2');assert.match(t.d.getElementById('craft-preview').textContent,/要求品質 E/);t.click('craftExecute');if(t.d.getElementById('sheet').open)t.click('close');assert.match(t.d.getElementById('main').textContent,/まんぷく弁当 C以上は/);assert.deepEqual(t.errors,[])}finally{t.close()}});
test('v58 quality guide can standardize the named product and then exposes the guaranteed shortcut',()=>{const t=setup();try{const s=E.newGame('STANDARD');s.day=21;s.research.recipe=3;s.rp=83;s.lots=[];E.addLot(s,'deli',2,0,0,185);E.addLot(s,'vegetable',2,0,0,15);s.candidates=[E.order(s,'bento',2,2,'makoto')];t.w.GCApp.loadForTest(s);t.w.GCApp.go('trade/orders');t.click('guideStandard',p=>p.id==='bento');assert.match(t.d.getElementById('sheet-body').textContent,/45.*83/);t.click('do',p=>p.type==='standardize');assert.equal(t.w.GCApp.state.guarantees.bento,2);assert.match(t.d.getElementById('sheet-body').textContent,/まんぷく弁当の製法を標準化/);t.click('close');assert.match(t.d.getElementById('main').textContent,/受けて、作って、お届け/);assert.deepEqual(t.errors,[])}finally{t.close()}});
test('v58 material ceiling, recipe unlocking and disabled contract limits are all stated visibly',()=>{const t=setup();try{let s=E.newGame('GUIDE');s.candidates=[E.order(s,'bento',2,3,'makoto')];t.w.GCApp.loadForTest(s);t.w.GCApp.go('trade/orders');t.click('guideResearch');assert.match(t.d.getElementById('sheet-body').textContent,/レシピ研究.*25/);t.click('close');s.day=21;s.research.recipe=3;s.lots=[];E.addLot(s,'deli',2,2,0,185);E.addLot(s,'vegetable',2,0,0,15);s.used.accept=3;t.w.GCApp.loadForTest(s);t.w.GCApp.go('trade/orders');assert.match(t.d.getElementById('main').textContent,/今日は新規受注3件の上限/);assert.ok(t.d.querySelector('[data-a=acceptSheet]').disabled);t.click('guideMaterials');assert.match(t.d.getElementById('sheet-body').textContent,/加重平均が1以上必要/);assert.ok(t.d.querySelector('[data-a=supplierSheet]'));assert.deepEqual(t.errors,[])}finally{t.close()}});
test('v58 quality rework opens the exact lot with the necessary quantity selected',()=>{const t=setup();try{const s=E.newGame('REWORK');s.day=21;s.research.recipe=3;s.rp=100;s.lots=[];E.addLot(s,'bento',2,1,1,255);s.candidates=[E.order(s,'bento',2,2,'makoto')];t.w.GCApp.loadForTest(s);t.w.GCApp.go('trade/orders');t.click('guideImprove');assert.equal(t.d.getElementById('improve-n').value,'2');assert.match(t.d.getElementById('improve-cost').textContent,/100/);t.click('improveExecute');assert.equal(t.w.GCApp.state.lots[0].qualityRank,2);assert.deepEqual(t.errors,[])}finally{t.close()}});
test('v58 dining complete flow uses two samples, shows score feedback, saves album and restores it',()=>{const t=setup();try{const s=E.newGame('MENU');s.day=6;s.lots=[];s.settings.reduced=true;s.settings.short=true;E.addLot(s,'bread',1,0,0,54);E.addLot(s,'salad',1,0,0,50);t.w.GCApp.loadForTest(s);t.click('diningSheet');t.click('diningSelect',p=>p.id==='picnic');t.click('diningBegin',p=>p.option===0);assert.match(t.d.getElementById('dining-preview').textContent,/88 \/ 100/);assert.match(t.d.getElementById('dining-preview').textContent,/用途 60\/60/);t.d.getElementById('dining-service').value='table';t.d.getElementById('dining-service').dispatchEvent(new t.w.Event('change',{bubbles:true}));assert.match(t.d.getElementById('dining-preview').textContent,/74 \/ 100/);t.click('diningServe');assert.equal(t.w.GCApp.state.dining.album[0].score,74);assert.equal(t.w.GCApp.state.lots.length,0);assert.match(t.d.getElementById('sheet-body').textContent,/りくとくん/);assert.equal(t.d.getElementById('celebrate').children.length,0);const next=setup({data:t.data});try{assert.equal(next.w.GCApp.state.dining.album[0].score,74);assert.deepEqual(next.errors,[])}finally{next.close()}assert.deepEqual(t.errors,[])}finally{t.close()}});
test('v58 menu preparation has an atomic materials-to-dish button and returns directly to the menu',()=>{const t=setup();try{const s=E.newGame('EASY-MENU');s.day=6;s.lots=[];t.w.GCApp.loadForTest(s);t.click('diningSheet');t.click('diningSelect',p=>p.id==='picnic');t.click('diningBegin',p=>p.option===0);assert.ok(t.d.querySelector('[data-a=diningServe]').disabled);t.click('dishGuide',p=>p.id==='bread');assert.match(t.d.getElementById('sheet-body').textContent,/材料からまとめて用意する/);t.click('diningPrepare');assert.ok(t.d.getElementById('dining-lot-0'));assert.equal(E.qty(t.w.GCApp.state,'bread'),1);t.click('dishGuide',p=>p.id==='salad');t.click('diningPrepare');assert.ok(!t.d.querySelector('[data-a=diningServe]').disabled);assert.equal(E.qty(t.w.GCApp.state,'salad'),1);assert.deepEqual(t.errors,[])}finally{t.close()}});
test('v58 menu never renders imported food names as markup or draws reward from opening a sheet',()=>{const t=setup();try{let s=E.newGame('ESCAPE-MENU');s.day=6;s=E.transact(s,'diningStart',{id:'picnic',option:0}).state;s.recipes.push({id:'original:menu',name:'<img src=x onerror=alert(1)>',kind:'food',recipe:{wheat:2},weights:{wheat:1},recipeVersion:1,tags:['携帯'],formal:false});s.lots=[];E.addLot(s,'original:menu',1,0,0,30);E.addLot(s,'salad',1,0,0,50);const before=JSON.stringify(s);t.w.GCApp.loadForTest(s);t.click('diningSheet');assert.equal(t.d.getElementById('dining-preview').querySelectorAll('img').length,0);assert.ok(t.d.getElementById('dining-preview').textContent.includes('<img'));assert.equal(JSON.stringify(t.w.GCApp.state),before);assert.deepEqual(t.errors,[])}finally{t.close()}});
test('v58 a one-unit harvest deficit stays one unit, and invalid production never shows negative spend',()=>{const t=setup();try{const s=E.newGame('ONE-UNIT');s.lots=[];s.candidates=[E.order(s,'wheat',1,1,'sakura')];s.materialRanks.wheat=1;s.used.accept=3;t.w.GCApp.loadForTest(s);t.w.GCApp.go('trade/orders');t.click('guidePrepare');assert.equal(t.d.getElementById('produce-n').value,'1');const field=t.d.getElementById('produce-n');field.value='-1';field.dispatchEvent(new t.w.Event('input',{bubbles:true}));assert.ok(t.d.querySelector('[data-a=produceExecute]').disabled);assert.ok(!t.d.getElementById('produce-preview').textContent.includes('-12円'));field.value='1';field.dispatchEvent(new t.w.Event('input',{bubbles:true}));t.click('produceExecute');assert.equal(E.qty(t.w.GCApp.state,'wheat'),1);assert.deepEqual(t.errors,[])}finally{t.close()}});
test('v58 ready stock with an exhausted acceptance limit does not offer an enabled accept shortcut',()=>{const t=setup();try{const s=E.newGame('LIMIT');s.lots=[];E.addLot(s,'bread',3,0,0,54);s.candidates=[E.order(s,'bread',3,0,'sakura')];s.used.accept=3;t.w.GCApp.loadForTest(s);t.w.GCApp.go('trade/orders');assert.equal([...t.d.querySelectorAll('[data-a=acceptSheet]')].filter(b=>!b.disabled).length,0);assert.match(t.d.getElementById('main').textContent,/今日の残りと閉店予定を見る/);assert.deepEqual(t.errors,[])}finally{t.close()}});
test('v58 improvement input explains RP shortage before execution, without misleading negative cost',()=>{const t=setup();try{const s=E.newGame('REWORK-COST');s.lots=[];E.addLot(s,'bread',2,1,1,54);s.rp=50;s.candidates=[E.order(s,'bread',2,2,'sakura')];t.w.GCApp.loadForTest(s);t.w.GCApp.go('trade/orders');t.click('guideImprove');assert.ok(t.d.querySelector('[data-a=improveExecute]').disabled);assert.match(t.d.getElementById('improve-cost').textContent,/研究Pが50不足/);const n=t.d.getElementById('improve-n');n.value='1';n.dispatchEvent(new t.w.Event('input',{bubbles:true}));assert.ok(!t.d.querySelector('[data-a=improveExecute]').disabled);assert.deepEqual(t.errors,[])}finally{t.close()}});
test('v58 a B-quality guarantee path shows both standardization stages and their total before spending',()=>{const t=setup();try{const s=E.newGame('B-PATH');s.day=21;s.research.recipe=3;s.rp=120;s.lots=[];E.addLot(s,'deli',1,1,1,185);E.addLot(s,'vegetable',1,1,1,15);s.candidates=[E.order(s,'bento',1,3,'makoto')];t.w.GCApp.loadForTest(s);t.w.GCApp.go('trade/orders');t.click('guideStandard');assert.match(t.d.getElementById('sheet-body').textContent,/要求Bの保証にはあと2段階・合計115P/);t.click('do',p=>p.type==='standardize');t.click('close');t.click('guideStandard');assert.match(t.d.getElementById('sheet-body').textContent,/70.*75/);t.click('do',p=>p.type==='standardize');assert.equal(t.w.GCApp.state.guarantees.bento,3);assert.equal(t.w.GCApp.state.rp,5);assert.deepEqual(t.errors,[])}finally{t.close()}});
