'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const E=require('../actions.js'),S=require('../storage.js');
function act(s,type,p={}){const r=E.transact(s,type,p);assert.ok(r.ok,r.error);return r.state;}
const close=s=>act(s,'nextDay',{day:s.day});
function first(){let s=E.newGame('GUIDED');s=act(s,'accept',{id:s.candidates[0].id});s=act(s,'craft',{id:'flour',n:3});s=act(s,'craft',{id:'bread',n:3});return act(s,'deliver',{id:s.orders[0].id});}
test('the coach completes a first delivery in four transactions with no RNG requirement',()=>{for(const seed of ['GUIDE-A','GUIDE-B','GUIDE-C']){let s=E.newGame(seed),g=E.coach(s);assert.equal(g.action,'acceptSheet');s=act(s,'accept',g.p);g=E.coach(s);assert.equal(g.p.id,'flour');assert.equal(g.p.n,3);s=act(s,'craft',g.p);g=E.coach(s);assert.equal(g.p.id,'bread');assert.equal(g.p.n,3);s=act(s,'craft',g.p);g=E.coach(s);assert.equal(g.action,'do');s=act(s,g.p.type,g.p.p);assert.equal(s.stats.delivered,1);assert.equal(s.progress.units,3);assert.equal(s.day,1);assert.equal(E.coach(s).action,'tutorialWork');assert.equal(s.used.craft,2);assert.equal(s.money,6000-90+s.ledger.sales);}});
test('first delivery through one-click or day-close automation also advances the same tutorial and counters',()=>{for(const mode of ['quick','close']){let s=E.newGame('SHORTCUT');if(mode==='quick')s=act(s,'acceptAndDeliver',{id:s.candidates[0].id});else{s=act(s,'accept',{id:s.candidates[0].id});s=act(s,'workPreset',{mode:'orders'});s=close(s);}assert.equal(s.progress.units,3);assert.equal(s.stats.delivered,1);assert.equal(s.progress.tutorial.step,mode==='close'?5:4);if(mode==='close')assert.equal(s.lastReport.deliveredUnits,3);}});
test('making and wholesale do not increase contract deliveries, split requirements count actual units',()=>{let s=E.newGame('UNITS');s=act(s,'craft',{id:'flour',n:3});s=act(s,'craft',{id:'bread',n:3});assert.equal(s.progress.units,0);const o=E.order(s,'bread',2,0,'sakura',{requirements:[{itemId:'bread',quantity:2},{itemId:'vegetable',quantity:2}],dueDay:3,acceptedDay:1});s.orders=[o];s=act(s,'deliver',{id:o.id});assert.equal(s.progress.units,4);assert.equal(s.stats.delivered,1);assert.match(s.lastResult.sub,/1件・4個/);});
test('skipping and reopening tutorial changes no assets and supports continued companies',()=>{let s=E.newGame('SKIP'),before=E.clone(s);s=act(s,'tutorial',{mode:'skip'});assert.ok(!E.coach(s).tutorial);for(const k of ['money','lots','rng','used','stats'])assert.deepEqual(s[k],before[k]);s=act(s,'tutorial',{mode:'resume'});assert.ok(E.coach(s).tutorial);s=first();s=act(s,'tutorial',{mode:'finish'});assert.ok(!E.coach(s).tutorial);s=act(s,'tutorial',{mode:'resume'});assert.equal(E.coach(s).action,'tutorialWork');});
test('delegation coach points to close preview when the real plan will deliver',()=>{let s=first();s=act(s,'workPreset',{mode:'orders'});s=act(s,'accept',{id:s.candidates.find(o=>o.itemId==='salad').id});assert.equal(E.coach(s).action,'dayPreview');const f=E.closingForecast(s);assert.ok(f.scheduledIds.includes(s.orders[0].id));s=close(s);assert.equal(s.stats.delivered,2);assert.equal(s.progress.units,5);});
test('sales research raises new acceptance limit gradually and the same limit is enforced',()=>{for(let research=0;research<=6;research++){let s=E.newGame('LIMIT');s.research.sales=research;s.used.accept=E.acceptLimit(s)-1;assert.equal(E.acceptLimit(s),research<3?3:research<6?4:5);s=act(s,'accept',{id:s.candidates[0].id});const blocked=E.transact(s,'accept',{id:s.candidates[0].id});assert.ok(!blocked.ok);assert.match(blocked.error,new RegExp('1日'+E.acceptLimit(s)+'件'));assert.match(E.orderGuidance(s,s.candidates[0]).acceptBlock,/新規受注/);}});
test('growth preview is exact and does not restore consumed action slots',()=>{let s=E.newGame('GROW');s.rp=100;s.used.craft=3;let g=E.deliveryGrowth(s).find(g=>g.p.id==='processing');assert.match(g.text,/3 → 4個/);assert.equal(g.cost,22);s=act(s,'research',g.p);assert.equal(E.batch(s),4);assert.equal(s.used.craft,3);g=E.deliveryGrowth(s).find(g=>g.p.id==='workshop');assert.match(g.text,/5 → 6枠/);s=act(s,'facility',g.p);assert.equal(E.craftLimit(s),6);assert.equal(s.used.craft,3);});
test('letters arrive at a defined milestone and persist until answered, without overwriting contracts',()=>{let s=first();s=close(close(s));assert.equal(s.day,3);assert.equal(s.event.story,'regular');const event=E.clone(s.event),rep=s.reputation;s=close(close(s));assert.deepEqual(s.event,event);assert.equal(s.reputation,rep);assert.equal(s.progress.seen.filter(x=>x==='regular').length,1);const copy=S.parse(JSON.stringify(s)).runs[s.runId];assert.deepEqual(copy.event,event);});
test('invitation preview matches contract terms, has four inclusive days and protects accepted contracts',()=>{let s=first();s=close(close(s));s=act(s,'accept',{id:s.candidates[0].id});const existing=E.clone(s.orders),preview=E.storyInvitation(s),rng=s.rng;s=act(s,'storyChoice',{choice:'offer'});assert.equal(s.rng,rng);assert.deepEqual(s.orders,existing);const candidate=s.candidates[0];assert.equal(candidate.storyId,'regular');assert.equal(E.quoteReward(s,candidate),preview.reward);const day=s.day;s=act(s,'accept',{id:candidate.id});const contract=s.orders.find(o=>o.id===candidate.id);assert.equal(contract.dueDay,day+3);assert.equal(contract.reward,preview.reward);});
test('learning reward and letter history cannot be repeated through double taps or reloading',()=>{let s=first();s=close(close(s));const before=s.rp,token=s.transactionSeq+1,r=E.transact(s,'storyChoice',{choice:'learn'},token);assert.ok(r.ok);s=r.state;assert.equal(s.rp,before+12);assert.equal(s.progress.focus,'delivery');assert.ok(!E.transact(s,'storyChoice',{choice:'learn'},token).ok);assert.ok(!E.transact(s,'storyChoice',{choice:'learn'}).ok);s=S.parse(JSON.stringify(s)).runs[s.runId];s=close(s);assert.notEqual(s.event?.story,'regular');});
test('all letters support both choices and unavailable recipes use a disclosed basic substitute',()=>{for(const chapter of E.chapters){for(const choice of ['offer','learn']){let s=E.newGame('LETTERS');s.day=chapter.day;s.progress.seen=E.chapters.filter(c=>c.day<chapter.day).map(c=>c.id);s.event=E.morningEvent(s);const p=E.storyInvitation(s);assert.equal(p.id,chapter.id);assert.ok(E.unlocked(s,p.itemId));assert.equal(p.minQuality,chapter.offer[2]);s=act(s,'storyChoice',{choice});if(choice==='offer')assert.equal(s.candidates[0].itemId,p.itemId);else assert.equal(s.progress.focus,chapter.learn);assert.ok(E.validate(s));}}});
test('forecasts, tutorial, event previews and growth advice never consume RNG or modify state',()=>{let s=first();s=close(close(s));const before=JSON.stringify(s);for(let i=0;i<3;i++){E.coach(s);E.closingForecast(s);E.storyInvitation(s);E.deliveryGrowth(s);E.nextChapter(s);E.todayStatus(s);}assert.equal(JSON.stringify(s),before);});
test('v58 continuation preserves economic state and labels unknown historical unit count',()=>{const input=JSON.parse(fs.readFileSync(__dirname+'/v58-continuation-fixture.json','utf8')),old=input.runs[input.current],saved=E.clone(old),env=S.parse(JSON.stringify(input)),s=env.runs[env.current];assert.equal(saved.gameRulesVersion,'2.3.0');for(const k of ['runId','rng','money','rp','lots','orders','staff','stats','workPlan','initialEvaluation','dining','used'])assert.deepEqual(s[k],saved[k],k);assert.equal(s.progress.units,0);assert.equal(s.progress.unitsFromDay,s.day);assert.equal(s.progress.completeCount,false);assert.equal(s.progress.tutorial.enabled,false);assert.equal(s.gameRulesVersion,E.D.rules);const once=JSON.stringify(s);E.upgrade(s);assert.equal(JSON.stringify(s),once);});
test('invalid progress, duplicate letters and corrupted counters are rejected on import',()=>{for(const change of [s=>s.progress.units=-1,s=>s.progress.units=Infinity,s=>s.progress.tutorial.step=9,s=>s.progress.seen=['regular','regular'],s=>s.progress.focus='unknown',s=>s.event={story:'unknown',arrivedDay:1}]){const s=E.newGame('BAD');change(s);assert.throws(()=>S.parse(JSON.stringify(s)));}});
test('60th day includes delivery units and one-time letters remain bounded in endless play',()=>{let s=first();s.day=60;s.dailyCrop='off';s.lots=[];E.addLot(s,'bread',2);const o=E.order(s,'bread',2,0,'sakura',{dueDay:60,acceptedDay:60});s.orders=[o];s=act(s,'deliver',{id:o.id});s=close(s);assert.equal(s.day,60);assert.ok(s.ended);assert.equal(s.stats.delivered,2);assert.equal(s.progress.units,5);s=act(s,'continue');for(let i=0;i<70;i++){if(s.event?.story)s=act(s,'storyChoice',{choice:'learn'});s=close(s);}assert.equal(s.day,131);assert.equal(s.progress.seen.length,8);assert.equal(new Set(s.progress.seen).size,8);});
test('contest invitation can prepare exactly one sample with ordinary costs and submit separately',()=>{let s=E.newGame('SAMPLE');s.day=12;s.lots=[];const before=s.money,p=E.contestPreparation(s,'breadCup');assert.ok(p.ok,p.reason);assert.equal(p.spent,54);assert.equal(p.craft,2);assert.equal(p.produce,1);s=act(s,'contestPrepare',{key:'breadCup'});assert.equal(E.qty(s,'bread'),1);assert.equal(s.money,before-54);assert.equal(s.contestEntries.length,0);assert.equal(s.progress.units,0);s=act(s,'contest',{key:'breadCup',lot:s.lots.find(l=>l.itemId==='bread').lotId});assert.equal(s.contestEntries.length,1);assert.equal(E.qty(s,'bread'),0);assert.equal(s.money,before-54-200);});
test('contest preparation refuses expired registration and missing formal recipes atomically',()=>{for(const [day,key]of [[15,'breadCup'],[55,'nationalFeast']]){const s=E.newGame('BAD-SAMPLE');s.day=day;const before=JSON.stringify(s),r=E.transact(s,'contestPrepare',{key});assert.ok(!r.ok);assert.equal(JSON.stringify(r.state),before);assert.equal(E.contestPreparation(s,key).ok,false);}});
test('a midday v58 migration labels partial daily unit counts until the next ledger',()=>{let old=E.newGame('MIDDAY');old.gameRulesVersion='2.3.0';old.contentVersion='58.0';delete old.progress;delete old.ledger.deliveredUnits;old.stats.delivered=1;old.ledger.deliveries=1;let s=S.parse(JSON.stringify(old)).runs[old.runId];assert.equal(s.ledger.deliveredUnitsPartial,true);s=act(s,'acceptAndDeliver',{id:s.candidates[0].id});assert.equal(s.ledger.deliveries,2);assert.equal(s.ledger.deliveredUnits,3);s=close(s);assert.ok(s.lastReport.deliveredUnitsPartial);assert.equal(s.lastReport.deliveredUnits,3);assert.equal(s.ledger.deliveredUnits,0);assert.ok(!s.ledger.deliveredUnitsPartial);});
