'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),E=require('../actions.js'),S=require('../storage.js');
const fresh=()=>E.newGame('PEOPLE-57');
function act(s,type,p={},token){const r=E.transact(s,type,p,token);assert.ok(r.ok,type+': '+r.error);return r.state}
function reject(s,type,p={},regex){const before=JSON.stringify(s),r=E.transact(s,type,p);assert.equal(r.ok,false,type);assert.equal(r.state,s);assert.equal(JSON.stringify(s),before);if(regex)assert.match(r.error,regex)}
function close(s){return act(s,'nextDay',{day:s.day})}
test('new company has no applicants until recruitment; day change and all previews do not generate any',()=>{let s=fresh();assert.equal(s.recruitment.candidates.length,0);const before=JSON.stringify(s);E.todayStatus(s);E.recruitPreview(s,'flyer');E.cashStatus(s);assert.equal(JSON.stringify(s),before);s=close(s);assert.equal(s.recruitment.candidates.length,0);assert.equal(s.recruitment.round,0)});
test('all four campaigns pay exactly once, increase counts, respect focus and guarantee first rarity',()=>{const expected=[['flyer',300,2,0],['listing',1200,3,1],['network',3000,4,1],['commercial',6500,6,2]];for(const [campaign,cost,count,min]of expected){let s=fresh();s.money=20000;const oldRng=s.rng;s=act(s,'recruit',{campaign,focus:'lab'});assert.equal(s.money,20000-cost);assert.equal(s.ledger.investment,cost);assert.equal(s.recruitment.candidates.length,count);assert.ok(s.recruitment.candidates.every(t=>t.assigned==='lab'));assert.ok(s.recruitment.candidates[0].rarityIndex>=min);assert.equal(s.rng,oldRng);assert.equal(new Set(s.recruitment.candidates.map(t=>t.name)).size,count);assert.equal(s.companyXP,0)}});
test('displayed base and guarantee distributions match all 10000 discrete probability inputs',()=>{for(const key of Object.keys(E.D.recruitment))for(const slot of [0,1]){const probs=E.recruitmentOdds(key,slot),counts=[0,0,0,0];for(let n=0;n<10000;n++)counts[E.rarityAt((n+.5)/10000,probs)]++;for(let i=0;i<4;i++)assert.ok(Math.abs(counts[i]/10000-probs[i])<=.00011);assert.ok(Math.abs(probs.reduce((a,b)=>a+b,0)-1)<1e-12)}});
test('rarity probability improves monotonically with campaign price for each upper-rarity threshold',()=>{const campaigns=Object.keys(E.D.recruitment);for(let cutoff=1;cutoff<4;cutoff++){let prev=0;for(const key of campaigns){const d=E.D.recruitment[key],first=E.recruitmentOdds(key,0).slice(cutoff).reduce((a,b)=>a+b,0),other=E.recruitmentOdds(key,1).slice(cutoff).reduce((a,b)=>a+b,0),chance=(first+other*(d.count-1))/d.count;assert.ok(chance>=prev);prev=chance}}});
test('same seed and campaign sequence reproduce applicants, while different seeds create different people',()=>{const a=act(fresh(),'recruit',{campaign:'listing'}),b=act(fresh(),'recruit',{campaign:'listing'}),c=act(E.newGame('DIFFERENT'),'recruit',{campaign:'listing'});assert.deepEqual(a.recruitment,b.recruitment);assert.notDeepEqual(a.recruitment.candidates,c.recruitment.candidates);const original=E.clone(a.recruitment);for(let i=0;i<5;i++)E.todayStatus(a);assert.deepEqual(a.recruitment,original)});
test('recruitment cannot reroll that day, on reload, or through a stale double tap',()=>{let s=fresh();const token=s.transactionSeq+1;s=act(s,'recruit',{campaign:'flyer'},token);reject(s,'recruit',{campaign:'listing'},/1営業日1回/);const again=E.transact(s,'recruit',{campaign:'flyer'},token);assert.equal(again.ok,false);const restored=S.parse(JSON.stringify(S.envelope(s))).runs[s.runId];assert.deepEqual(restored.recruitment,s.recruitment);reject(restored,'recruit',{campaign:'flyer'},/1営業日1回/)});
test('unaffordable or invalid campaigns preserve cash, candidate board, id sequence and both RNG streams',()=>{let s=fresh();s.money=299;reject(s,'recruit',{campaign:'flyer'},/募集費/);s.money=20000;reject(s,'recruit',{campaign:'__proto__'});reject(s,'recruit',{campaign:'flyer',focus:'unknown'});reject(s,'hire',{id:'komugi'},/求人募集/)});
test('applicants persist without real or game-day expiry, replacement leaves hired staff intact',()=>{let s=act(fresh(),'recruit',{campaign:'flyer'}),first=E.clone(s.recruitment.candidates);for(let i=0;i<5;i++)s=close(s);assert.deepEqual(s.recruitment.candidates,first);s=act(s,'hire',{id:first[0].id});const hired=E.clone(s.staff.at(-1));s=act(s,'recruit',{campaign:'flyer'});assert.deepEqual(s.staff.at(-1),hired);assert.ok(!s.recruitment.candidates.some(t=>first.some(f=>f.id===t.id)));reject(s,'hire',{id:first[1].id})});
test('hire preserves revealed stats and portrait, charges no additional fee and grants no purchase XP',()=>{let s=act(fresh(),'recruit',{campaign:'listing',focus:'workshop'});const candidate=E.clone(s.recruitment.candidates[0]),money=s.money,xp=s.companyXP,expense=E.operatingCost(s);s=act(s,'hire',{id:candidate.id});const t=s.staff.at(-1);assert.deepEqual(t.stats,candidate.stats);assert.deepEqual(t.appearance,candidate.appearance);assert.equal(t.rarity,candidate.rarity);assert.equal(s.money,money);assert.equal(s.companyXP,xp);assert.equal(E.operatingCost(s),expense+10);reject(s,'hire',{id:candidate.id})});
test('team scenario blocks further hiring and recruitment before expense',()=>{let s=E.newGame('TEAM','team');s=act(s,'recruit',{campaign:'flyer'});s=act(s,'hire',{id:s.recruitment.candidates[0].id});reject(s,'hire',{id:s.recruitment.candidates[0].id},/上限/);s=close(s);reject(s,'recruit',{campaign:'flyer'},/上限/)});
test('recruited talents can be assigned, trained, used and reloaded with their work history',()=>{let s=act(fresh(),'recruit',{campaign:'flyer',focus:'workshop'});const id=s.recruitment.candidates[0].id;s=act(s,'hire',{id});s=act(s,'contractWork',{n:2});assert.equal(s.staff.find(t=>t.id===id).usedDay,1);s=act(s,'assign',{id,role:'lab'});assert.equal(s.staff.find(t=>t.id===id).nextAssignment,'lab');s=act(s,'train',{id});s=close(s);assert.equal(s.staff.find(t=>t.id===id).assigned,'lab');assert.deepEqual(S.parse(JSON.stringify(S.envelope(s))).runs[s.runId],s)});
test('trait-based bread teamwork supports generated ids and retains the old named team',()=>{const s=fresh();const baker=E.makeStaff('komugi');baker.id='talent-test';baker.name='新しい職人';s.staff.push(baker);E.addLot(s,'flour',2);const before=E.craftPlan(s,'bread',1);const after=act(s,'produce',{id:'wheat',n:1});assert.equal(before.q.team,false);assert.equal(E.craftPlan(after,'bread',1).q.team,true)});
test('zero cash, no materials and no spare frames can still receive immediate debt-free support',()=>{let s=fresh();s.money=0;s.lots=[];s.used.craft=E.craftLimit(s);s.used.produce=E.productionLimit(s);const staff=E.clone(s.staff),xp=s.companyXP;s=act(s,'recoveryAid');assert.equal(s.money,1000);assert.equal(E.operatingCost(s),0);assert.equal(s.finance.reliefUntil,3);assert.deepEqual(s.staff,staff);assert.equal(s.companyXP,xp);reject(s,'recoveryAid');s=close(s);assert.equal(s.day,2);assert.equal(s.lastReport.operating,0);assert.ok(s.lastReport.profit<=0);assert.equal(s.used.craft,0);const o=s.candidates.find(o=>E.offerPreview(s,o.id).ok);assert.ok(o);s=act(s,'acceptAndDeliver',{id:o.id});assert.equal(s.stats.delivered,1)});
test('aid threshold and seven-day cooldown are enforced on import and across day close',()=>{let s=fresh();s.money=501;reject(s,'recoveryAid');s.money=500;s=act(s,'recoveryAid');s.dailyCrop='off';for(let i=0;i<6;i++)s=close(s);s.money=0;assert.equal(s.day,7);reject(s,'recoveryAid',{},/8日目/);s=close(s);s=act(s,'recoveryAid');assert.equal(s.money,1000);assert.equal(s.finance.reliefUntil,10);const restored=S.parse(JSON.stringify(S.envelope(s))).runs[s.runId];assert.equal(E.aidPreview(restored).ok,false)});
test('expense relief lasts acquisition day and next two business days only',()=>{let s=fresh();s.money=0;s.dailyCrop='off';s=act(s,'recoveryAid');for(let day=1;day<=3;day++){assert.equal(E.operatingCost(s),0);s=close(s);assert.equal(s.lastReport.operating,0)}assert.equal(s.day,4);assert.equal(E.operatingCost(s),30);s=close(s);assert.equal(s.lastReport.operating,30)});
test('bulk commission work is material-free and has exactly the same money and staff growth as repeated work',()=>{let a=fresh();a.money=0;a.lots=[];a.staff.push(E.makeStaff('komugi'));const bulk=act(a,'contractWork',{n:3});for(let i=0;i<3;i++)a=act(a,'contractWork');assert.equal(bulk.money,660);assert.deepEqual(bulk.staff,a.staff);assert.deepEqual(bulk.used,a.used);assert.equal(bulk.rng,a.rng);assert.equal(bulk.companyXP,0);reject(bulk,'contractWork',{n:3});reject(bulk,'contractWork',{n:-1})});
test('commission income counts as operating income but support does not masquerade as sales profit',()=>{let s=fresh();s.money=0;s.dailyCrop='off';s=act(s,'recoveryAid');s=act(s,'contractWork',{n:2});s=close(s);assert.equal(s.lastReport.contractIncome,440);assert.equal(s.lastReport.otherIncome,1440);assert.equal(s.lastReport.salesProfit,0);assert.equal(s.lastReport.profit,440)});
test('automatic recovery respects trial frames and daily forecast exactly matches actual income',()=>{let s=fresh();s.money=0;s.dailyCrop='off';s=act(s,'workPreset',{mode:'creative'});s=act(s,'financeConfig',{autoWork:true,target:1200});const before=JSON.stringify(s),pred=E.closingForecast(s);assert.equal(JSON.stringify(s),before);assert.equal(pred.report.financeWork.frames,4);assert.equal(pred.report.financeWork.income,880);s=close(s);assert.deepEqual(s.lastReport,pred.report);assert.equal(s.money,850)});
test('automatic commissions run after contract deliveries, stopping if they cover the cash target',()=>{let s=fresh();s.money=0;s.dailyCrop='off';const o=E.order(s,'bread',3,0,'sakura');s.orders.push({...o,reward:2000,acceptedDay:1,dueDay:1,auto:true});E.addLot(s,'bread',3);s=act(s,'financeConfig',{autoWork:true,target:1200});s=close(s);assert.equal(s.stats.delivered,1);assert.equal(s.lastReport.financeWork.frames,0);assert.equal(s.money,1970)});
test('automatic recovery never runs from rendering and uses only enough work to reach its target',()=>{let s=fresh();s.money=1100;s.dailyCrop='off';s=act(s,'financeConfig',{autoWork:true,target:1200});E.todayStatus(s);assert.equal(s.money,1100);s=close(s);assert.equal(s.lastReport.financeWork.frames,1);assert.equal(s.money,1290);s=close(s);assert.equal(s.lastReport.financeWork.frames,0)});
test('stock buyback pays below cost, observes daily cap and protects reserved and locked lots',()=>{let s=fresh();s.lots=[];const wheat=E.addLot(s,'wheat',20,0,0,12),locked=E.addLot(s,'milk',5,0,0,60,{locked:true}),reserved=E.addLot(s,'bread',3,0,0,40,{reservation:'ORDER'});assert.equal(E.stockSalePreview(s,wheat.lotId,3).unit,7);reject(s,'stockSale',{id:locked.lotId,n:1});reject(s,'stockSale',{id:reserved.lotId,n:1});const cash=s.money;s=act(s,'stockSale',{id:wheat.lotId,n:10});assert.equal(s.money,cash+70);assert.equal(s.ledger.cogs,120);reject(s,'stockSale',{id:wheat.lotId,n:1},/1日10個/);s=close(s);s=act(s,'stockSale',{id:wheat.lotId,n:1});assert.equal(s.finance.sold,1)});
test('buyback cannot yield profit by buying and immediately reselling, or sell expired and valueless lots',()=>{let s=fresh();s.lots=[];s=act(s,'buy',{id:'milk',n:5});const l=s.lots[0],q=E.stockSalePreview(s,l.lotId,5);assert.ok(q.ok);assert.ok(q.income<5*l.unitCost);const free=E.addLot(s,'wheat',1,0,0,0);reject(s,'stockSale',{id:free.lotId,n:1});s.day=4;reject(s,'stockSale',{id:l.lotId,n:1},/期限切れ/)});
test('unknown or corrupt applicant data, duplicate ids and forged relief duration are rejected on import',()=>{const s=act(fresh(),'recruit',{campaign:'listing'});for(const mutate of [x=>x.recruitment.candidates[0].stats.craft=-1,x=>x.recruitment.candidates[0].id=x.staff[0].id,x=>x.recruitment.candidates[0].rarity='神',x=>x.recruitment.candidates[0].appearance.hair='url(x)',x=>x.finance.reliefUntil=999]){const copy=E.clone(s);mutate(copy);assert.throws(()=>S.parse(JSON.stringify(S.envelope(copy))))}});
test('v56 migration preserves all owned staff and custom work plans without generating applicants or granting cash',()=>{const s=fresh();s.staff.push(E.makeStaff('komugi'),E.makeStaff('haru'));s.gameRulesVersion='2.1.0';s.contentVersion='56.0';delete s.recruitment;delete s.finance;s.workPlan.budget=378;s.workPlan.enabled=true;const before=E.clone(s),up=S.parse(JSON.stringify(S.envelope(s))).runs[s.runId];assert.equal(up.gameRulesVersion,E.D.rules);assert.equal(up.contentVersion,E.D.content);for(const k of ['staff','money','workPlan','orders','lots','recipes','initialEvaluation','rng','companyXP'])assert.deepEqual(up[k],before[k]);assert.equal(up.recruitment.candidates.length,0);assert.equal(up.finance.autoWork,false);assert.equal(up.finance.aidDay,0)});
test('full locked warehouse at zero cash does not prevent material-free recovery',()=>{let s=fresh();s.money=0;s.lots=[];E.addLot(s,'wheat',E.capacity(s),0,0,12,{locked:true});const lots=E.clone(s.lots);s=act(s,'contractWork',{n:2});assert.equal(s.money,440);assert.deepEqual(s.lots,lots);s=act(s,'recoveryAid');assert.equal(s.money,1440)});
test('recruitment corruption and forged candidate stats fail before UI is loaded',()=>{const s=act(fresh(),'recruit',{campaign:'flyer'});s.recruitment.history=[null];assert.throws(()=>S.parse(JSON.stringify(S.envelope(s))),/募集履歴/)});
test('cash-zero recovery reaches a delivery across seeds and all initial scenarios',()=>{for(const seed of ['KO-MOREBI','FEAST-2026','FRIENDS'])for(const scenario of Object.keys(E.D.scenarios)){let s=E.newGame(seed,scenario);s.money=0;s.lots=[];s.used.craft=E.craftLimit(s);s.used.produce=E.productionLimit(s);s=act(s,'recoveryAid');s=close(s);s=S.parse(JSON.stringify(S.envelope(s))).runs[s.runId];assert.equal(E.aidPreview(s).ok,false);const candidate=s.candidates.find(o=>E.offerPreview(s,o.id).ok);assert.ok(candidate,seed+' '+scenario);s=act(s,'acceptAndDeliver',{id:candidate.id});assert.equal(s.stats.delivered,1);assert.ok(s.money>0)}});
