'use strict';const E=require('../actions.js'),S=require('../storage.js'),fs=require('fs');
function run(seed,route){let s=E.newGame(seed),operations=0,errors=[],unlockDays={},maxLots=0;const act=(a,p={})=>{const r=E.transact(s,a,p);if(r.ok){s=r.state;operations++;return true}return false};
function ensure(id,n,min=0,depth=0){if(depth>10)return false;let need=n-E.qty(s,id,min);if(need<=0)return true;const d=E.item(s,id);if(!d||!E.unlocked(s,id))return false;if(d.farm){let attempts=0;while(E.qty(s,id,min)<n&&attempts++<8){if(!act('produce',{id,n:Math.min(E.produceBatch(s),Math.max(1,n-E.qty(s,id,min)),Math.max(0,E.capacity(s)-E.total(s)))}))return false}return E.qty(s,id,min)>=n}if(d.buy){const k=Math.ceil(need/E.supplyUnit(s))*E.supplyUnit(s);return act('buy',{id,n:k})&&E.qty(s,id,min)>=n}if(d.recipe){let attempts=0;while(E.qty(s,id,min)<n&&attempts++<5){const amount=Math.min(E.batch(s),Math.max(1,n-E.qty(s,id,min)));for(const [k,v]of Object.entries(d.recipe))if(!ensure(k,amount*v,0,depth+1))return false;if(!act('craft',{id,n:amount}))return false}return E.qty(s,id,min)>=n}return false}
const invest=()=>{const researchOrder=route==='quality'?['quality','production','processing','recipe','storage','sales']:route==='research'?['recipe','processing','quality','production','storage','sales']:route==='regional'?['sales','processing','recipe','production','quality','storage']:['processing','production','quality','recipe','sales','storage'];for(const k of researchOrder){if(s.research[k]<(route==='novice'?2:k==='quality'&&route==='quality'?6:k==='recipe'&&route==='research'?5:4)){if(s.rp>=E.D.research[k].base*(s.research[k]+1)+15)act('research',{id:k});break}}
const targets=route==='novice'?['workshop']:route==='quality'?['workshop','workshop','warehouse']:route==='research'?['lab','workshop','sales','warehouse']:route==='regional'?['sales','workshop','warehouse','lab']:['workshop','workshop','warehouse','sales'];
if(s.staff.length<targets.length+1&&s.money>3500){const role=targets[s.staff.length-1],applicant=s.recruitment.candidates.filter(t=>t.assigned===role).sort((a,b)=>b.stats[E.D.roles[role].stat]-a.stats[E.D.roles[role].stat])[0];if(applicant)act('hire',{id:applicant.id});else if(s.recruitment.lastDay!==s.day)act('recruit',{campaign:route==='novice'?'flyer':'listing',focus:role})}

for(const id of ['warehouse','workshop','farm','lab']){const wanted=route==='novice'?2:route==='quality'&&id==='farm'?4:3,cost=Math.round(E.D.facilities[id].base*1.65**(s.facilities[id]-1));if(s.facilities[id]<wanted&&s.money>cost+3000){act('facility',{id});break}}
if(route!=='novice'&&s.day>8&&(route!=='quality'||s.research.quality>=5)){const preferred=route==='quality'?'bread':route==='research'?'sweets':route==='regional'?'bento':'bread';if(E.unlocked(s,preferred)&&(s.standardized[preferred]||0)<(route==='quality'?3:1)&&s.rp>70)act('standardize',{id:preferred})}
if((route!=='quality'||s.research.quality>=5)&&s.money>6000&&s.rp>80&&s.supplierLevel<3&&['quality','research'].includes(route))act('supplier');
if(route==='regional'||s.day>25&&['mass','quality','research'].includes(route)&&s.regions.length<({mass:3,quality:2,research:2}[route])){const next=Object.keys(E.D.regions).find(k=>!s.regions.includes(k));if(next){const d=E.D.regions[next];if(E.level(s)>=d.lv&&s.reputation>=d.rep&&s.money>d.cost+2000)act('region',{id:next})}}
if(s.day>=12&&route==='mass'){for(const id of ['flourMill','breadFactory'])if(!s.auto[id]&&s.money>E.D.auto[id].cost+4000){act('autoBuild',{id});act('autoConfig',{id,target:3,budget:500,minQuality:0,enabled:true})}}
if(s.day>=8&&route==='mass')act('policy',{policy:'mass'});if(s.day>=8&&route==='quality')act('policy',{policy:'careful'});
};
for(let day=1;day<=75;day++){if(s.ended){if(!act('continue'))break}invest();if(s.event?.story)act('storyChoice',{choice:route==='mass'?'offer':'learn'});else if(s.event){const ev=E.D.events[s.event.index];let choice=ev.options[0][0];if(ev.kind==='price'&&s.money<400)choice='accept';if(ev.kind==='repair'&&s.money<400)choice='slow';if(ev.kind==='delivery'&&s.money<300)choice='wait';act('event',{choice})}
for(const o of [...s.orders]){if(ensure(o.itemId,o.quantity,o.minQuality))act('deliver',{id:o.id})}
let safe=0;while(s.used.accept< (route==='novice'?1:E.acceptLimit(s))&&s.orders.length<2+Math.floor(s.research.sales/2)&&safe++<6){let candidates=[...s.candidates].filter(o=>o.minQuality<=(route==='quality'?4:route==='novice'?0:1));candidates.sort((a,b)=>{const rank=id=>route==='research'?(['sweets','deli','bento'].includes(id)?4:0):route==='quality'?(id==='bread'?5:0):route==='mass'?(id==='bread'?3:0):0;return rank(b.itemId)-rank(a.itemId)||(b.reward-E.standardCost(s,b.itemId)*b.quantity)-(a.reward-E.standardCost(s,a.itemId)*a.quantity)});let selected=null;for(const o of candidates){const pl=E.planning(s,o);if(!pl.steps.some(x=>x.locked)&&pl.crafts<=E.craftLimit(s)-s.used.craft&&pl.produces<=E.productionLimit(s)-s.used.produce&&pl.cost<s.money*.7){selected=o;break}}if(!selected)break;if(ensure(selected.itemId,selected.quantity,selected.minQuality)&&act('accept',{id:selected.id}))act('deliver',{id:s.orders[s.orders.length-1].id});else break}
if(route==='research'&&s.day>=18&&s.rp>=35&&s.used.craft<E.craftLimit(s)){if(!s.recipes.length){if(ensure('flour',1)&&ensure('milk',1))act('prototype',{name:'ひだまりミルク',main:'flour',ingredients:{flour:1,milk:1}})}else{const r=s.recipes[0];if(r.completion<100)act('refine',{id:r.id});else if(!r.formal)act('formalize',{id:r.id});else if(!E.qty(s,r.id)&&s.day>=50)ensure(r.id,1)}}
for(const [key,c]of Object.entries(E.D.contests)){const date=E.nextContest(s,key);if(date-s.day<=5&&date>s.day&&!s.contestEntries.some(e=>e.key===key)){const lot=[...s.lots].filter(l=>!l.reservation&&!l.locked&&(c.original?E.item(s,l.itemId).formal:c.product?l.itemId===c.product:E.item(s,l.itemId).kind==='food')).sort((a,b)=>b.qualityRank-a.qualityRank)[0];if(lot)act('contest',{key,lot:lot.lotId})}}
if(route!=='novice'){for(const id of ['wheat','vegetable','flour','bread','salad']){if(E.qty(s,id)>4&&!s.orders.some(o=>o.itemId===id))act('wholesale',{id,target:3})}}
if(s.money<500&&s.used.craft<E.craftLimit(s))act('contractWork');
for(const id of Object.keys(E.D.items))if(E.unlocked(s,id)&&!unlockDays[id])unlockDays[id]=s.day;
const r=E.transact(s,'nextDay',{day:s.day});if(!r.ok){errors.push({day:s.day,error:r.error});break}s=r.state;operations++;maxLots=Math.max(maxLots,s.lots.length);if(day%10===0){const restored=S.parse(JSON.stringify(S.envelope(s))).runs[s.runId];if(JSON.stringify(s)!==JSON.stringify(restored))throw Error('serialization mismatch')}
}
return {seed,route,finalDay:s.day,cash:s.money,profit:Math.round(s.stats.profit),delivered:s.stats.delivered,failed:s.stats.failed,waste:s.stats.waste,companyLevel:E.level(s),reputation:s.reputation,bestQuality:Math.max(0,...Object.values(s.records)),rp:s.rp,operations,regions:s.regions.length,recipes:s.recipes.length,formal:s.recipes.filter(r=>r.formal).length,awards:s.contestHistory.map(h=>h.grade),ending:s.initialEvaluation?.ending,unlockDays,researchLevels:s.research,maxLots,errors,state:s}}
const rows=[];for(const route of ['novice','mass','quality','research','regional'])for(const seed of ['KO-MOREBI','FEAST-2026','FRIENDS']){const r=run(seed,route),{state,...summary}=r;rows.push(summary);if(route==='research'&&seed==='KO-MOREBI')fs.writeFileSync(__dirname+'/advanced-test-save.json',JSON.stringify(S.envelope(state)));console.log(route,seed,'day',r.finalDay,'cash',r.cash,'delivered',r.delivered,'failed',r.failed,'waste',r.waste,'quality',r.bestQuality,'regions',r.regions,'formal',r.formal,'errors',r.errors.length)}fs.writeFileSync(__dirname+'/simulation-results.json',JSON.stringify(rows,null,2));if(rows.some(r=>r.errors.length||r.finalDay<76))process.exitCode=1;
