'use strict';// VM template test: NOT a browser/DOM layout test.
const vm=require('node:vm'),fs=require('fs'),assert=require('node:assert/strict'),test=require('node:test');
const E=require('../actions.js'),S=require('../storage.js');
const decode=s=>String(s||'').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&');
function attrs(text){const a={};for(const m of text.matchAll(/([\w-]+)="([^"]*)"/g))a[m[1]]=decode(m[2]);return a}
function setup(){const els={},listeners={},data={};class Element{constructor(id=''){this.id=id;this._html='';this.value='';this.disabled=false;this.checked=false;this.open=false;this.classList={toggle(){},add(){},remove(){}};this.dataset={};this.style={}}set innerHTML(html){this._html=html;for(const m of html.matchAll(/<(input|select|button|div|span|h2|p)([^>]*?\bid="[^"]+"[^>]*)>([\s\S]*?)(?:<\/\1>|(?=<))/g)){const a=attrs(m[2]);let el=els[a.id]||(els[a.id]=new Element(a.id));Object.assign(el,{value:a.value||'',checked:/\bchecked\b/.test(m[2]),max:a.max,min:a.min});el.dataset=Object.fromEntries(Object.entries(a).filter(([k])=>k.startsWith('data-')).map(([k,v])=>[k.slice(5),v]));if(m[1]==='select'){const opts=[...m[3].matchAll(/<option([^>]*)>([^<]*)/g)],o=opts.find(o=>/selected/.test(o[1]))||opts[0];el.value=o?attrs(o[1]).value:''}}for(const m of html.matchAll(/<input([^>]+)>/g)){const a=attrs(m[1]);if(a.id){const el=els[a.id]||(els[a.id]=new Element(a.id));el.value=a.value||'';el.checked=/\bchecked\b/.test(m[1]);el.dataset=Object.fromEntries(Object.entries(a).filter(([k])=>k.startsWith('data-')).map(([k,v])=>[k.slice(5),v]))}}for(const m of html.matchAll(/<select([^>]+)>([\s\S]*?)<\/select>/g)){const a=attrs(m[1]);if(!a.id)continue;const el=els[a.id]||(els[a.id]=new Element(a.id)),opts=[...m[2].matchAll(/<option([^>]*)>/g)],o=opts.find(o=>/selected/.test(o[1]))||opts[0];el.value=o?attrs(o[1]).value:'';el.dataset=Object.fromEntries(Object.entries(a).filter(([k])=>k.startsWith('data-')).map(([k,v])=>[k.slice(5),v]))}}get innerHTML(){return this._html}addEventListener(k,f){(listeners[this.id+':'+k]||=([])).push(f)}querySelector(){return new Element()}showModal(){this.open=true}close(){this.open=false}appendChild(){}remove(){}click(){}getBoundingClientRect(){return {left:0,right:400,top:0,bottom:800}}}
for(const id of ['header','main','nav','daybar','sheet','sheet-body','save-warning','toast','celebrate','import-file'])els[id]=new Element(id);
const document={getElementById:id=>els[id]||(els[id]=new Element(id)),body:new Element('body'),querySelector:()=>null,querySelectorAll:sel=>sel==='[data-ingredient]'?Object.values(els).filter(e=>e.dataset.ingredient):sel==='[data-substitute]'?Object.values(els).filter(e=>e.dataset.substitute):[],addEventListener(k,f){(listeners[k]||=([])).push(f)},createElement:()=>new Element(),hidden:false};
const context={console,document,localStorage:{getItem:k=>data[k]||null,setItem:(k,v)=>data[k]=v},URLSearchParams,location:{search:'?qa=1'},setTimeout:()=>0,clearTimeout(){},setInterval:()=>0,clearInterval(){},Blob,URL,Math,Date,JSON,Number,String,Object,Array,Map,Set,Error,Boolean,Promise};context.window=context;context.globalThis=context;context.addEventListener=(k,f)=>(listeners['window:'+k]||=[]).push(f);context.scrollTo=()=>{};context.scrollY=0;context.GCAudio={setup(){},effect(){},unlock(){}};vm.createContext(context);for(const file of ['data.js','flavor.js','engine.js','actions.js','planning.js','recruitment.js','finance.js','advisor.js','guidance.js','dining.js','progression.js','storage.js','art.js','ui.js'])vm.runInContext(fs.readFileSync(__dirname+'/../'+file,'utf8'),context,{filename:file});return {context,els,listeners,click(action,p={}){const el=new Element();el.dataset={a:action,p:JSON.stringify(p),seq:String(context.GCApp.state?context.GCApp.state.transactionSeq+1:0)};el.closest=()=>el;for(const handler of listeners.click)handler({target:{closest:selector=>selector==='[data-a]'?el:null}})}}}
const routes=['home','make/plan','make/craft','make/produce','make/buy','make/inventory','make/original','trade/orders','trade/finance','trade/customers','trade/wholesale','trade/regions','grow/staff','grow/recruit','grow/research','grow/facilities','grow/auto','grow/invest','more/book','more/contests','more/rivals','more/timeline','more/settings'];
function allButtons(html){return [...html.matchAll(/<button\b([^>]*)>/g)].map(m=>attrs(m[1])).filter(a=>a['data-a'])}
test('all UI page templates render and every displayed action exists, fresh + advanced',()=>{const t=setup(),advanced=S.parse(fs.readFileSync(__dirname+'/advanced-test-save.json','utf8')),reports=[];for(const state of [E.newGame('UI'),advanced.runs[advanced.current]]){t.context.GCApp.loadForTest(state);for(const route of routes){t.context.GCApp.go(route);const html=t.els.main.innerHTML;assert.ok(html.length>100,route);assert.ok(!html.includes('undefined'),route+' undefined visible');const buttons=allButtons(html+t.els.nav.innerHTML+t.els.daybar.innerHTML);for(const a of buttons)assert.ok(t.context.GCApp.handlers.includes(a['data-a']),route+' unbound '+a['data-a']);reports.push({day:state.day,route,bytes:html.length,buttons:buttons.length})}}fs.writeFileSync(__dirname+'/ui-template-results.json',JSON.stringify(reports,null,2));});
test('welcome startup handler creates a saved run in isolated QA namespace',()=>{const t=setup();assert.ok(t.els.main.innerHTML.includes('会社をはじめる'));t.click('welcomeStart');t.els['new-name'].value='UI試験の会社';t.els['new-seed'].value='QA';t.els['new-scenario'].value='standard';t.click('startNew');assert.equal(t.context.GCApp.state.name,'UI試験の会社');assert.ok(t.els.header.innerHTML.includes('保存済み'))});
test('craft, procurement, production, contract preparation and daily preview sheets generate without errors',()=>{const t=setup();t.context.GCApp.loadForTest(E.newGame('UI'));for(const [action,p,text]of [['craftSheet',{id:'flour'},'工房の製造計画'],['buySheet',{id:'milk'},'素材の仕入れ'],['produceSheet',{id:'wheat'},'畑の収穫'],['planSheet',{id:t.context.GCApp.state.candidates[0].id},'この注文への道のり'],['dayPreview',{},'営業を終えますか']]){t.click(action,p);assert.ok(t.els['sheet-body'].innerHTML.includes(text),action);assert.ok(!t.els.toast.textContent?.includes('操作を完了できませんでした'),action+' '+t.els.toast.textContent);t.click('close')}});
test('UI escapes imported names as text',()=>{const t=setup(),s=E.newGame('XSS');s.name='<img src=x onerror=alert(1)>';s.staff[0].name='<script>alert(1)</script>';t.context.GCApp.loadForTest(s);assert.ok(!t.els.header.innerHTML.includes('<img'));t.context.GCApp.go('grow/staff');assert.ok(t.els.main.innerHTML.includes('&lt;script&gt;'))});
